// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * From is who shared a note: their name then and their squad colour.
 */
export class From {
    "name": string;
    "color"?: string;

    /** Creates a new From instance. */
    constructor($$source: Partial<From> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new From instance from a string or object.
     */
    static createFrom($$source: any = {}): From {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new From($$parsedSource as Partial<From>);
    }
}

/**
 * Note is one snap note. Strokes is the shell's drawing, kept as it sends it.
 */
export class Note {
    "id": string;
    "title": string;
    "url"?: string;
    "pageTitle"?: string;
    "linked": boolean;
    "favorite"?: boolean;

    /**
     * Spot is where a note from a game screenshot was taken, when its file
     * name has the position.
     */
    "spot"?: Spot | null;

    /**
     * From is the squadmate a note shared with the squad came from.
     */
    "from"?: From | null;
    "full"?: boolean;
    "width": number;
    "height": number;
    "createdAt": string;

    /**
     * UpdatedAt is when the drawing or title last changed (the list is in
     * that order); ChangedAt when anything did, the star or a removal too, to
     * merge copies of a note if notes are ever synced (internal/userdata).
     */
    "updatedAt": string;
    "changedAt"?: string;
    "strokes"?: json$0.RawMessage;

    /**
     * Deleted is a removed note: its images are gone and its note.json
     * stays as a tombstone for tombstoneAge, so that a copy still having it
     * does not bring it back.
     */
    "deleted"?: boolean;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("linked" in $$source)) {
            this["linked"] = false;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("spot" in $$parsedSource) {
            $$parsedSource["spot"] = $$createField6_0($$parsedSource["spot"]);
        }
        if ("from" in $$parsedSource) {
            $$parsedSource["from"] = $$createField7_0($$parsedSource["from"]);
        }
        return new Note($$parsedSource as Partial<Note>);
    }
}

/**
 * Spot is a place in a raid: the map (tarkov.dev's name for it, "" when not
 * known), the position and the direction faced (degrees).
 */
export class Spot {
    "map"?: string;
    "x": number;
    "y": number;
    "z": number;
    "rotation": number;

    /** Creates a new Spot instance. */
    constructor($$source: Partial<Spot> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("z" in $$source)) {
            this["z"] = 0;
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Spot instance from a string or object.
     */
    static createFrom($$source: any = {}): Spot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Spot($$parsedSource as Partial<Spot>);
    }
}

// Private type creation functions
const $$createType0 = Spot.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = From.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
