// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Options are logical-pixel offsets inside the trusted main window.
 */
export class Options {
    "id": string;
    "url": string;
    "left": number;
    "top": number;

    /**
     * Right and Bottom keep strips of the window free on the right and at
     * the bottom, for the sidebars placed there.
     */
    "right": number;
    "bottom": number;

    /**
     * Background ("#rrggbb") fills the view until the page paints, so a
     * switch or a slow page does not flash white.
     */
    "background": string;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("left" in $$source)) {
            this["left"] = 0;
        }
        if (!("top" in $$source)) {
            this["top"] = 0;
        }
        if (!("right" in $$source)) {
            this["right"] = 0;
        }
        if (!("bottom" in $$source)) {
            this["bottom"] = 0;
        }
        if (!("background" in $$source)) {
            this["background"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options($$parsedSource as Partial<Options>);
    }
}
