// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Record is what MAYAK made of one screenshot, kept for the screenshot
 * list: what it was recognized as, how sure it was, and what it matched.
 */
export class Record {
    "at": string;

    /**
     * tasks, item, position or unknown
     */
    "type": string;
    "layout"?: string;
    "score"?: number;
    "map"?: string;
    "raid": boolean;
    "stage"?: string;

    /**
     * Match is the task or item recognized; Detail its trader or short name.
     */
    "match"?: string;
    "matchId"?: string;
    "detail"?: string;
    "confidence"?: number;
    "candidates"?: string[];
    "ocr"?: string;
    "position"?: string;
    "error"?: string;

    /** Creates a new Record instance. */
    constructor($$source: Partial<Record> = {}) {
        if (!("at" in $$source)) {
            this["at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("raid" in $$source)) {
            this["raid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     */
    static createFrom($$source: any = {}): Record {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField11_0($$parsedSource["candidates"]);
        }
        return new Record($$parsedSource as Partial<Record>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
