// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HideoutItemAttributes {
    "foundInRaid": boolean;

    /** Creates a new HideoutItemAttributes instance. */
    constructor($$source: Partial<HideoutItemAttributes> = {}) {
        if (!("foundInRaid" in $$source)) {
            this["foundInRaid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutItemAttributes instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutItemAttributes {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HideoutItemAttributes($$parsedSource as Partial<HideoutItemAttributes>);
    }
}

export class HideoutItemRequirement {
    "item": string;
    "name": string;
    "count": number;
    "attributes": HideoutItemAttributes;

    /** Creates a new HideoutItemRequirement instance. */
    constructor($$source: Partial<HideoutItemRequirement> = {}) {
        if (!("item" in $$source)) {
            this["item"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = (new HideoutItemAttributes());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutItemRequirement instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutItemRequirement {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField3_0($$parsedSource["attributes"]);
        }
        return new HideoutItemRequirement($$parsedSource as Partial<HideoutItemRequirement>);
    }
}

export class HideoutLevel {
    "id": string;
    "level": number;
    "constructionTime": number;
    "itemRequirements": HideoutItemRequirement[];
    "stationLevelRequirements": HideoutStationRequirement[];
    "traderRequirements": HideoutTraderRequirement[];
    "skillRequirements": HideoutSkillRequirement[];

    /** Creates a new HideoutLevel instance. */
    constructor($$source: Partial<HideoutLevel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }
        if (!("constructionTime" in $$source)) {
            this["constructionTime"] = 0;
        }
        if (!("itemRequirements" in $$source)) {
            this["itemRequirements"] = [];
        }
        if (!("stationLevelRequirements" in $$source)) {
            this["stationLevelRequirements"] = [];
        }
        if (!("traderRequirements" in $$source)) {
            this["traderRequirements"] = [];
        }
        if (!("skillRequirements" in $$source)) {
            this["skillRequirements"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutLevel instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutLevel {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("itemRequirements" in $$parsedSource) {
            $$parsedSource["itemRequirements"] = $$createField3_0($$parsedSource["itemRequirements"]);
        }
        if ("stationLevelRequirements" in $$parsedSource) {
            $$parsedSource["stationLevelRequirements"] = $$createField4_0($$parsedSource["stationLevelRequirements"]);
        }
        if ("traderRequirements" in $$parsedSource) {
            $$parsedSource["traderRequirements"] = $$createField5_0($$parsedSource["traderRequirements"]);
        }
        if ("skillRequirements" in $$parsedSource) {
            $$parsedSource["skillRequirements"] = $$createField6_0($$parsedSource["skillRequirements"]);
        }
        return new HideoutLevel($$parsedSource as Partial<HideoutLevel>);
    }
}

export class HideoutSkillRequirement {
    "skill": string;
    "level": number;

    /** Creates a new HideoutSkillRequirement instance. */
    constructor($$source: Partial<HideoutSkillRequirement> = {}) {
        if (!("skill" in $$source)) {
            this["skill"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutSkillRequirement instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutSkillRequirement {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HideoutSkillRequirement($$parsedSource as Partial<HideoutSkillRequirement>);
    }
}

export class HideoutStationRequirement {
    "station": string;
    "name": string;
    "level": number;

    /** Creates a new HideoutStationRequirement instance. */
    constructor($$source: Partial<HideoutStationRequirement> = {}) {
        if (!("station" in $$source)) {
            this["station"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutStationRequirement instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutStationRequirement {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HideoutStationRequirement($$parsedSource as Partial<HideoutStationRequirement>);
    }
}

export class HideoutTraderRequirement {
    "trader": string;
    "name": string;
    "level": number;

    /** Creates a new HideoutTraderRequirement instance. */
    constructor($$source: Partial<HideoutTraderRequirement> = {}) {
        if (!("trader" in $$source)) {
            this["trader"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutTraderRequirement instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutTraderRequirement {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HideoutTraderRequirement($$parsedSource as Partial<HideoutTraderRequirement>);
    }
}

// Private type creation functions
const $$createType0 = HideoutItemAttributes.createFrom;
const $$createType1 = HideoutItemRequirement.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = HideoutStationRequirement.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = HideoutTraderRequirement.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = HideoutSkillRequirement.createFrom;
const $$createType8 = $Create.Array($$createType7);
