// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Member is one player in the room, as last reported.
 */
export class Member {
    "id": string;
    "me": boolean;
    "name": string;

    /**
     * Viewer is a PC that only watches: a client of a Host in the squad,
     * the same player, so the others leave it out of their list.
     */
    "viewer"?: boolean;
    "map"?: string;
    "pos"?: Position | null;

    /**
     * At is when the position was taken.
     */
    "at"?: string;

    /**
     * Color is the squad colour chosen ("#rrggbb"), or empty for one given
     * by the others (map-geo.js assignColors). Older builds leave it out.
     */
    "color"?: string;

    /**
     * Key is this PC's member key (32 hex digits), the same across
     * reconnections, which the squad's lines are owned by (map-draw.js).
     */
    "key"?: string;

    /** Creates a new Member instance. */
    constructor($$source: Partial<Member> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("me" in $$source)) {
            this["me"] = false;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Member instance from a string or object.
     */
    static createFrom($$source: any = {}): Member {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pos" in $$parsedSource) {
            $$parsedSource["pos"] = $$createField5_0($$parsedSource["pos"]);
        }
        return new Member($$parsedSource as Partial<Member>);
    }
}

/**
 * Position is a player's place in a raid, in the game's coordinates, and
 * which way they face (degrees).
 */
export class Position {
    "x": number;
    "y": number;
    "z": number;
    "rot": number;

    /** Creates a new Position instance. */
    constructor($$source: Partial<Position> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("z" in $$source)) {
            this["z"] = 0;
        }
        if (!("rot" in $$source)) {
            this["rot"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     */
    static createFrom($$source: any = {}): Position {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position($$parsedSource as Partial<Position>);
    }
}

/**
 * State is the room as this PC sees it.
 */
export class State {
    "code": string;
    "phase": string;
    "members": Member[];

    /**
     * Drawing is whether the relay takes the squad pen's messages (it
     * said so in its welcome); an older relay would drop this PC for them.
     */
    "drawing": boolean;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("members" in $$source)) {
            this["members"] = [];
        }
        if (!("drawing" in $$source)) {
            this["drawing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("members" in $$parsedSource) {
            $$parsedSource["members"] = $$createField2_0($$parsedSource["members"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

// Private type creation functions
const $$createType0 = Position.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Member.createFrom;
const $$createType3 = $Create.Array($$createType2);
