// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Member is one player in the room, as last reported.
 */
export class Member {
    "id": string;
    "me": boolean;
    "name": string;

    /**
     * Viewer is a PC that only watches: a client of a Host in the squad,
     * the same player, so the others leave it out of their list.
     */
    "viewer"?: boolean;
    "map"?: string;
    "pos"?: Position | null;

    /**
     * At is when the position was taken.
     */
    "at"?: string;

    /**
     * Color is the squad colour chosen ("#rrggbb"), or empty for one given
     * by the others (map-geo.js assignColors). Older builds leave it out.
     */
    "color"?: string;

    /**
     * Key is this PC's member key (32 hex digits), the same across
     * reconnections, which the squad's lines are owned by (map-draw.js).
     */
    "key"?: string;

    /**
     * Tracker is this player's TarkovTracker progress in short, when they
     * sync with it: shown on their card in the others' sidebar.
     */
    "tracker"?: Tracker | null;

    /**
     * Profile is what this player's Overall screen showed when last read.
     */
    "profile"?: Profile | null;

    /** Creates a new Member instance. */
    constructor($$source: Partial<Member> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("me" in $$source)) {
            this["me"] = false;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Member instance from a string or object.
     */
    static createFrom($$source: any = {}): Member {
        const $$createField5_0 = $$createType1;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pos" in $$parsedSource) {
            $$parsedSource["pos"] = $$createField5_0($$parsedSource["pos"]);
        }
        if ("tracker" in $$parsedSource) {
            $$parsedSource["tracker"] = $$createField9_0($$parsedSource["tracker"]);
        }
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField10_0($$parsedSource["profile"]);
        }
        return new Member($$parsedSource as Partial<Member>);
    }
}

/**
 * Position is a player's place in a raid, in the game's coordinates, and
 * which way they face (degrees).
 */
export class Position {
    "x": number;
    "y": number;
    "z": number;
    "rot": number;

    /** Creates a new Position instance. */
    constructor($$source: Partial<Position> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("z" in $$source)) {
            this["z"] = 0;
        }
        if (!("rot" in $$source)) {
            this["rot"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     */
    static createFrom($$source: any = {}): Position {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position($$parsedSource as Partial<Position>);
    }
}

/**
 * Profile is a player's Overall screen in short: the nickname, the level,
 * raids, kills, the survival rate, K/D, hours online, and when the picture
 * of their character was taken (unix seconds; 0 for none), which the
 * others fetch from the squad's store (StoreIn "picture").
 */
export class Profile {
    "name"?: string;
    "level"?: number;
    "raids"?: number;
    "kills"?: number;
    "sr"?: number;
    "kd"?: number;
    "hours"?: number;
    "picture"?: number;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

/**
 * State is the room as this PC sees it.
 */
export class State {
    "code": string;
    "phase": string;
    "members": Member[];

    /**
     * Drawing is whether the relay takes the squad pen's messages (it
     * said so in its welcome); an older relay would drop this PC for them.
     */
    "drawing": boolean;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("members" in $$source)) {
            this["members"] = [];
        }
        if (!("drawing" in $$source)) {
            this["drawing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("members" in $$parsedSource) {
            $$parsedSource["members"] = $$createField2_0($$parsedSource["members"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

/**
 * Tracker is a player's TarkovTracker progress in short: the name there,
 * the level, the game mode (pvp, pve), the tasks completed and failed, and
 * the TarkovTracker user (for the link to their shared profile).
 */
export class Tracker {
    "name"?: string;
    "level"?: number;
    "mode"?: string;
    "done"?: number;
    "failed"?: number;
    "user"?: string;

    /** Creates a new Tracker instance. */
    constructor($$source: Partial<Tracker> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tracker instance from a string or object.
     */
    static createFrom($$source: any = {}): Tracker {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tracker($$parsedSource as Partial<Tracker>);
    }
}

// Private type creation functions
const $$createType0 = Position.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Tracker.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = Profile.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = Member.createFrom;
const $$createType7 = $Create.Array($$createType6);
