// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hideoutlog$0 from "../hideoutlog/models.js";

export class CatalogStatus {
    "state": string;
    "mode": string;
    "updatedAt": string;
    "items": number;
    "maps": number;
    "traders": number;
    "tasks": number;
    "hideoutStations": number;
    "scavCooldownSeconds": number;
    "playerLevels": number;
    "lastError": string;

    /** Creates a new CatalogStatus instance. */
    constructor($$source: Partial<CatalogStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = 0;
        }
        if (!("maps" in $$source)) {
            this["maps"] = 0;
        }
        if (!("traders" in $$source)) {
            this["traders"] = 0;
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = 0;
        }
        if (!("hideoutStations" in $$source)) {
            this["hideoutStations"] = 0;
        }
        if (!("scavCooldownSeconds" in $$source)) {
            this["scavCooldownSeconds"] = 0;
        }
        if (!("playerLevels" in $$source)) {
            this["playerLevels"] = 0;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogStatus($$parsedSource as Partial<CatalogStatus>);
    }
}

export class HideoutStationProgress {
    "id": string;
    "name": string;
    "normalizedName": string;
    "areaType": number;
    "levels": catalog$0.HideoutLevel[];
    "currentLevel": number;
    "completedLevels": number[];
    "nextLevel"?: catalog$0.HideoutLevel | null;

    /** Creates a new HideoutStationProgress instance. */
    constructor($$source: Partial<HideoutStationProgress> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("normalizedName" in $$source)) {
            this["normalizedName"] = "";
        }
        if (!("areaType" in $$source)) {
            this["areaType"] = 0;
        }
        if (!("levels" in $$source)) {
            this["levels"] = [];
        }
        if (!("currentLevel" in $$source)) {
            this["currentLevel"] = 0;
        }
        if (!("completedLevels" in $$source)) {
            this["completedLevels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutStationProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutStationProgress {
        const $$createField4_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("levels" in $$parsedSource) {
            $$parsedSource["levels"] = $$createField4_0($$parsedSource["levels"]);
        }
        if ("completedLevels" in $$parsedSource) {
            $$parsedSource["completedLevels"] = $$createField6_0($$parsedSource["completedLevels"]);
        }
        if ("nextLevel" in $$parsedSource) {
            $$parsedSource["nextLevel"] = $$createField7_0($$parsedSource["nextLevel"]);
        }
        return new HideoutStationProgress($$parsedSource as Partial<HideoutStationProgress>);
    }
}

export class HideoutStatus {
    "state": string;
    "mode": string;
    "accountId": string;
    "profileId": string;
    "completed": number;
    "total": number;
    "stations": HideoutStationProgress[];
    "events": hideoutlog$0.Event[];
    "lastError": string;

    /** Creates a new HideoutStatus instance. */
    constructor($$source: Partial<HideoutStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("completed" in $$source)) {
            this["completed"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("stations" in $$source)) {
            this["stations"] = [];
        }
        if (!("events" in $$source)) {
            this["events"] = [];
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutStatus {
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stations" in $$parsedSource) {
            $$parsedSource["stations"] = $$createField6_0($$parsedSource["stations"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField7_0($$parsedSource["events"]);
        }
        return new HideoutStatus($$parsedSource as Partial<HideoutStatus>);
    }
}

export class ItemCandidate {
    "id": string;
    "name": string;
    "shortName": string;
    "url": string;
    "iconUrl": string;
    "confidence": number;

    /** Creates a new ItemCandidate instance. */
    constructor($$source: Partial<ItemCandidate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("iconUrl" in $$source)) {
            this["iconUrl"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCandidate($$parsedSource as Partial<ItemCandidate>);
    }
}

export class LogEntry {
    "id": number;
    "timestamp": string;
    "level": string;
    "category": string;
    "message": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class Position {
    "x": number;
    "y": number;
    "z": number;
    "rotation": number;
    "detectedAt": string;

    /** Creates a new Position instance. */
    constructor($$source: Partial<Position> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("z" in $$source)) {
            this["z"] = 0;
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }
        if (!("detectedAt" in $$source)) {
            this["detectedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     */
    static createFrom($$source: any = {}): Position {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position($$parsedSource as Partial<Position>);
    }
}

export class QuestCandidate {
    "id": string;
    "name": string;
    "trader": string;
    "map": string;
    "confidence": number;

    /** Creates a new QuestCandidate instance. */
    constructor($$source: Partial<QuestCandidate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("trader" in $$source)) {
            this["trader"] = "";
        }
        if (!("map" in $$source)) {
            this["map"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestCandidate($$parsedSource as Partial<QuestCandidate>);
    }
}

export class QuestObjective {
    "description": string;
    "maps": string[];

    /** Creates a new QuestObjective instance. */
    constructor($$source: Partial<QuestObjective> = {}) {
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("maps" in $$source)) {
            this["maps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestObjective instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestObjective {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("maps" in $$parsedSource) {
            $$parsedSource["maps"] = $$createField1_0($$parsedSource["maps"]);
        }
        return new QuestObjective($$parsedSource as Partial<QuestObjective>);
    }
}

export class Status {
    "hideout": HideoutStatus;
    "catalog": CatalogStatus;
    "connection": string;
    "monitoring": boolean;
    "currentMap": string;
    "raidActive": boolean;
    "raidStartedAt": string;
    "runThroughAt": string;
    "lastQueueSeconds": number;
    "lastScreenshot": string;
    "screenshotType": string;
    "position"?: Position | null;
    "lastError": string;
    "detectionScore": number;
    "detectionLayout": string;
    "analysisStage": string;
    "ocrRaw": string;
    "lastQuest": string;
    "questId": string;
    "questTrader": string;
    "questMap": string;
    "matchConfidence": number;
    "questCandidates": QuestCandidate[];
    "cropPreview": string;
    "questUrl": string;
    "questWikiUrl": string;
    "questObjectives": QuestObjective[];
    "lastItem": string;
    "itemId": string;
    "itemShortName": string;
    "itemUrl": string;
    "itemIconUrl": string;
    "itemConfidence": number;
    "itemCandidates": ItemCandidate[];
    "lastRemoteCommand": string;
    "tracker": TrackerStatus;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("hideout" in $$source)) {
            this["hideout"] = (new HideoutStatus());
        }
        if (!("catalog" in $$source)) {
            this["catalog"] = (new CatalogStatus());
        }
        if (!("connection" in $$source)) {
            this["connection"] = "";
        }
        if (!("monitoring" in $$source)) {
            this["monitoring"] = false;
        }
        if (!("currentMap" in $$source)) {
            this["currentMap"] = "";
        }
        if (!("raidActive" in $$source)) {
            this["raidActive"] = false;
        }
        if (!("raidStartedAt" in $$source)) {
            this["raidStartedAt"] = "";
        }
        if (!("runThroughAt" in $$source)) {
            this["runThroughAt"] = "";
        }
        if (!("lastQueueSeconds" in $$source)) {
            this["lastQueueSeconds"] = 0;
        }
        if (!("lastScreenshot" in $$source)) {
            this["lastScreenshot"] = "";
        }
        if (!("screenshotType" in $$source)) {
            this["screenshotType"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("detectionScore" in $$source)) {
            this["detectionScore"] = 0;
        }
        if (!("detectionLayout" in $$source)) {
            this["detectionLayout"] = "";
        }
        if (!("analysisStage" in $$source)) {
            this["analysisStage"] = "";
        }
        if (!("ocrRaw" in $$source)) {
            this["ocrRaw"] = "";
        }
        if (!("lastQuest" in $$source)) {
            this["lastQuest"] = "";
        }
        if (!("questId" in $$source)) {
            this["questId"] = "";
        }
        if (!("questTrader" in $$source)) {
            this["questTrader"] = "";
        }
        if (!("questMap" in $$source)) {
            this["questMap"] = "";
        }
        if (!("matchConfidence" in $$source)) {
            this["matchConfidence"] = 0;
        }
        if (!("questCandidates" in $$source)) {
            this["questCandidates"] = [];
        }
        if (!("cropPreview" in $$source)) {
            this["cropPreview"] = "";
        }
        if (!("questUrl" in $$source)) {
            this["questUrl"] = "";
        }
        if (!("questWikiUrl" in $$source)) {
            this["questWikiUrl"] = "";
        }
        if (!("questObjectives" in $$source)) {
            this["questObjectives"] = [];
        }
        if (!("lastItem" in $$source)) {
            this["lastItem"] = "";
        }
        if (!("itemId" in $$source)) {
            this["itemId"] = "";
        }
        if (!("itemShortName" in $$source)) {
            this["itemShortName"] = "";
        }
        if (!("itemUrl" in $$source)) {
            this["itemUrl"] = "";
        }
        if (!("itemIconUrl" in $$source)) {
            this["itemIconUrl"] = "";
        }
        if (!("itemConfidence" in $$source)) {
            this["itemConfidence"] = 0;
        }
        if (!("itemCandidates" in $$source)) {
            this["itemCandidates"] = [];
        }
        if (!("lastRemoteCommand" in $$source)) {
            this["lastRemoteCommand"] = "";
        }
        if (!("tracker" in $$source)) {
            this["tracker"] = (new TrackerStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType10;
        const $$createField11_0 = $$createType12;
        const $$createField22_0 = $$createType14;
        const $$createField26_0 = $$createType16;
        const $$createField33_0 = $$createType18;
        const $$createField35_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hideout" in $$parsedSource) {
            $$parsedSource["hideout"] = $$createField0_0($$parsedSource["hideout"]);
        }
        if ("catalog" in $$parsedSource) {
            $$parsedSource["catalog"] = $$createField1_0($$parsedSource["catalog"]);
        }
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField11_0($$parsedSource["position"]);
        }
        if ("questCandidates" in $$parsedSource) {
            $$parsedSource["questCandidates"] = $$createField22_0($$parsedSource["questCandidates"]);
        }
        if ("questObjectives" in $$parsedSource) {
            $$parsedSource["questObjectives"] = $$createField26_0($$parsedSource["questObjectives"]);
        }
        if ("itemCandidates" in $$parsedSource) {
            $$parsedSource["itemCandidates"] = $$createField33_0($$parsedSource["itemCandidates"]);
        }
        if ("tracker" in $$parsedSource) {
            $$parsedSource["tracker"] = $$createField35_0($$parsedSource["tracker"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

export class TrackerKeySummary {
    "id": string;
    "name": string;
    "mode": string;
    "maskedToken": string;
    "accountId": string;
    "profileId": string;
    "bound": boolean;

    /** Creates a new TrackerKeySummary instance. */
    constructor($$source: Partial<TrackerKeySummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("maskedToken" in $$source)) {
            this["maskedToken"] = "";
        }
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("bound" in $$source)) {
            this["bound"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackerKeySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackerKeySummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackerKeySummary($$parsedSource as Partial<TrackerKeySummary>);
    }
}

export class TrackerProfileSummary {
    "accountId": string;
    "profileId": string;
    "mode": string;
    "firstSeen": string;
    "lastSeen": string;
    "boundKeyId": string;
    "current": boolean;

    /** Creates a new TrackerProfileSummary instance. */
    constructor($$source: Partial<TrackerProfileSummary> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("firstSeen" in $$source)) {
            this["firstSeen"] = "";
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "";
        }
        if (!("boundKeyId" in $$source)) {
            this["boundKeyId"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackerProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackerProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackerProfileSummary($$parsedSource as Partial<TrackerProfileSummary>);
    }
}

export class TrackerStatus {
    "connection": string;
    "mode": string;
    "profileId": string;
    "accountId": string;
    "displayName": string;
    "playerLevel": number;
    "completedTasks": number;
    "failedTasks": number;
    "pvpConfigured": boolean;
    "pveConfigured": boolean;
    "seasonalConfigured": boolean;
    "lastSync": string;
    "lastEvent": string;
    "lastError": string;
    "keys": TrackerKeySummary[];
    "profiles": TrackerProfileSummary[];

    /** Creates a new TrackerStatus instance. */
    constructor($$source: Partial<TrackerStatus> = {}) {
        if (!("connection" in $$source)) {
            this["connection"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("playerLevel" in $$source)) {
            this["playerLevel"] = 0;
        }
        if (!("completedTasks" in $$source)) {
            this["completedTasks"] = 0;
        }
        if (!("failedTasks" in $$source)) {
            this["failedTasks"] = 0;
        }
        if (!("pvpConfigured" in $$source)) {
            this["pvpConfigured"] = false;
        }
        if (!("pveConfigured" in $$source)) {
            this["pveConfigured"] = false;
        }
        if (!("seasonalConfigured" in $$source)) {
            this["seasonalConfigured"] = false;
        }
        if (!("lastSync" in $$source)) {
            this["lastSync"] = "";
        }
        if (!("lastEvent" in $$source)) {
            this["lastEvent"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("keys" in $$source)) {
            this["keys"] = [];
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackerStatus {
        const $$createField14_0 = $$createType21;
        const $$createField15_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField14_0($$parsedSource["keys"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField15_0($$parsedSource["profiles"]);
        }
        return new TrackerStatus($$parsedSource as Partial<TrackerStatus>);
    }
}

/**
 * UpdateStatus is the state of the check for a newer MAYAK on GitHub
 * Releases (internal/app/app_update.go). State is idle, checking, current,
 * available, downloading (Progress in percent), ready (downloaded, installed
 * on quit or restart), unsupported (no build for Platform) or error.
 */
export class UpdateStatus {
    "current": string;
    "latest": string;
    "state": string;
    "progress": number;
    "platform": string;
    "releaseUrl": string;
    "releaseName": string;
    "notes": string;
    "publishedAt": string;
    "checkedAt": string;
    "lastError": string;

    /** Creates a new UpdateStatus instance. */
    constructor($$source: Partial<UpdateStatus> = {}) {
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("releaseName" in $$source)) {
            this["releaseName"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateStatus($$parsedSource as Partial<UpdateStatus>);
    }
}

// Private type creation functions
const $$createType0 = catalog$0.HideoutLevel.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = HideoutStationProgress.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = hideoutlog$0.Event.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = HideoutStatus.createFrom;
const $$createType10 = CatalogStatus.createFrom;
const $$createType11 = Position.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = QuestCandidate.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = QuestObjective.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = ItemCandidate.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = TrackerStatus.createFrom;
const $$createType20 = TrackerKeySummary.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = TrackerProfileSummary.createFrom;
const $$createType23 = $Create.Array($$createType22);
