// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bossinfo$0 from "../bossinfo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as browserview$0 from "../browserview/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eftdetect$0 from "../eftdetect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as iteminfo$0 from "../iteminfo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AnalyzeLatestScreenshot(): $CancellablePromise<void> {
    return $Call.ByID(3174466197);
}

export function AutoDetectEFTDirectories(): $CancellablePromise<eftdetect$0.Result> {
    return $Call.ByID(3503443286).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AutoDetectRemoteID(): $CancellablePromise<string> {
    return $Call.ByID(433838117);
}

/**
 * BrowserBosses returns the bosses of each map and the latest Goons reports
 * for the sidebar's boss section, in the game mode being played (mode "") or
 * the one given, with names in lang.
 */
export function BrowserBosses(mode: string, lang: string): $CancellablePromise<bossinfo$0.Info> {
    return $Call.ByID(2944774439, mode, lang).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BrowserFavicon returns the icon at rawURL as a data URL, from the cache
 * unless refresh asks for a current copy.
 */
export function BrowserFavicon(rawURL: string, refresh: boolean): $CancellablePromise<string> {
    return $Call.ByID(4248976838, rawURL, refresh);
}

/**
 * BrowserGoonReportInfo returns what a Goons report can be about: the raid in
 * progress or the last one, and the accounts and modes seen in the logs.
 */
export function BrowserGoonReportInfo(): $CancellablePromise<$models.GoonReportInfo> {
    return $Call.ByID(682966287).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * BrowserItemHistory returns the item's flea market price history for the
 * item sidebar's chart.
 */
export function BrowserItemHistory(mode: string, id: string): $CancellablePromise<iteminfo$0.PricePoint[]> {
    return $Call.ByID(3180075751, mode, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * BrowserItemInfo returns current details of an item for the item sidebar's
 * refresh button.
 */
export function BrowserItemInfo(mode: string, id: string): $CancellablePromise<iteminfo$0.Info> {
    return $Call.ByID(3325237645, mode, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * BrowserItemSearch finds catalog items by name or short name, so items can
 * be looked up without a screenshot.
 */
export function BrowserItemSearch(query: string): $CancellablePromise<$models.ItemSearchHit[]> {
    return $Call.ByID(3753157553, query).then(($result: any) => {
        return $$createType7($result);
    });
}

export function BrowserLoad(): $CancellablePromise<string> {
    return $Call.ByID(3043990910);
}

export function BrowserPlatform(): $CancellablePromise<string> {
    return $Call.ByID(3877969133);
}

/**
 * BrowserPopupClose closes the popup.
 */
export function BrowserPopupClose(): $CancellablePromise<void> {
    return $Call.ByID(3010978540);
}

/**
 * BrowserPopupPin pins the popup, so it stays when it loses the focus, or
 * unpins it.
 */
export function BrowserPopupPin(pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(1217014263, pinned);
}

/**
 * BrowserPopupShow opens page in the popup. An open popup stays where it is;
 * a new one opens where the last one was left, or else at place.
 */
export function BrowserPopupShow(page: $models.PopupPage, place: $models.PopupPlace): $CancellablePromise<void> {
    return $Call.ByID(3745698833, page, place);
}

/**
 * BrowserRemoteID lets the browser shell open its fixed map view with
 * ?connection=<ID> directly, instead of waiting for the document script.
 */
export function BrowserRemoteID(): $CancellablePromise<string> {
    return $Call.ByID(625165601);
}

/**
 * BrowserReportGoons submits a Goons sighting to tarkov.dev, for an account and
 * mode seen in the logs, on a map the Goons spawn on, once per raid.
 */
export function BrowserReportGoons(r: $models.GoonReport): $CancellablePromise<void> {
    return $Call.ByID(2284664064, r);
}

/**
 * Browser state contains only UI preferences, bookmarks and tabs. Tokens and
 * temporary WebRTC descriptions are never stored in this file.
 */
export function BrowserSave(raw: string): $CancellablePromise<void> {
    return $Call.ByID(1115281819, raw);
}

/**
 * BrowserScreenshotImage returns a screenshot as a JPEG data URL: a thumbnail
 * when thumbnail is set, else at full size.
 */
export function BrowserScreenshotImage(name: string, thumbnail: boolean): $CancellablePromise<string> {
    return $Call.ByID(3411663, name, thumbnail);
}

/**
 * BrowserScreenshots lists the screenshot folder's screenshots, newest first,
 * at most limit of them.
 */
export function BrowserScreenshots(limit: number): $CancellablePromise<$models.ScreenshotEntry[]> {
    return $Call.ByID(356321515, limit).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * BrowserSetAdblock applies the browser shell's ad blocking setting. Open
 * pages keep their current content until they are reloaded.
 */
export function BrowserSetAdblock(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1219344332, enabled);
}

export function BrowserSetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(738006765, mode);
}

/**
 * BrowserSetWindowTheme colors the native title bar and border to match the
 * browser shell's theme. Colors are "#rrggbb"; dark selects light or dark
 * caption buttons. Platforms without a colorable title bar ignore it.
 */
export function BrowserSetWindowTheme(caption: string, text: string, border: string, dark: boolean): $CancellablePromise<void> {
    return $Call.ByID(1857866107, caption, text, border, dark);
}

export function BrowserView(command: string, v: browserview$0.Options): $CancellablePromise<void> {
    return $Call.ByID(2681710815, command, v);
}

/**
 * CheckForUpdates asks GitHub for the latest release now. With autoUpdate
 * on, a newer release starts downloading.
 */
export function CheckForUpdates(): $CancellablePromise<model$0.UpdateStatus> {
    return $Call.ByID(3891257649).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ChooseLogsDirectory(): $CancellablePromise<string> {
    return $Call.ByID(4164457643);
}

export function ChooseScreenshotDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1391905886);
}

export function ChooseSoundFile(): $CancellablePromise<string> {
    return $Call.ByID(2799588716);
}

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(2638454672);
}

export function DiscoverTrackerProfiles(): $CancellablePromise<void> {
    return $Call.ByID(4170460093);
}

/**
 * DownloadUpdate downloads the release the last check found.
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1204715875);
}

/**
 * GameLanguages are the game languages MAYAK reads (settings' choices):
 * English and those in internal/locale.
 */
export function GameLanguages(): $CancellablePromise<string[]> {
    return $Call.ByID(241665187).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetLogs(): $CancellablePromise<model$0.LogEntry[]> {
    return $Call.ByID(3489936509).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(1576393379).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetStatus(): $CancellablePromise<model$0.Status> {
    return $Call.ByID(1528916376).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetTrackerHistoryBreakpoints(accountID: string, profileID: string, mode: string): $CancellablePromise<model$0.TrackerHistoryBreakpoint[]> {
    return $Call.ByID(547782838, accountID, profileID, mode).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetUpdateStatus returns the update's state for the settings page.
 */
export function GetUpdateStatus(): $CancellablePromise<model$0.UpdateStatus> {
    return $Call.ByID(2737290697).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetVersion is the running build's version, empty in development.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(3467524218);
}

export function ImportTrackerToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(3326162070, token);
}

/**
 * InstallUpdate puts the downloaded release in place and restarts into it.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(598684024);
}

export function OpenDebugDirectory(): $CancellablePromise<void> {
    return $Call.ByID(3117568264);
}

export function OpenHideoutDiagnostics(): $CancellablePromise<void> {
    return $Call.ByID(2653085358);
}

export function OpenLogsDirectory(): $CancellablePromise<void> {
    return $Call.ByID(488187932);
}

export function OpenQuestPage(): $CancellablePromise<void> {
    return $Call.ByID(3261994119);
}

export function OpenScreenshotDirectory(): $CancellablePromise<void> {
    return $Call.ByID(420978845);
}

/**
 * PersistSettings stores edits immediately without restarting active services.
 * Explicit SaveSettings still applies folder changes to a running monitor.
 */
export function PersistSettings(s: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(914542567, s);
}

export function PreviewSound(kind: string, path: string, volume: number): $CancellablePromise<void> {
    return $Call.ByID(2022189061, kind, path, volume);
}

export function RefreshCatalog(): $CancellablePromise<void> {
    return $Call.ByID(1073188156);
}

export function RefreshHideout(): $CancellablePromise<void> {
    return $Call.ByID(2634111235);
}

export function RefreshTracker(): $CancellablePromise<void> {
    return $Call.ByID(830301695);
}

/**
 * RefreshTrackerKeyNames reads metadata for all saved keys, including unassigned keys.
 */
export function RefreshTrackerKeyNames(): $CancellablePromise<void> {
    return $Call.ByID(3514687458);
}

export function RemoveTrackerKey(keyID: string): $CancellablePromise<void> {
    return $Call.ByID(1661829381, keyID);
}

export function SaveSettings(s: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(3616322938, s);
}

export function SetTrackerProfileKey(accountID: string, profileID: string, mode: string, keyID: string): $CancellablePromise<void> {
    return $Call.ByID(3013609958, accountID, profileID, mode, keyID);
}

export function StartMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(2732801236);
}

export function StopMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(1383325780);
}

export function SyncTrackerHistory(accountID: string, profileID: string, mode: string, breakpointID: string): $CancellablePromise<void> {
    return $Call.ByID(2148743105, accountID, profileID, mode, breakpointID);
}

export function TestRemote(): $CancellablePromise<void> {
    return $Call.ByID(528960240);
}

// Private type creation functions
const $$createType0 = eftdetect$0.Result.createFrom;
const $$createType1 = bossinfo$0.Info.createFrom;
const $$createType2 = $models.GoonReportInfo.createFrom;
const $$createType3 = iteminfo$0.PricePoint.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = iteminfo$0.Info.createFrom;
const $$createType6 = $models.ItemSearchHit.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.ScreenshotEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = model$0.UpdateStatus.createFrom;
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = model$0.LogEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = config$0.Settings.createFrom;
const $$createType15 = model$0.Status.createFrom;
const $$createType16 = model$0.TrackerHistoryBreakpoint.createFrom;
const $$createType17 = $Create.Array($$createType16);
