// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bossinfo$0 from "../bossinfo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as browserview$0 from "../browserview/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eftdetect$0 from "../eftdetect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as iteminfo$0 from "../iteminfo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mapdata$0 from "../mapdata/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as snapnote$0 from "../snapnote/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sound$0 from "../sound/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as squad$0 from "../squad/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AnalyzeLatestScreenshot(): $CancellablePromise<void> {
    return $Call.ByID(3174466197);
}

export function AutoDetectEFTDirectories(): $CancellablePromise<eftdetect$0.Result> {
    return $Call.ByID(3503443286).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AutoDetectRemoteID(): $CancellablePromise<string> {
    return $Call.ByID(433838117);
}

/**
 * BrowserBosses returns the bosses of each map and the latest Goons reports
 * for the sidebar's boss section, in the game mode being played (mode "") or
 * the one given, with names in lang.
 */
export function BrowserBosses(mode: string, lang: string): $CancellablePromise<bossinfo$0.Info> {
    return $Call.ByID(2944774439, mode, lang).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BrowserFavicon returns the icon at rawURL as a data URL, from the cache
 * unless refresh asks for a current copy.
 */
export function BrowserFavicon(rawURL: string, refresh: boolean): $CancellablePromise<string> {
    return $Call.ByID(4248976838, rawURL, refresh);
}

/**
 * BrowserGoonReportInfo returns what a Goons report can be about: the raid in
 * progress or the last one, and the accounts and modes seen in the logs.
 */
export function BrowserGoonReportInfo(): $CancellablePromise<$models.GoonReportInfo> {
    return $Call.ByID(682966287).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * BrowserItemHistory returns the item's flea market price history for the
 * item sidebar's chart.
 */
export function BrowserItemHistory(mode: string, id: string): $CancellablePromise<iteminfo$0.PricePoint[]> {
    return $Call.ByID(3180075751, mode, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * BrowserItemInfo returns current details of an item for the item sidebar's
 * refresh button.
 */
export function BrowserItemInfo(mode: string, id: string): $CancellablePromise<iteminfo$0.Info> {
    return $Call.ByID(3325237645, mode, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * BrowserItemSearch finds catalog items by name or short name, so items can
 * be looked up without a screenshot.
 */
export function BrowserItemSearch(query: string): $CancellablePromise<$models.ItemSearchHit[]> {
    return $Call.ByID(3753157553, query).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * BrowserLinkRelay is where a Host and its Client meet (the shell's
 * transport.js); MAYAK_LINK_RELAY points a development build at another one
 * (`task relay:dev`: ws://127.0.0.1:8787/link/).
 */
export function BrowserLinkRelay(): $CancellablePromise<string> {
    return $Call.ByID(2579711407);
}

export function BrowserLoad(): $CancellablePromise<string> {
    return $Call.ByID(3043990910);
}

/**
 * BrowserMapMarkers returns what the map view can show on map (a key or an
 * alias), the way tarkov.dev's map shows it: extracts, spawns, loot, task
 * objectives… from the tarkov.dev catalog of the game mode played, with
 * item and task names in language ("ja" or "en"). With TarkovTracker
 * connected, a task done or failed is marked inactive.
 * 
 * mode is the catalog's game mode ("regular", "pve", "pvp-season"), or ""
 * for the one played (the Host's setting, or what TarkovTracker and the
 * logs tell; PvP when unknown); the markers say which it was.
 */
export function BrowserMapMarkers(name: string, language: string, mode: string): $CancellablePromise<mapdata$0.MapMarkers> {
    return $Call.ByID(1249944371, name, language, mode).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * BrowserMapTile returns a tile of a map drawn from tiles (on
 * assets.tarkov.dev) as a data URL, for the map view's picture made into a
 * snap note.
 */
export function BrowserMapTile(url: string): $CancellablePromise<string> {
    return $Call.ByID(910685324, url);
}

/**
 * BrowserMenuChoose closes the menu with a choice ("" for none).
 */
export function BrowserMenuChoose(id: string): $CancellablePromise<void> {
    return $Call.ByID(2938484100, id);
}

/**
 * BrowserMenuCurrent is the menu shown now, for the menu page to draw when it
 * has just loaded; none when no menu is open.
 */
export function BrowserMenuCurrent(): $CancellablePromise<$models.MenuRequest | null> {
    return $Call.ByID(1280066958).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * BrowserMenuReady shows the menu at the height its page drew it.
 */
export function BrowserMenuReady(height: number): $CancellablePromise<void> {
    return $Call.ByID(2663145016, height);
}

/**
 * BrowserMenuShow opens a menu. It shows once the menu page has drawn it
 * (BrowserMenuReady), so it never flashes at a wrong size.
 */
export function BrowserMenuShow(request: $models.MenuRequest): $CancellablePromise<void> {
    return $Call.ByID(2591647512, request);
}

export function BrowserPlatform(): $CancellablePromise<string> {
    return $Call.ByID(3877969133);
}

/**
 * BrowserPopupClose closes the popup.
 */
export function BrowserPopupClose(): $CancellablePromise<void> {
    return $Call.ByID(3010978540);
}

/**
 * BrowserPopupPin pins the popup, so it stays when it loses the focus, or
 * unpins it.
 */
export function BrowserPopupPin(pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(1217014263, pinned);
}

/**
 * BrowserPopupShow opens page in the popup. An open popup stays where it is;
 * a new one opens where the last one was left, or else at place.
 */
export function BrowserPopupShow(page: $models.PopupPage, place: $models.PopupPlace): $CancellablePromise<void> {
    return $Call.ByID(3745698833, page, place);
}

/**
 * BrowserRemoteID lets the browser shell open its fixed map view with
 * ?connection=<ID> directly, instead of waiting for the document script.
 */
export function BrowserRemoteID(): $CancellablePromise<string> {
    return $Call.ByID(625165601);
}

/**
 * BrowserReportGoons submits a Goons sighting to tarkov.dev, for an account and
 * mode seen in the logs, on a map the Goons spawn on, once per raid.
 */
export function BrowserReportGoons(r: $models.GoonReport): $CancellablePromise<void> {
    return $Call.ByID(2284664064, r);
}

/**
 * BrowserSave keeps the shell's state: UI preferences, bookmarks and tabs.
 * Tokens are never stored in it; the pairing's key is (connection.link),
 * with the other device settings.
 */
export function BrowserSave(raw: string): $CancellablePromise<void> {
    return $Call.ByID(1115281819, raw);
}

/**
 * BrowserScreenshotImage returns a screenshot as a JPEG data URL: a thumbnail
 * when thumbnail is set, else at full size.
 */
export function BrowserScreenshotImage(name: string, thumbnail: boolean): $CancellablePromise<string> {
    return $Call.ByID(3411663, name, thumbnail);
}

/**
 * BrowserScreenshots lists the screenshot folder's screenshots, newest first,
 * at most limit of them.
 */
export function BrowserScreenshots(limit: number): $CancellablePromise<$models.ScreenshotEntry[]> {
    return $Call.ByID(356321515, limit).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * BrowserSetAdblock applies the browser shell's ad blocking setting. Open
 * pages keep their current content until they are reloaded.
 */
export function BrowserSetAdblock(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1219344332, enabled);
}

export function BrowserSetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(738006765, mode);
}

/**
 * BrowserSetWindowTheme colors the native title bar and border to match the
 * browser shell's theme. Colors are "#rrggbb"; dark selects light or dark
 * caption buttons. Platforms without a colorable title bar ignore it.
 */
export function BrowserSetWindowTheme(caption: string, text: string, border: string, dark: boolean): $CancellablePromise<void> {
    return $Call.ByID(1857866107, caption, text, border, dark);
}

/**
 * BrowserSquadMapImage returns the picture of map (a key or an alias) at a
 * floor (a layer's svgLayer, or "" for the ground level), the ground faded
 * to fade percent under a floor, as a data URL.
 */
export function BrowserSquadMapImage(name: string, layer: string, fade: number): $CancellablePromise<string> {
    return $Call.ByID(3491416803, name, layer, fade);
}

/**
 * BrowserSquadMaps returns the interactive maps' geometry for the squad map.
 */
export function BrowserSquadMaps(): $CancellablePromise<mapdata$0.Map[]> {
    return $Call.ByID(397465127).then(($result: any) => {
        return $$createType14($result);
    });
}

export function BrowserView(command: string, v: browserview$0.Options): $CancellablePromise<void> {
    return $Call.ByID(2681710815, command, v);
}

/**
 * CheckForUpdates asks GitHub for the latest release now. With autoUpdate
 * on, a newer release starts downloading.
 */
export function CheckForUpdates(): $CancellablePromise<model$0.UpdateStatus> {
    return $Call.ByID(3891257649).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ChooseLogsDirectory(): $CancellablePromise<string> {
    return $Call.ByID(4164457643);
}

export function ChooseScreenshotDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1391905886);
}

export function ChooseSoundFile(): $CancellablePromise<string> {
    return $Call.ByID(2799588716);
}

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(2638454672);
}

export function DiscoverTrackerProfiles(): $CancellablePromise<void> {
    return $Call.ByID(4170460093);
}

/**
 * DownloadUpdate downloads the release the last check found.
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1204715875);
}

/**
 * GameLanguages are the game languages MAYAK reads (settings' choices):
 * English and those in internal/locale.
 */
export function GameLanguages(): $CancellablePromise<string[]> {
    return $Call.ByID(241665187).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetLogs(): $CancellablePromise<model$0.LogEntry[]> {
    return $Call.ByID(3489936509).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(1576393379).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetStatus(): $CancellablePromise<model$0.Status> {
    return $Call.ByID(1528916376).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * GetUpdateStatus returns the update's state for the settings page.
 */
export function GetUpdateStatus(): $CancellablePromise<model$0.UpdateStatus> {
    return $Call.ByID(2737290697).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetVersion is the running build's version, empty in development.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(3467524218);
}

/**
 * ImportTrackerToken verifies a TarkovTracker token and stores it as a key.
 * The key goes straight onto the EFT profile it is for when that is plain:
 * the one profile of its mode without a key, or the profile being played.
 * It returns that profile's description, or "" when the key waits to be
 * assigned by hand.
 */
export function ImportTrackerToken(token: string): $CancellablePromise<string> {
    return $Call.ByID(3326162070, token);
}

/**
 * InstallUpdate puts the downloaded release in place and restarts into it.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(598684024);
}

/**
 * MapDrawingLoad returns the lines kept, as a JSON array ("[]" for none).
 */
export function MapDrawingLoad(): $CancellablePromise<string> {
    return $Call.ByID(3673321122);
}

/**
 * MapDrawingSave keeps the lines given, all of them (a JSON array of
 * objects with an id): a line no longer given becomes a tombstone.
 */
export function MapDrawingSave(raw: string): $CancellablePromise<void> {
    return $Call.ByID(3121519351, raw);
}

export function OpenDebugDirectory(): $CancellablePromise<void> {
    return $Call.ByID(3117568264);
}

export function OpenHideoutDiagnostics(): $CancellablePromise<void> {
    return $Call.ByID(2653085358);
}

export function OpenLogsDirectory(): $CancellablePromise<void> {
    return $Call.ByID(488187932);
}

export function OpenQuestPage(): $CancellablePromise<void> {
    return $Call.ByID(3261994119);
}

export function OpenScreenshotDirectory(): $CancellablePromise<void> {
    return $Call.ByID(420978845);
}

/**
 * OpenThirdPartyNotices opens THIRD_PARTY_NOTICES.txt, which the build puts
 * beside Mayak.exe (tools/notices); a development build has none.
 */
export function OpenThirdPartyNotices(): $CancellablePromise<void> {
    return $Call.ByID(606796694);
}

/**
 * PersistSettings stores s and applies it as an edit is made in the settings
 * page, without restarting the monitor for a changed folder (SaveSettings
 * does that).
 */
export function PersistSettings(s: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(914542567, s);
}

/**
 * PlayerMarkerEffectColor is the colour effect shows in without a colour
 * chosen, for the settings' colour control.
 */
export function PlayerMarkerEffectColor(effect: string): $CancellablePromise<string> {
    return $Call.ByID(2215901919, effect);
}

/**
 * PlayerMarkerEffects lists the effects the settings offer.
 */
export function PlayerMarkerEffects(): $CancellablePromise<string[]> {
    return $Call.ByID(504171073).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * PlayerMarkerPreviewCSS is a style sheet for the settings page: each
 * effect's rules, in color (or its own), on
 * .marker-preview[data-effect=<effect>] .marker-icon (the box) and its img.
 */
export function PlayerMarkerPreviewCSS(color: string): $CancellablePromise<string> {
    return $Call.ByID(675497734, color);
}

/**
 * PreviewSound plays a notification as it would sound with a file ("" for
 * none) and a built-in voice ("" for the beeps).
 */
export function PreviewSound(kind: string, path: string, voice: string, volume: number): $CancellablePromise<void> {
    return $Call.ByID(2022189061, kind, path, voice, volume);
}

/**
 * QuestSiteURLs is a task's page on each task site, from the task list at
 * hand: a task tab kept from before keeps the pages it opened with, which a
 * newer list may know better (a trader read since, for the Japanese wiki).
 * Empty when the task is not in the list.
 */
export function QuestSiteURLs(id: string, name: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2662235009, id, name).then(($result: any) => {
        return $$createType21($result);
    });
}

export function RefreshCatalog(): $CancellablePromise<void> {
    return $Call.ByID(1073188156);
}

export function RefreshHideout(): $CancellablePromise<void> {
    return $Call.ByID(2634111235);
}

export function RefreshTracker(): $CancellablePromise<void> {
    return $Call.ByID(830301695);
}

/**
 * RefreshTrackerKeyNames reads metadata for all saved keys, including unassigned keys.
 */
export function RefreshTrackerKeyNames(): $CancellablePromise<void> {
    return $Call.ByID(3514687458);
}

export function RemoveTrackerKey(keyID: string): $CancellablePromise<void> {
    return $Call.ByID(1661829381, keyID);
}

/**
 * SaveSettings stores s and applies it, folders included: a running monitor
 * moves to changed folders. It is the settings page's explicit save.
 */
export function SaveSettings(s: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(3616322938, s);
}

export function SetTrackerProfileKey(accountID: string, profileID: string, mode: string, keyID: string): $CancellablePromise<void> {
    return $Call.ByID(3013609958, accountID, profileID, mode, keyID);
}

/**
 * SnapNoteCapture captures the page in tab viewID (what is on screen, or with
 * full the whole page) as a new note linked to that page. translated says
 * the page shows through Google Translate, whose bar is hidden for it.
 */
export function SnapNoteCapture(viewID: string, pageURL: string, pageTitle: string, full: boolean, translated: boolean): $CancellablePromise<snapnote$0.Note> {
    return $Call.ByID(2024184632, viewID, pageURL, pageTitle, full, translated).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * SnapNoteCopyImage puts a note's picture (a PNG data URL: the image with
 * its drawing, as the shell shows it) on the clipboard.
 */
export function SnapNoteCopyImage(pngDataURL: string): $CancellablePromise<void> {
    return $Call.ByID(2394800284, pngDataURL);
}

/**
 * SnapNoteCreate starts a note on its own (not linked to a page) from an
 * image data URL: a pasted picture, an image file or a blank sheet.
 */
export function SnapNoteCreate(imageDataURL: string, title: string): $CancellablePromise<snapnote$0.Note> {
    return $Call.ByID(173459086, imageDataURL, title).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * SnapNoteDelete removes a note.
 */
export function SnapNoteDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2432754661, id);
}

/**
 * SnapNoteExport saves a note's picture (a PNG data URL) where the user
 * chooses, under name. It returns the path, or "" when the dialog was
 * cancelled.
 */
export function SnapNoteExport(pngDataURL: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(527011928, pngDataURL, name);
}

/**
 * SnapNoteFavorite stars a note, or takes its star off.
 */
export function SnapNoteFavorite(id: string, favorite: boolean): $CancellablePromise<snapnote$0.Note> {
    return $Call.ByID(3862972790, id, favorite).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * SnapNoteFromScreenshot starts a note on its own (not linked to a page)
 * from a game screenshot in the Screenshots folder, named as the gallery
 * lists it.
 */
export function SnapNoteFromScreenshot(name: string, title: string): $CancellablePromise<snapnote$0.Note> {
    return $Call.ByID(3622921050, name, title).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * SnapNoteLink links a note to the page it was taken from, or unlinks it.
 */
export function SnapNoteLink(id: string, linked: boolean): $CancellablePromise<snapnote$0.Note> {
    return $Call.ByID(2416529170, id, linked).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * SnapNoteList returns every note (without strokes), the latest changed first.
 */
export function SnapNoteList(): $CancellablePromise<snapnote$0.Note[]> {
    return $Call.ByID(2495635670).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * SnapNoteOpen returns a note with its strokes and image.
 */
export function SnapNoteOpen(id: string): $CancellablePromise<$models.SnapNoteData> {
    return $Call.ByID(625471842, id).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * SnapNoteSave stores a note's title, drawing (JSON) and thumbnail (a JPEG
 * data URL; empty keeps the one it has).
 */
export function SnapNoteSave(id: string, title: string, strokes: string, thumbDataURL: string): $CancellablePromise<snapnote$0.Note> {
    return $Call.ByID(4245433319, id, title, strokes, thumbDataURL).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * SnapNoteSetMap sets the map of a note's position.
 */
export function SnapNoteSetMap(id: string, mapName: string): $CancellablePromise<snapnote$0.Note> {
    return $Call.ByID(683081412, id, mapName).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * SnapNoteShowSpot shows a note's position on the tarkov.dev map: the
 * built-in browser brings its map forward, and the position (with the map)
 * goes to the maps connected by Remote Control, as a screenshot's would.
 */
export function SnapNoteShowSpot(id: string): $CancellablePromise<void> {
    return $Call.ByID(3347874839, id);
}

/**
 * SnapNoteThumb returns a note's thumbnail as a data URL, empty before one
 * was saved.
 */
export function SnapNoteThumb(id: string): $CancellablePromise<string> {
    return $Call.ByID(1299541354, id);
}

/**
 * SquadAvailable reports whether this build offers squads.
 */
export function SquadAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(2161399151);
}

/**
 * SquadJoin joins the squad of code as name, leaving the one joined before.
 * It returns the code in its canonical form ("ABCD-1234").
 */
export function SquadJoin(code: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(4115320172, code, name);
}

/**
 * SquadLeave leaves the squad.
 */
export function SquadLeave(): $CancellablePromise<void> {
    return $Call.ByID(1676689683);
}

/**
 * SquadNewCode returns a fresh squad code ("ABCD-1234") to create a squad
 * with.
 */
export function SquadNewCode(): $CancellablePromise<string> {
    return $Call.ByID(3692172135);
}

/**
 * SquadRename changes the name this PC shows in its squad.
 */
export function SquadRename(name: string): $CancellablePromise<void> {
    return $Call.ByID(2878794830, name);
}

/**
 * SquadSetColor sets the squad colour this PC's reports carry ("#rrggbb", or
 * empty to take one the others give), and tells the squad joined.
 */
export function SquadSetColor(color: string): $CancellablePromise<void> {
    return $Call.ByID(2482357739, color);
}

/**
 * SquadState returns the squad joined, or nil.
 */
export function SquadState(): $CancellablePromise<squad$0.State | null> {
    return $Call.ByID(2725117137).then(($result: any) => {
        return $$createType26($result);
    });
}

export function StartMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(2732801236);
}

export function StopMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(1383325780);
}

export function SyncTrackerProfileHistory(accountID: string, profileID: string, mode: string): $CancellablePromise<number> {
    return $Call.ByID(1759201672, accountID, profileID, mode);
}

/**
 * SystemFonts lists the font families installed, for the snap notes' text.
 */
export function SystemFonts(): $CancellablePromise<string[]> {
    return $Call.ByID(2671723451).then(($result: any) => {
        return $$createType16($result);
    });
}

export function TestRemote(): $CancellablePromise<void> {
    return $Call.ByID(528960240);
}

/**
 * VoicePacks lists the built-in voices the notifications can speak with.
 */
export function VoicePacks(): $CancellablePromise<sound$0.VoicePack[]> {
    return $Call.ByID(2023705626).then(($result: any) => {
        return $$createType28($result);
    });
}

// Private type creation functions
const $$createType0 = eftdetect$0.Result.createFrom;
const $$createType1 = bossinfo$0.Info.createFrom;
const $$createType2 = $models.GoonReportInfo.createFrom;
const $$createType3 = iteminfo$0.PricePoint.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = iteminfo$0.Info.createFrom;
const $$createType6 = $models.ItemSearchHit.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = mapdata$0.MapMarkers.createFrom;
const $$createType9 = $models.MenuRequest.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.ScreenshotEntry.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = mapdata$0.Map.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = model$0.UpdateStatus.createFrom;
const $$createType16 = $Create.Array($Create.Any);
const $$createType17 = model$0.LogEntry.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = config$0.Settings.createFrom;
const $$createType20 = model$0.Status.createFrom;
const $$createType21 = $Create.Map($Create.Any, $Create.Any);
const $$createType22 = snapnote$0.Note.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $models.SnapNoteData.createFrom;
const $$createType25 = squad$0.State.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = sound$0.VoicePack.createFrom;
const $$createType28 = $Create.Array($$createType27);
