// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as screenshotstore$0 from "../screenshotstore/models.js";

/**
 * GoonIdentity is an account and game mode seen in the EFT logs.
 */
export class GoonIdentity {
    "accountId": string;
    "profileId": string;

    /**
     * pvp or pve
     */
    "mode": string;
    "lastSeen": string;
    "current": boolean;

    /** Creates a new GoonIdentity instance. */
    constructor($$source: Partial<GoonIdentity> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoonIdentity instance from a string or object.
     */
    static createFrom($$source: any = {}): GoonIdentity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoonIdentity($$parsedSource as Partial<GoonIdentity>);
    }
}

/**
 * GoonRaid is a raid a report can be for.
 */
export class GoonRaid {
    "map": string;
    "startedAt": string;
    "mode": string;
    "accountId": string;
    "profileId": string;
    "active": boolean;
    "reported": boolean;

    /** Creates a new GoonRaid instance. */
    constructor($$source: Partial<GoonRaid> = {}) {
        if (!("map" in $$source)) {
            this["map"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("reported" in $$source)) {
            this["reported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoonRaid instance from a string or object.
     */
    static createFrom($$source: any = {}): GoonRaid {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoonRaid($$parsedSource as Partial<GoonRaid>);
    }
}

/**
 * GoonReport is what the user chose to report: the map (its normalized name),
 * the account and mode, and the raid start (RFC 3339; empty for now).
 */
export class GoonReport {
    "map": string;
    "accountId": string;
    "mode": string;
    "startedAt": string;

    /** Creates a new GoonReport instance. */
    constructor($$source: Partial<GoonReport> = {}) {
        if (!("map" in $$source)) {
            this["map"] = "";
        }
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoonReport instance from a string or object.
     */
    static createFrom($$source: any = {}): GoonReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoonReport($$parsedSource as Partial<GoonReport>);
    }
}

export class GoonReportInfo {
    "raid": GoonRaid | null;
    "identities": GoonIdentity[];

    /** Creates a new GoonReportInfo instance. */
    constructor($$source: Partial<GoonReportInfo> = {}) {
        if (!("raid" in $$source)) {
            this["raid"] = null;
        }
        if (!("identities" in $$source)) {
            this["identities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoonReportInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GoonReportInfo {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("raid" in $$parsedSource) {
            $$parsedSource["raid"] = $$createField0_0($$parsedSource["raid"]);
        }
        if ("identities" in $$parsedSource) {
            $$parsedSource["identities"] = $$createField1_0($$parsedSource["identities"]);
        }
        return new GoonReportInfo($$parsedSource as Partial<GoonReportInfo>);
    }
}

/**
 * ItemSearchHit is one match of the item sidebar's search box.
 */
export class ItemSearchHit {
    "id": string;
    "name": string;
    "shortName": string;

    /**
     * Names are the names in other languages, when they differ.
     */
    "names"?: { [_ in string]?: string };
    "iconUrl": string;

    /** Creates a new ItemSearchHit instance. */
    constructor($$source: Partial<ItemSearchHit> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("iconUrl" in $$source)) {
            this["iconUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemSearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemSearchHit {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField3_0($$parsedSource["names"]);
        }
        return new ItemSearchHit($$parsedSource as Partial<ItemSearchHit>);
    }
}

/**
 * PopupPage is what the popup shows.
 */
export class PopupPage {
    "url": string;
    "title": string;
    "task": boolean;
    "background": string;

    /**
     * Theme and Language style the popup's header like the shell.
     */
    "theme": string;
    "language": string;

    /**
     * Pinned is set by the Go side: whether the popup is pinned.
     */
    "pinned": boolean;

    /** Creates a new PopupPage instance. */
    constructor($$source: Partial<PopupPage> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("task" in $$source)) {
            this["task"] = false;
        }
        if (!("background" in $$source)) {
            this["background"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PopupPage instance from a string or object.
     */
    static createFrom($$source: any = {}): PopupPage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PopupPage($$parsedSource as Partial<PopupPage>);
    }
}

/**
 * PopupPlace is where the popup opens: x and y are relative to the main
 * window, in the shell's pixels.
 */
export class PopupPlace {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new PopupPlace instance. */
    constructor($$source: Partial<PopupPlace> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PopupPlace instance from a string or object.
     */
    static createFrom($$source: any = {}): PopupPlace {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PopupPlace($$parsedSource as Partial<PopupPlace>);
    }
}

/**
 * ScreenshotEntry is one screenshot in the screenshot folder.
 */
export class ScreenshotEntry {
    "name": string;

    /**
     * Time is when it was saved (RFC 3339).
     */
    "time": string;

    /**
     * Meta is what MAYAK recognized it as, if it analyzed it.
     */
    "meta"?: screenshotstore$0.Record | null;

    /** Creates a new ScreenshotEntry instance. */
    constructor($$source: Partial<ScreenshotEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenshotEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ScreenshotEntry {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField2_0($$parsedSource["meta"]);
        }
        return new ScreenshotEntry($$parsedSource as Partial<ScreenshotEntry>);
    }
}

// Private type creation functions
const $$createType0 = GoonRaid.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = GoonIdentity.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = screenshotstore$0.Record.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
