// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Event contains only allowlisted diagnostics. Never retain surrounding log text.
 */
export class Event {
    "accountId": string;
    "profileId": string;
    "mode": string;
    "hidden"?: boolean;
    "stationName": string;
    "kind": string;
    "action": string;
    "areaType": number;
    "actionTimestamp": number;
    "source": string;
    "occurredAt": string;
    "status": string;
    "confidence": string;
    "historical": boolean;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("stationName" in $$source)) {
            this["stationName"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("areaType" in $$source)) {
            this["areaType"] = 0;
        }
        if (!("actionTimestamp" in $$source)) {
            this["actionTimestamp"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("occurredAt" in $$source)) {
            this["occurredAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = "";
        }
        if (!("historical" in $$source)) {
            this["historical"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Event($$parsedSource as Partial<Event>);
    }
}
