// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Boss {
    "id": string;
    "name": string;
    "portrait": string;
    "chance": number;
    "locations": Location[];
    "escorts": Escort[];

    /** Creates a new Boss instance. */
    constructor($$source: Partial<Boss> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("portrait" in $$source)) {
            this["portrait"] = "";
        }
        if (!("chance" in $$source)) {
            this["chance"] = 0;
        }
        if (!("locations" in $$source)) {
            this["locations"] = [];
        }
        if (!("escorts" in $$source)) {
            this["escorts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Boss instance from a string or object.
     */
    static createFrom($$source: any = {}): Boss {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("locations" in $$parsedSource) {
            $$parsedSource["locations"] = $$createField4_0($$parsedSource["locations"]);
        }
        if ("escorts" in $$parsedSource) {
            $$parsedSource["escorts"] = $$createField5_0($$parsedSource["escorts"]);
        }
        return new Boss($$parsedSource as Partial<Boss>);
    }
}

/**
 * Escort is a follower with the counts it comes in, e.g. 0–3.
 */
export class Escort {
    "name": string;
    "min": number;
    "max": number;

    /** Creates a new Escort instance. */
    constructor($$source: Partial<Escort> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("min" in $$source)) {
            this["min"] = 0;
        }
        if (!("max" in $$source)) {
            this["max"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Escort instance from a string or object.
     */
    static createFrom($$source: any = {}): Escort {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Escort($$parsedSource as Partial<Escort>);
    }
}

/**
 * Goon is one player report of the Goons on a map.
 */
export class Goon {
    "mapKey": string;
    "map": string;
    "time": string;

    /** Creates a new Goon instance. */
    constructor($$source: Partial<Goon> = {}) {
        if (!("mapKey" in $$source)) {
            this["mapKey"] = "";
        }
        if (!("map" in $$source)) {
            this["map"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Goon instance from a string or object.
     */
    static createFrom($$source: any = {}): Goon {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Goon($$parsedSource as Partial<Goon>);
    }
}

export class Info {
    "mode": string;
    "fetched": string;
    "maps": Map[];
    "goons": Goon[];

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("fetched" in $$source)) {
            this["fetched"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("maps" in $$source)) {
            this["maps"] = [];
        }
        if (!("goons" in $$source)) {
            this["goons"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("maps" in $$parsedSource) {
            $$parsedSource["maps"] = $$createField2_0($$parsedSource["maps"]);
        }
        if ("goons" in $$parsedSource) {
            $$parsedSource["goons"] = $$createField3_0($$parsedSource["goons"]);
        }
        return new Info($$parsedSource as Partial<Info>);
    }
}

export class Location {
    "name": string;
    "chance": number;

    /** Creates a new Location instance. */
    constructor($$source: Partial<Location> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("chance" in $$source)) {
            this["chance"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Location instance from a string or object.
     */
    static createFrom($$source: any = {}): Location {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Location($$parsedSource as Partial<Location>);
    }
}

export class Map {
    "id": string;

    /**
     * normalized name, as the map detection reports it
     */
    "key": string;

    /**
     * the game's name, as Goons reports take it
     */
    "nameId": string;
    "name": string;
    "bosses": Boss[];

    /** Creates a new Map instance. */
    constructor($$source: Partial<Map> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("nameId" in $$source)) {
            this["nameId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("bosses" in $$source)) {
            this["bosses"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Map instance from a string or object.
     */
    static createFrom($$source: any = {}): Map {
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bosses" in $$parsedSource) {
            $$parsedSource["bosses"] = $$createField4_0($$parsedSource["bosses"]);
        }
        return new Map($$parsedSource as Partial<Map>);
    }
}

// Private type creation functions
const $$createType0 = Location.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Escort.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Map.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Goon.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Boss.createFrom;
const $$createType9 = $Create.Array($$createType8);
