// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RemoteTarget {
    "id": string;
    "name": string;
    "map": boolean;
    "tasks": boolean;

    /** Creates a new RemoteTarget instance. */
    constructor($$source: Partial<RemoteTarget> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("map" in $$source)) {
            this["map"] = false;
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteTarget($$parsedSource as Partial<RemoteTarget>);
    }
}

export class Settings {
    "gameLanguage": string;
    "questSite": string;
    "language": string;
    "screenshotDirectory": string;
    "logsDirectory": string;
    "remoteId": string;
    "remoteTargets": RemoteTarget[];
    "browserRemoteId": string;
    "map": string;
    "gameMode": string;
    "ocrEngine": string;
    "tesseractPath": string;

    /**
     * OCRDefaultRevision records one-time moves to a new default OCR engine.
     */
    "ocrDefaultRevision": number;
    "debug": boolean;
    "saveRecognitionDebug": boolean;
    "screenshotCleanup": boolean;
    "screenshotRetainCount": number;
    "screenshotRetainHours": number;
    "soundsEnabled": boolean;
    "questSoundEnabled": boolean;
    "questSoundPath": string;

    /**
     * ErrorSound is a screenshot that could not be read; it once also
     * covered a task matching nothing and a failed tarkov.dev connection,
     * which have their own now (settings saved before take its choice).
     */
    "errorSoundEnabled": boolean;
    "errorSoundPath": string;
    "taskNotMatchedSoundEnabled": boolean;
    "taskNotMatchedSoundPath": string;
    "remoteErrorSoundEnabled": boolean;
    "remoteErrorSoundPath": string;
    "itemSoundEnabled": boolean;
    "itemSoundPath": string;
    "itemNotMatchedSoundEnabled": boolean;
    "itemNotMatchedSoundPath": string;
    "soundVolume": number;

    /**
     * SoundVoice is the built-in voice the notifications speak with (a
     * pack of internal/sound/voices), "beep" for the built-in beeps, or
     * empty for the language's default (app_sound.go baseVoice).
     */
    "soundVoice": string;

    /**
     * SoundVoices is the voice a notification speaks with instead (its kind,
     * sound.Kind, to a pack or "beep"); one not in it takes SoundVoice.
     */
    "soundVoices": { [_ in string]?: string };

    /**
     * SoundVolumeOffsets turns a notification (its kind) up or down from
     * SoundVolume, in points (-50 to +50).
     */
    "soundVolumeOffsets": { [_ in string]?: number };
    "autoStartMonitoring": boolean;
    "openMapOnRaidStart": boolean;
    "navigateMapOnPositionScreenshot": boolean;

    /**
     * PlayerMarkerEffect is the effect the built-in browser gives the
     * player's position marker on tarkov.dev's map, PlayerMarkerColor its
     * colour (#rrggbb; empty for the effect's own); see app_marker.go.
     * PlayerMarker was 0.1.15's single choice; it is read once and dropped.
     */
    "playerMarkerEffect": string;
    "playerMarkerColor": string;
    "playerMarker"?: string;
    "tarkovTrackerEnabled": boolean;
    "matchFoundSoundEnabled": boolean;
    "matchFoundSoundPath": string;
    "raidStartSoundEnabled": boolean;
    "raidStartSoundPath": string;
    "runThroughSoundEnabled": boolean;
    "runThroughSoundPath": string;
    "runThroughSeconds": number;
    "questItemsSoundEnabled": boolean;
    "questItemsSoundPath": string;
    "restartTasksSoundEnabled": boolean;
    "restartTasksSoundPath": string;
    "startMinimized": boolean;

    /**
     * MinimizeToTray removes the taskbar entry when the window is minimized;
     * CloseToTray keeps the app running in the tray when it is closed.
     */
    "minimizeToTray": boolean;
    "closeToTray": boolean;

    /**
     * KeepPriority puts MAYAK and its window's WebView2 processes back to
     * normal priority when a priority manager (Process Lasso) lowered them
     * (priority_windows.go); off unless such a tool makes the window sluggish.
     */
    "keepPriority": boolean;
    "launchAtStartup": boolean;

    /**
     * AutoUpdate checks GitHub Releases for a newer MAYAK, downloads it in
     * the background and installs it when MAYAK quits.
     */
    "autoUpdate": boolean;

    /**
     * UpdateChannel is where updates come from: "stable" (tagged releases)
     * or "nightly" (also the nightly build, whichever is newer).
     */
    "updateChannel": string;
    "windowX": number;
    "windowY": number;
    "windowWidth": number;
    "windowHeight": number;
    "windowConfigured": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("gameLanguage" in $$source)) {
            this["gameLanguage"] = "";
        }
        if (!("questSite" in $$source)) {
            this["questSite"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("screenshotDirectory" in $$source)) {
            this["screenshotDirectory"] = "";
        }
        if (!("logsDirectory" in $$source)) {
            this["logsDirectory"] = "";
        }
        if (!("remoteId" in $$source)) {
            this["remoteId"] = "";
        }
        if (!("remoteTargets" in $$source)) {
            this["remoteTargets"] = [];
        }
        if (!("browserRemoteId" in $$source)) {
            this["browserRemoteId"] = "";
        }
        if (!("map" in $$source)) {
            this["map"] = "";
        }
        if (!("gameMode" in $$source)) {
            this["gameMode"] = "";
        }
        if (!("ocrEngine" in $$source)) {
            this["ocrEngine"] = "";
        }
        if (!("tesseractPath" in $$source)) {
            this["tesseractPath"] = "";
        }
        if (!("ocrDefaultRevision" in $$source)) {
            this["ocrDefaultRevision"] = 0;
        }
        if (!("debug" in $$source)) {
            this["debug"] = false;
        }
        if (!("saveRecognitionDebug" in $$source)) {
            this["saveRecognitionDebug"] = false;
        }
        if (!("screenshotCleanup" in $$source)) {
            this["screenshotCleanup"] = false;
        }
        if (!("screenshotRetainCount" in $$source)) {
            this["screenshotRetainCount"] = 0;
        }
        if (!("screenshotRetainHours" in $$source)) {
            this["screenshotRetainHours"] = 0;
        }
        if (!("soundsEnabled" in $$source)) {
            this["soundsEnabled"] = false;
        }
        if (!("questSoundEnabled" in $$source)) {
            this["questSoundEnabled"] = false;
        }
        if (!("questSoundPath" in $$source)) {
            this["questSoundPath"] = "";
        }
        if (!("errorSoundEnabled" in $$source)) {
            this["errorSoundEnabled"] = false;
        }
        if (!("errorSoundPath" in $$source)) {
            this["errorSoundPath"] = "";
        }
        if (!("taskNotMatchedSoundEnabled" in $$source)) {
            this["taskNotMatchedSoundEnabled"] = false;
        }
        if (!("taskNotMatchedSoundPath" in $$source)) {
            this["taskNotMatchedSoundPath"] = "";
        }
        if (!("remoteErrorSoundEnabled" in $$source)) {
            this["remoteErrorSoundEnabled"] = false;
        }
        if (!("remoteErrorSoundPath" in $$source)) {
            this["remoteErrorSoundPath"] = "";
        }
        if (!("itemSoundEnabled" in $$source)) {
            this["itemSoundEnabled"] = false;
        }
        if (!("itemSoundPath" in $$source)) {
            this["itemSoundPath"] = "";
        }
        if (!("itemNotMatchedSoundEnabled" in $$source)) {
            this["itemNotMatchedSoundEnabled"] = false;
        }
        if (!("itemNotMatchedSoundPath" in $$source)) {
            this["itemNotMatchedSoundPath"] = "";
        }
        if (!("soundVolume" in $$source)) {
            this["soundVolume"] = 0;
        }
        if (!("soundVoice" in $$source)) {
            this["soundVoice"] = "";
        }
        if (!("soundVoices" in $$source)) {
            this["soundVoices"] = {};
        }
        if (!("soundVolumeOffsets" in $$source)) {
            this["soundVolumeOffsets"] = {};
        }
        if (!("autoStartMonitoring" in $$source)) {
            this["autoStartMonitoring"] = false;
        }
        if (!("openMapOnRaidStart" in $$source)) {
            this["openMapOnRaidStart"] = false;
        }
        if (!("navigateMapOnPositionScreenshot" in $$source)) {
            this["navigateMapOnPositionScreenshot"] = false;
        }
        if (!("playerMarkerEffect" in $$source)) {
            this["playerMarkerEffect"] = "";
        }
        if (!("playerMarkerColor" in $$source)) {
            this["playerMarkerColor"] = "";
        }
        if (!("tarkovTrackerEnabled" in $$source)) {
            this["tarkovTrackerEnabled"] = false;
        }
        if (!("matchFoundSoundEnabled" in $$source)) {
            this["matchFoundSoundEnabled"] = false;
        }
        if (!("matchFoundSoundPath" in $$source)) {
            this["matchFoundSoundPath"] = "";
        }
        if (!("raidStartSoundEnabled" in $$source)) {
            this["raidStartSoundEnabled"] = false;
        }
        if (!("raidStartSoundPath" in $$source)) {
            this["raidStartSoundPath"] = "";
        }
        if (!("runThroughSoundEnabled" in $$source)) {
            this["runThroughSoundEnabled"] = false;
        }
        if (!("runThroughSoundPath" in $$source)) {
            this["runThroughSoundPath"] = "";
        }
        if (!("runThroughSeconds" in $$source)) {
            this["runThroughSeconds"] = 0;
        }
        if (!("questItemsSoundEnabled" in $$source)) {
            this["questItemsSoundEnabled"] = false;
        }
        if (!("questItemsSoundPath" in $$source)) {
            this["questItemsSoundPath"] = "";
        }
        if (!("restartTasksSoundEnabled" in $$source)) {
            this["restartTasksSoundEnabled"] = false;
        }
        if (!("restartTasksSoundPath" in $$source)) {
            this["restartTasksSoundPath"] = "";
        }
        if (!("startMinimized" in $$source)) {
            this["startMinimized"] = false;
        }
        if (!("minimizeToTray" in $$source)) {
            this["minimizeToTray"] = false;
        }
        if (!("closeToTray" in $$source)) {
            this["closeToTray"] = false;
        }
        if (!("keepPriority" in $$source)) {
            this["keepPriority"] = false;
        }
        if (!("launchAtStartup" in $$source)) {
            this["launchAtStartup"] = false;
        }
        if (!("autoUpdate" in $$source)) {
            this["autoUpdate"] = false;
        }
        if (!("updateChannel" in $$source)) {
            this["updateChannel"] = "";
        }
        if (!("windowX" in $$source)) {
            this["windowX"] = 0;
        }
        if (!("windowY" in $$source)) {
            this["windowY"] = 0;
        }
        if (!("windowWidth" in $$source)) {
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            this["windowHeight"] = 0;
        }
        if (!("windowConfigured" in $$source)) {
            this["windowConfigured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField6_0 = $$createType1;
        const $$createField33_0 = $$createType2;
        const $$createField34_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("remoteTargets" in $$parsedSource) {
            $$parsedSource["remoteTargets"] = $$createField6_0($$parsedSource["remoteTargets"]);
        }
        if ("soundVoices" in $$parsedSource) {
            $$parsedSource["soundVoices"] = $$createField33_0($$parsedSource["soundVoices"]);
        }
        if ("soundVolumeOffsets" in $$parsedSource) {
            $$parsedSource["soundVolumeOffsets"] = $$createField34_0($$parsedSource["soundVolumeOffsets"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = RemoteTarget.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
