// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RemoteTarget {
    "id": string;
    "name": string;
    "map": boolean;
    "tasks": boolean;

    /** Creates a new RemoteTarget instance. */
    constructor($$source: Partial<RemoteTarget> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("map" in $$source)) {
            this["map"] = false;
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteTarget($$parsedSource as Partial<RemoteTarget>);
    }
}

export class Settings {
    "gameLanguage": string;
    "questSite": string;
    "hideoutErrorNotifications": boolean;
    "hideoutErrorSoundPath": string;
    "language": string;
    "screenshotDirectory": string;
    "logsDirectory": string;
    "remoteId": string;
    "remoteTargets": RemoteTarget[];
    "browserRemoteId": string;
    "map": string;
    "gameMode": string;
    "ocrEngine": string;
    "tesseractPath": string;

    /**
     * OCRDefaultRevision records one-time moves to a new default OCR engine.
     */
    "ocrDefaultRevision": number;
    "debug": boolean;
    "saveRecognitionDebug": boolean;
    "screenshotCleanup": boolean;
    "screenshotRetainCount": number;
    "screenshotRetainHours": number;
    "soundsEnabled": boolean;
    "questSoundEnabled": boolean;
    "questSoundPath": string;
    "errorSoundEnabled": boolean;
    "errorSoundPath": string;
    "soundVolume": number;
    "autoStartMonitoring": boolean;
    "openMapOnRaidStart": boolean;
    "navigateMapOnPositionScreenshot": boolean;
    "tarkovTrackerEnabled": boolean;
    "matchFoundSoundEnabled": boolean;
    "matchFoundSoundPath": string;
    "raidStartSoundEnabled": boolean;
    "raidStartSoundPath": string;
    "runThroughSoundEnabled": boolean;
    "runThroughSoundPath": string;
    "runThroughSeconds": number;
    "questItemsSoundEnabled": boolean;
    "questItemsSoundPath": string;
    "restartTasksSoundEnabled": boolean;
    "restartTasksSoundPath": string;
    "startMinimized": boolean;

    /**
     * MinimizeToTray removes the taskbar entry when the window is minimized;
     * CloseToTray keeps the app running in the tray when it is closed.
     */
    "minimizeToTray": boolean;
    "closeToTray": boolean;
    "launchAtStartup": boolean;
    "windowX": number;
    "windowY": number;
    "windowWidth": number;
    "windowHeight": number;
    "windowConfigured": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("gameLanguage" in $$source)) {
            this["gameLanguage"] = "";
        }
        if (!("questSite" in $$source)) {
            this["questSite"] = "";
        }
        if (!("hideoutErrorNotifications" in $$source)) {
            this["hideoutErrorNotifications"] = false;
        }
        if (!("hideoutErrorSoundPath" in $$source)) {
            this["hideoutErrorSoundPath"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("screenshotDirectory" in $$source)) {
            this["screenshotDirectory"] = "";
        }
        if (!("logsDirectory" in $$source)) {
            this["logsDirectory"] = "";
        }
        if (!("remoteId" in $$source)) {
            this["remoteId"] = "";
        }
        if (!("remoteTargets" in $$source)) {
            this["remoteTargets"] = [];
        }
        if (!("browserRemoteId" in $$source)) {
            this["browserRemoteId"] = "";
        }
        if (!("map" in $$source)) {
            this["map"] = "";
        }
        if (!("gameMode" in $$source)) {
            this["gameMode"] = "";
        }
        if (!("ocrEngine" in $$source)) {
            this["ocrEngine"] = "";
        }
        if (!("tesseractPath" in $$source)) {
            this["tesseractPath"] = "";
        }
        if (!("ocrDefaultRevision" in $$source)) {
            this["ocrDefaultRevision"] = 0;
        }
        if (!("debug" in $$source)) {
            this["debug"] = false;
        }
        if (!("saveRecognitionDebug" in $$source)) {
            this["saveRecognitionDebug"] = false;
        }
        if (!("screenshotCleanup" in $$source)) {
            this["screenshotCleanup"] = false;
        }
        if (!("screenshotRetainCount" in $$source)) {
            this["screenshotRetainCount"] = 0;
        }
        if (!("screenshotRetainHours" in $$source)) {
            this["screenshotRetainHours"] = 0;
        }
        if (!("soundsEnabled" in $$source)) {
            this["soundsEnabled"] = false;
        }
        if (!("questSoundEnabled" in $$source)) {
            this["questSoundEnabled"] = false;
        }
        if (!("questSoundPath" in $$source)) {
            this["questSoundPath"] = "";
        }
        if (!("errorSoundEnabled" in $$source)) {
            this["errorSoundEnabled"] = false;
        }
        if (!("errorSoundPath" in $$source)) {
            this["errorSoundPath"] = "";
        }
        if (!("soundVolume" in $$source)) {
            this["soundVolume"] = 0;
        }
        if (!("autoStartMonitoring" in $$source)) {
            this["autoStartMonitoring"] = false;
        }
        if (!("openMapOnRaidStart" in $$source)) {
            this["openMapOnRaidStart"] = false;
        }
        if (!("navigateMapOnPositionScreenshot" in $$source)) {
            this["navigateMapOnPositionScreenshot"] = false;
        }
        if (!("tarkovTrackerEnabled" in $$source)) {
            this["tarkovTrackerEnabled"] = false;
        }
        if (!("matchFoundSoundEnabled" in $$source)) {
            this["matchFoundSoundEnabled"] = false;
        }
        if (!("matchFoundSoundPath" in $$source)) {
            this["matchFoundSoundPath"] = "";
        }
        if (!("raidStartSoundEnabled" in $$source)) {
            this["raidStartSoundEnabled"] = false;
        }
        if (!("raidStartSoundPath" in $$source)) {
            this["raidStartSoundPath"] = "";
        }
        if (!("runThroughSoundEnabled" in $$source)) {
            this["runThroughSoundEnabled"] = false;
        }
        if (!("runThroughSoundPath" in $$source)) {
            this["runThroughSoundPath"] = "";
        }
        if (!("runThroughSeconds" in $$source)) {
            this["runThroughSeconds"] = 0;
        }
        if (!("questItemsSoundEnabled" in $$source)) {
            this["questItemsSoundEnabled"] = false;
        }
        if (!("questItemsSoundPath" in $$source)) {
            this["questItemsSoundPath"] = "";
        }
        if (!("restartTasksSoundEnabled" in $$source)) {
            this["restartTasksSoundEnabled"] = false;
        }
        if (!("restartTasksSoundPath" in $$source)) {
            this["restartTasksSoundPath"] = "";
        }
        if (!("startMinimized" in $$source)) {
            this["startMinimized"] = false;
        }
        if (!("minimizeToTray" in $$source)) {
            this["minimizeToTray"] = false;
        }
        if (!("closeToTray" in $$source)) {
            this["closeToTray"] = false;
        }
        if (!("launchAtStartup" in $$source)) {
            this["launchAtStartup"] = false;
        }
        if (!("windowX" in $$source)) {
            this["windowX"] = 0;
        }
        if (!("windowY" in $$source)) {
            this["windowY"] = 0;
        }
        if (!("windowWidth" in $$source)) {
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            this["windowHeight"] = 0;
        }
        if (!("windowConfigured" in $$source)) {
            this["windowConfigured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("remoteTargets" in $$parsedSource) {
            $$parsedSource["remoteTargets"] = $$createField8_0($$parsedSource["remoteTargets"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = RemoteTarget.createFrom;
const $$createType1 = $Create.Array($$createType0);
