// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Extent is a height range of a floor, optionally only within some areas
 * ([[x1, z1], [x2, z2]] in game coordinates).
 */
export class Extent {
    "height": number[];
    "bounds"?: number[][][];

    /** Creates a new Extent instance. */
    constructor($$source: Partial<Extent> = {}) {
        if (!("height" in $$source)) {
            this["height"] = Array.from({ length: 2 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Extent instance from a string or object.
     */
    static createFrom($$source: any = {}): Extent {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField1_0($$parsedSource["bounds"]);
        }
        return new Extent($$parsedSource as Partial<Extent>);
    }
}

/**
 * Layer is a floor above or below the ground level.
 */
export class Layer {
    "name": string;
    "svgLayer": string;
    "extents": Extent[];

    /** Creates a new Layer instance. */
    constructor($$source: Partial<Layer> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("svgLayer" in $$source)) {
            this["svgLayer"] = "";
        }
        if (!("extents" in $$source)) {
            this["extents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Layer instance from a string or object.
     */
    static createFrom($$source: any = {}): Layer {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extents" in $$parsedSource) {
            $$parsedSource["extents"] = $$createField2_0($$parsedSource["extents"]);
        }
        return new Layer($$parsedSource as Partial<Layer>);
    }
}

/**
 * Map is one interactive map. Keys are tarkov.dev's map names; Aliases are
 * the other names that use the same map (night-factory, ground-zero-21).
 */
export class Map {
    "key": string;
    "aliases"?: string[];
    "svg"?: string;
    "svgLayer"?: string;
    "transform": number[];
    "rotation": number;
    "bounds": number[][];
    "svgBounds"?: number[][] | null;
    "minZoom": number;
    "maxZoom": number;
    "author"?: string;
    "authorLink"?: string;
    "layers"?: Layer[];

    /** Creates a new Map instance. */
    constructor($$source: Partial<Map> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("transform" in $$source)) {
            this["transform"] = Array.from({ length: 4 }, () => 0);
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }
        if (!("bounds" in $$source)) {
            this["bounds"] = Array.from({ length: 2 }, () => Array.from({ length: 2 }, () => 0));
        }
        if (!("minZoom" in $$source)) {
            this["minZoom"] = 0;
        }
        if (!("maxZoom" in $$source)) {
            this["maxZoom"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Map instance from a string or object.
     */
    static createFrom($$source: any = {}): Map {
        const $$createField1_0 = $$createType3;
        const $$createField12_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField1_0($$parsedSource["aliases"]);
        }
        if ("layers" in $$parsedSource) {
            $$parsedSource["layers"] = $$createField12_0($$parsedSource["layers"]);
        }
        return new Map($$parsedSource as Partial<Map>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Extent.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = Layer.createFrom;
const $$createType5 = $Create.Array($$createType4);
