// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * VoicePack is a built-in voice, as the settings list it.
 */
export class VoicePack {
    "id": string;

    /**
     * Name is the speaker's name by UI language ("ja", "en").
     */
    "name": { [_ in string]?: string };
    "language": string;
    "order": number;

    /**
     * Credit is the notice its terms ask for ("VOICEVOX:春日部つむぎ"),
     * Terms their page and TermsChecked when they were last read.
     */
    "credit": string;
    "terms": string;
    "termsChecked": string;

    /** Creates a new VoicePack instance. */
    constructor($$source: Partial<VoicePack> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = {};
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }
        if (!("credit" in $$source)) {
            this["credit"] = "";
        }
        if (!("terms" in $$source)) {
            this["terms"] = "";
        }
        if (!("termsChecked" in $$source)) {
            this["termsChecked"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoicePack instance from a string or object.
     */
    static createFrom($$source: any = {}): VoicePack {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField1_0($$parsedSource["name"]);
        }
        return new VoicePack($$parsedSource as Partial<VoicePack>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
