// The strings of the browser shell, the item panel and the popup window, by
// language. Both languages carry the same keys (words.test.js); the settings
// page has its own typed table in ../i18n.ts.
export const words={
 ja:{
  // Toolbar, sidebar, welcome page, settings
  home:'ホーム',settings:'設定',menu:'メニュー',off:'受信OFF',back:'戻る',forward:'進む',reload:'再読み込み',address:'URL または検索語を入力',open:'開く',close:'閉じる',pin:'固定',unpin:'固定解除',newTab:'新しいタブ',welcome:'レイドの準備を、ここから。',intro:'マップ、タスク、調べものを一つのウインドウに。',maps:'マップ',tasks:'タスク攻略',items:'アイテム',progress:'進捗管理',other:'その他',addBookmark:'ブックマークを追加',edit:'編集',delete:'削除',name:'名前',url:'URL',group:'分類',done:'確定',cancel:'キャンセル',empty:'ブックマークを追加して、よく使うサイトをまとめましょう。',client:'ブラウザ設定',host:'Host設定・ログ',appearance:'表示',language:'表示言語',layout:'タブの配置',vertical:'左サイドバー',horizontal:'上部の横並び',recognition:'タスクの自動表示',taskMode:'検出したタスクを開く方法',reuse:'同じタブを更新',new:'新しいタブを追加',questSite:'表示するサイト',hostChoice:'Hostの設定に従う',official:'公式Wiki',japanese:'日本語Wiki',taskHelp:'表示中のタスクは、上のサイト選択で英語Wiki・日本語Wikiを切り替えられます。固定したタブは自動更新の対象外です。',connection:'Host接続',mode:'接続方法',local:'このPCで検出する',disabled:'接続しない',localHelp:'このPCの検出結果をタブに表示します。',bookmarkHelp:'カードをクリックして開く。名前と分類は編集できます。',tabHelp:'ドラッグで順序変更',dismiss:'閉じる',searchWiki:'Wiki内で検索',pinHelp:'固定中',
  // Bosses, Goons reports, clock, screenshots
  bossMapBosses:'マップのボス',goonReport:'Goons を報告',goonReportOnly:'実際に Goons に遭遇したレイドだけ報告してください。報告は tarkov.dev に表示される目撃情報に加わります。',goonAccount:'報告するアカウント（EFT のログから）',goonNoAccount:'EFT のログにアカウントが見つかりません。一度ゲームを起動してください。',goonWhen:'いつ見たか',goonRaidNow:'今のレイド',goonRaidLast:'直前のレイド',goonStarted:'開始',goonAlready:'報告済み',goonWhenNow:'今の時刻で報告',goonConsent:'tarkov.dev は、報告と一緒にあなたの IP アドレスと選んだ EFT アカウント ID を保存します（不正な報告を追跡するため）。',goonSend:'報告する',goonSending:'送信中…',goonReported:'報告しました。tarkov.dev の目撃情報に反映されるまで最大10分ほどかかります。',goonCurrent:'プレイ中',goonLastSeen:'最終',bossAuto:'自動',bossModeLabel:'ゲームモード',bossPickHint:'マップを選ぶか、レイドに入るとボスを表示します',clockFormat:'時刻の表示',clock24:'24時間表示（13:05）',clock12:'12時間表示（1:05 PM）',shotKind_tasks:'タスク',shotKind_item:'アイテム',shotKind_offer:'出品',shotKind_position:'位置',shotKind_unknown:'判定なし',shotInfo:'判定の詳細',shotInfoKind:'種類',shotInfoMatch:'一致',shotInfoConfidence:'一致度',shotInfoCandidates:'候補',shotInfoLayout:'画面の形',shotInfoScore:'検出スコア',shotInfoMap:'マップ',shotInfoRaid:'レイド中',shotInfoPosition:'座標',shotInfoStage:'状態',shotInfoError:'エラー',yes:'はい',no:'いいえ',bosses:'ボス',allBosses:'ボスの詳細',bossesLoading:'ボス情報を読み込み中…',noGoons:'最近の報告なし',noBosses:'ボスは出ません',escorts:'取り巻き',goonHint:'Goons の位置はプレイヤーの報告（tarkov.dev）です。報告が新しいほど、今もそのマップにいる可能性が高くなります。',goonMaps:'Goons が出るマップ',bossMaps:'マップ',zoomIn:'拡大',zoomOut:'縮小',zoomFit:'全体を表示（リセット）',screenshots:'スクリーンショット',allScreenshots:'すべてのスクリーンショット',noScreenshots:'スクリーンショットはまだありません',screenshotsHostOnly:'スクリーンショットはHostのPCで見られます',openScreenshotFolder:'フォルダを開く',newerScreenshot:'新しい方へ',olderScreenshot:'古い方へ',
  webrtc:'インターネット経由（WebRTC・直接接続）',p2pTitle:'別のPCへ直接送信',p2pReceive:'接続コードで接続',p2pHelp:'両方の PC で MAYAK を開き、Host に出る 8 桁の接続コードを相手側に入力します。コードの受け渡しだけ mayak.ich.sh を経由し（10 分で失効）、接続後のタスク・マップ表示指示は暗号化して直接送ります。',pairCodeHelp:'相手の PC の MAYAK で 設定 → 他のPCとの接続 を開き、この番号を入力してください。応答は自動で受け取ります。10 分で失効します。',enterPairCode:'Host に表示された 8 桁の接続コード',joinPair:'接続する',manualExchange:'コードを手動で交換する（サーバーを使わない）',manualExchangeHelp:'mayak.ich.sh を経由したくないときは、長い招待コードと応答コードを自分でコピーして渡します。',relayFailed:'接続サーバー（mayak.ich.sh）に届きませんでした。下の手動交換を使ってください。',p2pWaitingHostAuto:'Host の応答を待っています（自動）',p2pLimit:'STUNは接続先の探索だけに使用します。中継サーバーは使用しないため、回線によっては接続できません。アプリの再起動や接続切れの際はコードを再交換してください。',createInvite:'接続コードを発行',inviteCode:'招待コード',answerCode:'応答コード',copyCode:'コードをコピー',copied:'コピーしました',enterOffer:'Host側の招待コードを貼り付け',createAnswer:'応答コードを作成',enterAnswer:'受信側の応答コードを貼り付け',finishPairing:'接続する',disconnectPeer:'切断 / キャンセル',offerStep:'① このコードを受信側へ渡してください（有効期限10分）。',answerStep:'② このコードをHost側へ返してください。',stunLabel:'STUNサーバー',stunHelp:'空欄にすると探索サーバーも使いません。直接到達できるネットワーク向けです。',p2pIdle:'未接続',p2pGathering:'接続情報を準備しています…',p2pWaitingAnswer:'受信側の応答待ち',p2pWaitingHost:'Host側で応答コードを入力してください',p2pConnecting:'直接接続を試みています…',p2pConnected:'直接接続中（中継なし）',p2pFailed:'直接接続できませんでした。コードを作り直すか、別の回線をお試しください。',p2pDisconnected:'接続が切れました。コードを再交換してください。',p2pExpired:'招待コードの有効期限が切れました。',
  // Tutorial
  tutorialShow:'チュートリアルを表示',tutorialShowHelp:'初回起動時の案内（フォルダ、スクリーンショットキー、マップ、TarkovTracker）をもう一度見ます。',tutStep:'ステップ',tutStart:'はじめる',tutLater:'あとで',tutNext:'次へ',tutBack:'戻る',tutSkip:'スキップ',tutFinish:'完了',
 tutWelcomeTitle:'MAYAK へようこそ',tutWelcome:'ゲーム内で撮影したスクリーンショットとログを読むだけで、マップ・タスク・アイテム情報をこのウインドウに映します。ゲーム本体には触れません。この案内に沿って進めれば、準備は数分で終わります。',
 tutFoldersTitle:'EFT のフォルダ',tutFolders:'スクリーンショットとログのフォルダを自動で探しました。違っていれば設定で選び直せます。',tutFoldersScreens:'スクリーンショット',tutFoldersLogs:'ログ',tutNotFound:'未検出。設定で選んでください',tutOpenFolders:'フォルダの設定を開く',
 tutKeyTitle:'スクリーンショットキーを押しやすい場所に',tutKey:'EFT の Settings → Controls → Screenshot。既定は PrintScreen ですが戦闘中に届きにくいので、マウスのサイドボタンや左手で届く空きキーへの割り当てをおすすめします。',tutKeyNote:'座標が入るのは EFT 自身のスクリーンショット機能で保存したファイルだけです。Steam や Windows のスクリーンショットは対象外です。',
 tutMapTitle:'レイド中はそのキーを押すだけ',tutMap:'このウインドウのマップタブは、設定なしで現在地に追従します。タスク一覧で該当のタスクを開いた状態か、アイテム詳細を撮れば、それぞれの情報も表示されます（一覧だけの画面ではどのタスクか分かりません）。1 台の PC でマルチモニタなら、これで完結です。',tutOpenMap:'マップを開く',
 tutRemoteTitle:'別の PC や普段のブラウザで見るなら（任意）',tutRemote:'そのブラウザで tarkov.dev のマップを開き、左下の接続ボタンを押します。同じ PC の Chrome / Edge / Brave なら Remote ID は自動検出、別の PC やタブレットなら ID を入力します。別の PC で MAYAK 自体を動かすなら、設定 → 他のPCとの接続 の 8 桁の接続コードで繋がります。',tutOpenRemote:'tarkov.dev 連携の設定を開く',
 tutTrackerTitle:'TarkovTracker で進捗を自動記録（任意）',tutTracker:'TarkovTracker はタスクの進捗を管理できる無料のサイトです。Settings → API Tokens で GP と WP を付けたトークンを作って取り込むと、受注・完了・失敗が自動で反映されます。',tutOpenTracker:'TarkovTracker の設定を開く',
 tutDoneTitle:'準備完了',tutDone:'この案内は 設定 → 表示 からいつでも見直せます。良いレイドを。',
  // Tab list and updates
  allTabs:'すべてのタブ',searchTabs:'タブを検索',tabsHint:'開いているタブを名前とアドレスで探せます。クリックで切り替え、× で閉じます。',noTabResults:'一致するタブはありません。',tabsClose:'タブを閉じる',updateSection:'アップデート',updateChannel:'更新チャンネル',updateChannelStable:'安定版',updateChannelNightly:'nightly（開発中の版）',updateChannelHelp:'nightly は開発中の変更を毎日ビルドした版で、不具合が残っていることがあります。nightly を選んでいても、安定版の方が新しいときは安定版に更新します。安定版に戻すと、ダウンロード済みの nightly は破棄し、次の安定版から更新します。',updateCurrent:'現在の版',updateLatest:'最新の版',updateCheck:'更新を確認',updateChecking:'確認しています…',updateCheckedAt:'最終確認',updateUpToDate:'最新の版です',updateNever:'まだ確認していません',updateUnsupported:'このプラットフォーム向けのビルドがありません',updateError:'確認できませんでした',updateAutoNote:'自動更新は 設定 → 起動とウィンドウ で切り替えられます。',updateDownloading:'MAYAK {v} をダウンロード中',updateReady:'MAYAK {v} の準備ができました',updateRestart:'再起動して適用',updateDownload:'ダウンロード',updateLater:'あとで',updateNotes:'変更点',updateReadyHint:'いま適用しなくても、次に MAYAK を終了したときに入れ替わります。',
  // Translate, sidebar, theme, ad blocking
  translatePage:'このページを翻訳（Google 翻訳）',translateOff:'翻訳をやめて元のページに戻る',translateWiki:'公式 Wiki（英語）を翻訳して開く',translateWikiHelp:'タスクの検出で開く公式 Wiki のページを、Google 翻訳（translate.goog）経由で表示します。Chrome の「ページを翻訳」は WebView2 に無いため、その代わりです。ツールバーの翻訳ボタンでどのページでも同じことができます。',homeHelp:'最初のページに戻る',fixedAddress:'固定表示のためアドレスは変更できません',openExternal:'既定のブラウザで開く',closeSettings:'設定を閉じる',collapseSection:'折りたたむ',expandSection:'展開する',groupHint:'選ぶか入力',resizeSidebar:'ドラッグで幅を変更（ダブルクリックで元に戻す）',allBookmarks:'すべてのブックマーク',searchBookmarks:'ブックマークを検索',gridView:'タイル表示',listView:'リスト表示',pinToSidebar:'サイドバーにピン留め',unpinFromSidebar:'サイドバーから外す',bookmarkDropHint:'ブックマークをここへドラッグしてピン留め',bookmarkDragHint:'サイドバーの「ブックマーク」へドラッグすると、サイドバーにピン留めできます。',noBookmarkResults:'一致するブックマークはありません。',collapseSidebar:'サイドバーを閉じる',expandSidebar:'サイドバーを開く',minimise:'最小化',maximise:'最大化',restore:'元に戻す',theme:'テーマ',themeSystem:'システムに合わせる',adblock:'広告ブロック',adblockEnable:'広告とトラッカーをブロックする',adblockHelp:'EasyList・EasyPrivacy・AdGuard日本語フィルタで広告を止め、広告があった場所の空欄も詰めます。フィルタは EasyList（easylist.to）と AdGuard が公開しているリストで、自動で更新されます。tarkov.dev は広告で運営されているため対象外です。切り替えると表示中のページを再読み込みします。',mapTab:'TARKOV.DEV',mapTabHelp:'tarkov.dev のマップ。Remote Control で接続済みのまま、検出したマップと位置を表示します。',tabs:'タブ',bookmarks:'ブックマーク',hostMode:'Hostモード',clientMode:'Clientモード',menuHint:'MAYAK メニュー',noTabs:'ロゴのメニューからサイトや設定を開けます。',
  // Status bar, settings sections, about
  tracker_connected:'同期中',tracker_connecting:'接続中','tracker_waiting-profile':'プロフィール待ち','tracker_missing-token':'APIキー未設定',tracker_error:'エラー',tracker_disabled:'オフ',monitorOn:'監視中',monitorOff:'監視停止中',monitorStart:'クリックで監視を開始',monitorStop:'クリックで監視を停止',inRaid:'レイド中',outRaid:'レイド外',trackerLabel:'TarkovTracker',taskSiteHelp:'タスクを認識したときと、アイテム情報からタスクを開くときのサイトです。tarkov.dev の Remote Control へ送るかどうかは「tarkov.dev 連携」の接続先ごとに選べます。',taskSiteClientHelp:'「Hostの設定に従う」にすると、Host側で選んだサイトで開きます。',settingsBack:'設定を閉じる',grpGeneral:'一般',grpGame:'ゲーム',grpLinks:'連携',grpBrowser:'ブラウザ',grpDiagnostics:'状態と診断',sec_appearance:'表示',sec_tasks:'タスクの開き方',sec_adblock:'広告ブロック',sec_connection:'他のPCとの接続',sec_status:'ステータス',sec_logs:'ログ',sec_folders:'フォルダと保存',sec_recognition:'ゲームと認識',sec_remote:'tarkov.dev 連携',sec_tracker:'TarkovTracker',sec_sounds:'通知',sec_startup:'起動とウィンドウ',sec_debug:'デバッグ',grpAbout:'情報',sec_about:'MAYAK について',aboutVersion:'バージョン',aboutDev:'開発ビルド',aboutTagline:'Escape from Tarkov のスクリーンショットとログから、マップ・タスク・アイテム情報を映すコンパニオン。',aboutSite:'公式サイト',aboutSource:'GitHub',aboutReleases:'変更履歴',aboutLicense:'GPL-3.0 で公開しています。',aboutCredits:'マップは tarkov.dev、タスクの進捗は TarkovTracker のデータと API を使っています。Escape from Tarkov は Battlestate Games の商標で、MAYAK は非公式のツールです。',
  // Layout and item panel
  placement:'配置を変更',navPosition:'タブの位置',itemDock:'アイテム情報の位置',placeLeft:'左',placeRight:'右',placeTop:'上',placeBottom:'下',openItemPage:'アイテムのページを開く',itemSearch:'アイテムを検索',itemSearchHint:'上のルーペからアイテム名で検索できます。ゲームでアイテムを調べてスクショを撮っても、ここに情報が出ます。',itemNoResults:'見つかりませんでした',openTask:'タスクを開く',itemPanel:'アイテム情報',itemShow:'アイテム情報を表示',itemHide:'アイテム情報を閉じる',itemRefresh:'最新の価格を取得',itemLive:'LIVE',itemCatalog:'カタログ',itemPriced:'価格更新',bestSale:'一番高く売れる先',perSlot:'1マス',flea:'フリーマーケット',fleaLow:'最安値',fleaAvg:'24時間平均',fleaRange:'24時間の幅',fleaChange:'48時間の変動',fleaOffers:'出品数',fleaLevel:'利用可能レベル',noFlea:'フリーマーケットでは売れません',traders:'トレーダー買取',itemTasks:'必要なタスク',itemHideout:'必要なハイドアウト',noNeeds:'なし',fir:'FIR',needDone:'完了',progressUnknown:'TarkovTrackerと同期すると完了済みがわかります',
  // Price chart
  priceHistory:'価格の推移',range7d:'7日',range30d:'30日',rangeAll:'全期間',avgLine:'平均',minLine:'最安値',chartHigh:'最高',chartLow:'最安',chartLoading:'価格の履歴を読み込み中…',chartFailed:'価格の履歴を取得できませんでした',chartEmpty:'この期間の履歴はありません',chartNow:'現在',
  // Popup window and api.js messages
  popupPin:'ピン留め (ほかをクリックしても閉じない)',popupUnpin:'ピン留めを外す',openInTab:'タブで開く',openExternalBrowser:'外部ブラウザで開く',actionFailed:'操作を完了できませんでした: ',enterWebURL:'http / https のURLを入力してください',
 },
 en:{
  // Toolbar, sidebar, welcome page, settings
  home:'Home',settings:'Settings',menu:'Menu',off:'Receiving off',back:'Back',forward:'Forward',reload:'Reload',address:'Search Google or type a URL',open:'Open',close:'Close',pin:'Pin',unpin:'Unpin',newTab:'New tab',welcome:'Get ready for your next raid.',intro:'Maps, tasks and research, together in one window.',maps:'Maps',tasks:'Task guides',items:'Items',progress:'Progress',other:'Other',addBookmark:'Add bookmark',edit:'Edit',delete:'Delete',name:'Name',url:'URL',group:'Category',done:'Done',cancel:'Cancel',empty:'Add bookmarks to keep your useful sites together.',client:'Browser settings',host:'Host settings & logs',appearance:'Appearance',language:'Language',layout:'Tab placement',vertical:'Left sidebar',horizontal:'Across the top',recognition:'Automatic task navigation',taskMode:'Open recognized tasks',reuse:'Reuse the task tab',new:'Add a new tab',questSite:'Website',hostChoice:'Follow Host setting',official:'Official Wiki',japanese:'Japanese Wiki',taskHelp:'Switch the current task between English and Japanese wikis using the website selector above. Pinned tabs are never replaced automatically.',connection:'Host connection',mode:'Connection mode',local:'Detect on this computer',disabled:'No connection',localHelp:'Show detections from this computer in tabs.',bookmarkHelp:'Click a card to open it. Names and categories are editable.',tabHelp:'Drag to reorder',dismiss:'Dismiss',searchWiki:'Search this Wiki',pinHelp:'Pinned',
  // Bosses, Goons reports, clock, screenshots
  bossMapBosses:"Map's bosses",goonReport:'Report the Goons',goonReportOnly:'Only report a raid where you actually ran into the Goons. The report is added to the sightings shown on tarkov.dev.',goonAccount:'Account to report with (from the EFT logs)',goonNoAccount:'No account in the EFT logs yet. Start the game once.',goonWhen:'When you saw them',goonRaidNow:'This raid',goonRaidLast:'The last raid',goonStarted:'start',goonAlready:'reported',goonWhenNow:'Report at the current time',goonConsent:'tarkov.dev stores the report together with your IP address and the EFT account ID you chose, so that misuse can be traced.',goonSend:'Report',goonSending:'Sending…',goonReported:'Reported. It shows in the tarkov.dev sightings within about ten minutes.',goonCurrent:'playing',goonLastSeen:'last seen',bossAuto:'Auto',bossModeLabel:'Game mode',bossPickHint:'Choose a map, or enter a raid, to see its bosses',clockFormat:'Time format',clock24:'24-hour (13:05)',clock12:'12-hour (1:05 PM)',shotKind_tasks:'Task',shotKind_item:'Item',shotKind_offer:'Offer',shotKind_position:'Position',shotKind_unknown:'Not recognized',shotInfo:'Recognition details',shotInfoKind:'Kind',shotInfoMatch:'Match',shotInfoConfidence:'Match confidence',shotInfoCandidates:'Candidates',shotInfoLayout:'Layout',shotInfoScore:'Detection score',shotInfoMap:'Map',shotInfoRaid:'In raid',shotInfoPosition:'Position',shotInfoStage:'Stage',shotInfoError:'Error',yes:'Yes',no:'No',bosses:'Bosses',allBosses:'Boss details',bossesLoading:'Loading bosses…',noGoons:'no recent reports',noBosses:'No bosses',escorts:'Escorts',goonHint:'Goons locations are player reports (tarkov.dev). The newer a report, the likelier they are still on that map.',goonMaps:'Maps the Goons spawn on',bossMaps:'Maps',zoomIn:'Zoom in',zoomOut:'Zoom out',zoomFit:'Fit to page (reset)',screenshots:'Screenshots',allScreenshots:'All screenshots',noScreenshots:'No screenshots yet',screenshotsHostOnly:'Screenshots are shown on the Host computer',openScreenshotFolder:'Open folder',newerScreenshot:'Newer',olderScreenshot:'Older',
  webrtc:'Over the internet (WebRTC direct)',p2pTitle:'Send directly to another computer',p2pReceive:'Connect with a code',p2pHelp:'Open MAYAK on both PCs and enter the 8-digit code shown on the Host into the other one. Only the code goes through mayak.ich.sh (it expires in 10 minutes); once connected, task and map commands are sent directly, encrypted.',pairCodeHelp:'On the other PC, open MAYAK → Settings → Other computers and enter this number. The response is picked up automatically. It expires in 10 minutes.',enterPairCode:'The 8-digit code shown on the Host',joinPair:'Connect',manualExchange:'Exchange the codes by hand (no server)',manualExchangeHelp:'To keep mayak.ich.sh out of it, copy the long invitation and response codes across yourself.',relayFailed:'The pairing server (mayak.ich.sh) could not be reached; use the manual exchange below.',p2pWaitingHostAuto:'Waiting for the Host (automatic)',p2pLimit:'STUN only discovers connection addresses. No relay server is used, so some networks cannot connect. Exchange fresh codes after restarting the app or losing the connection.',createInvite:'Get a code',inviteCode:'Invitation code',answerCode:'Response code',copyCode:'Copy code',copied:'Copied',enterOffer:'Paste the invitation from the Host',createAnswer:'Create response',enterAnswer:'Paste the response from the receiver',finishPairing:'Connect',disconnectPeer:'Disconnect / cancel',offerStep:'1. Give this code to the receiver (expires in 10 minutes).',answerStep:'2. Return this code to the Host.',stunLabel:'STUN server',stunHelp:'Leave empty to use no discovery server. Requires directly reachable network addresses.',p2pIdle:'Not connected',p2pGathering:'Preparing connection details…',p2pWaitingAnswer:'Waiting for the receiver’s response',p2pWaitingHost:'Enter the response on the Host',p2pConnecting:'Trying a direct connection…',p2pConnected:'Direct connection (no relay)',p2pFailed:'A direct connection could not be established. Try fresh codes or another network.',p2pDisconnected:'Connection lost. Exchange fresh codes to reconnect.',p2pExpired:'The invitation has expired.',
  // Tutorial
  tutorialShow:'Show the tutorial',tutorialShowHelp:'See the first-run guide again: folders, the screenshot key, the map and TarkovTracker.',tutStep:'Step',tutStart:'Get started',tutLater:'Later',tutNext:'Next',tutBack:'Back',tutSkip:'Skip',tutFinish:'Done',
 tutWelcomeTitle:'Welcome to MAYAK',tutWelcome:'MAYAK reads only the screenshots you take in the game and the logs it writes, and shows maps, tasks and item info in this window. It never touches the game itself. Follow this guide and setup takes a few minutes.',
 tutFoldersTitle:'EFT folders',tutFolders:'The Screenshots and Logs folders were looked up automatically. If they are wrong, pick them in the settings.',tutFoldersScreens:'Screenshots',tutFoldersLogs:'Logs',tutNotFound:'Not found; pick it in the settings',tutOpenFolders:'Open the folder settings',
 tutKeyTitle:'Put the screenshot key within reach',tutKey:'In EFT: Settings → Controls → Screenshot. The default is PrintScreen, which is hard to reach mid-fight, so bind it to a mouse side button or a free key near your left hand.',tutKeyNote:'Only screenshots taken with EFT’s own function carry coordinates; Steam or Windows screenshots do not.',
 tutMapTitle:'In a raid, just press that key',tutMap:'The map tab in this window follows your position with no setup. Screenshot a task opened in the Tasks screen, or an item window, and that info appears too (the list alone does not show which task). On one PC with several monitors, that is all you need.',tutOpenMap:'Open the map',
 tutRemoteTitle:'Another PC or your usual browser (optional)',tutRemote:'Open the tarkov.dev map there and click the connect button at the bottom left. Chrome, Edge and Brave on this PC are detected automatically; from another PC or a tablet, type the Remote ID in. To run MAYAK itself on another PC, pair it with the 8-digit code under Settings → Other computers.',tutOpenRemote:'Open the tarkov.dev settings',
 tutTrackerTitle:'Let TarkovTracker record your progress (optional)',tutTracker:'TarkovTracker is a free site that tracks task progress. Create a token with GP and WP under Settings → API Tokens, add it here, and accepted, completed and failed tasks are recorded automatically.',tutOpenTracker:'Open the TarkovTracker settings',
 tutDoneTitle:'All set',tutDone:'You can see this guide again under Settings → Appearance. Good raids.',
  // Tab list and updates
  allTabs:'All tabs',searchTabs:'Search tabs',tabsHint:'Every open tab, by name and address. Click one to switch to it, × to close it.',noTabResults:'No tabs match.',tabsClose:'Close tab',updateSection:'Updates',updateChannel:'Update channel',updateChannelStable:'Stable',updateChannelNightly:'Nightly (in development)',updateChannelHelp:'Nightly is built every day from the changes in development and may still have bugs. On nightly, a stable release that is newer is installed instead. Back on stable, a downloaded nightly is dropped and updates resume with the next stable release.',updateCurrent:'This version',updateLatest:'Latest version',updateCheck:'Check for updates',updateChecking:'Checking…',updateCheckedAt:'Last checked',updateUpToDate:'Up to date',updateNever:'Not checked yet',updateUnsupported:'No build for this platform',updateError:'Could not check',updateAutoNote:'Automatic updates are switched under Settings → Startup & window.',updateDownloading:'Downloading MAYAK {v}',updateReady:'MAYAK {v} is ready',updateRestart:'Restart to apply',updateDownload:'Download',updateLater:'Later',updateNotes:'What changed',updateReadyHint:'If you do not apply it now, it is installed when MAYAK next quits.',
  // Translate, sidebar, theme, ad blocking
  translatePage:'Translate this page (Google Translate)',translateOff:'Stop translating, back to the page itself',translateWiki:'Open the official wiki (English) translated',translateWikiHelp:'Task pages on the official wiki open through Google Translate (translate.goog). WebView2 has no page translation of its own, so this stands in for it. The translate button in the toolbar does the same for any page.',homeHelp:'Back to the start page',fixedAddress:'This view is fixed; its address cannot be edited',openExternal:'Open in default browser',closeSettings:'Close settings',collapseSection:'Collapse',expandSection:'Expand',groupHint:'Choose or type',resizeSidebar:'Drag to resize (double-click to reset)',allBookmarks:'All bookmarks',searchBookmarks:'Search bookmarks',gridView:'Tiles',listView:'List',pinToSidebar:'Pin to sidebar',unpinFromSidebar:'Remove from sidebar',bookmarkDropHint:'Drag bookmarks here to pin them',bookmarkDragHint:'Drag a bookmark onto “Bookmarks” in the sidebar to pin it there.',noBookmarkResults:'No bookmarks match.',collapseSidebar:'Close sidebar',expandSidebar:'Open sidebar',minimise:'Minimize',maximise:'Maximize',restore:'Restore',theme:'Theme',themeSystem:'Match system',adblock:'Ad blocking',adblockEnable:'Block ads and trackers',adblockHelp:'Blocks ads with EasyList, EasyPrivacy and the AdGuard Japanese filter, and closes the gaps they leave. The filter lists are published by EasyList (easylist.to) and AdGuard and update automatically. tarkov.dev is excluded because ads fund it. Changing this reloads the current page.',mapTab:'TARKOV.DEV',mapTabHelp:'tarkov.dev map, kept connected via Remote Control. Detected maps and positions appear here.',tabs:'Tabs',bookmarks:'Bookmarks',hostMode:'Host mode',clientMode:'Client mode',menuHint:'MAYAK menu',noTabs:'Open a website or settings from the logo menu.',
  // Status bar, settings sections, about
  tracker_connected:'synced',tracker_connecting:'connecting','tracker_waiting-profile':'waiting for profile','tracker_missing-token':'no API key',tracker_error:'error',tracker_disabled:'off',monitorOn:'Monitoring',monitorOff:'Not monitoring',monitorStart:'Click to start monitoring',monitorStop:'Click to stop monitoring',inRaid:'In raid',outRaid:'Out of raid',trackerLabel:'TarkovTracker',taskSiteHelp:'Where recognized tasks and tasks opened from the item sidebar open. Whether tasks go to tarkov.dev Remote Control is set per target under tarkov.dev link.',taskSiteClientHelp:'"Follow Host setting" opens the site chosen on the Host.',settingsBack:'Close settings',grpGeneral:'General',grpGame:'Game',grpLinks:'Connections',grpBrowser:'Browser',grpDiagnostics:'Status & diagnostics',sec_appearance:'Appearance',sec_tasks:'Opening tasks',sec_adblock:'Ad blocking',sec_connection:'Other computers',sec_status:'Status',sec_logs:'Logs',sec_folders:'Folders & storage',sec_recognition:'Game & recognition',sec_remote:'tarkov.dev link',sec_tracker:'TarkovTracker',sec_sounds:'Notifications',sec_startup:'Startup & window',sec_debug:'Debug',grpAbout:'About',sec_about:'About MAYAK',aboutVersion:'Version',aboutDev:'development build',aboutTagline:'A companion that turns Escape from Tarkov screenshots and logs into map, task and item information.',aboutSite:'Website',aboutSource:'GitHub',aboutReleases:'Changelog',aboutLicense:'Released under the GPL-3.0.',aboutCredits:'Maps come from tarkov.dev and task progress from TarkovTracker, through their data and APIs. Escape from Tarkov is a trademark of Battlestate Games; MAYAK is an unofficial tool.',
  // Layout and item panel
  placement:'Change the layout',navPosition:'Tabs position',itemDock:'Item details position',placeLeft:'Left',placeRight:'Right',placeTop:'Top',placeBottom:'Bottom',openItemPage:'Open the item page',itemSearch:'Search items',itemSearchHint:'Search by item name with the magnifier above, or inspect an item in the game and take a screenshot to see it here.',itemNoResults:'No items found',openTask:'Open task',itemPanel:'Item',itemShow:'Show item details',itemHide:'Close item details',itemRefresh:'Get the latest prices',itemLive:'LIVE',itemCatalog:'Catalog',itemPriced:'Prices updated',bestSale:'Sells best to',perSlot:'per slot',flea:'Flea market',fleaLow:'Lowest offer',fleaAvg:'24h average',fleaRange:'24h range',fleaChange:'48h change',fleaOffers:'Offers',fleaLevel:'Unlocks at level',noFlea:'Cannot be sold on the flea market',traders:'Trader buy prices',itemTasks:'Needed for tasks',itemHideout:'Needed for hideout',noNeeds:'None',fir:'FIR',needDone:'Done',progressUnknown:'Sync TarkovTracker to see what is done',
  // Price chart
  priceHistory:'Price history',range7d:'7D',range30d:'30D',rangeAll:'All',avgLine:'Average',minLine:'Lowest',chartHigh:'High',chartLow:'Low',chartLoading:'Loading price history…',chartFailed:'Could not load the price history',chartEmpty:'No history for this period',chartNow:'Now',
  // Popup window and api.js messages
  popupPin:'Pin (stays open when you click elsewhere)',popupUnpin:'Unpin',openInTab:'Open in a tab',openExternalBrowser:'Open in external browser',actionFailed:'Could not complete the action: ',enterWebURL:'Enter an http or https URL',
 },
};

// t returns key's text in language, falling back to Japanese, then the key.
export const t=(language,key)=>(words[language]||words.ja)[key]??key;
