// The strings of the browser shell, the item panel and the popup window, by
// language. Both languages carry the same keys (words.test.js); the settings
// page has its own typed table in ../i18n.ts.
export const words = {
  ja: {
    // The map view and its squad (view-map.js)
    liveMap: 'マップ',
    liveMapHelp: '脱出地点やスポーンなどと、分隊の仲間の位置を表示する地図',
    squad: '分隊',
    mapPen: '自分のペン（自分だけの線を描く。マップと階ごとに残ります）',
    mapPenHint: '左ドラッグで描く・右ドラッグかスペース + ドラッグで地図を動かす・Esc で終わる',
    mapPenHide: '自分の線を隠す',
    mapPenShow: '自分の線を表示',
    mapPenClear: 'この階の自分の線をすべて消す（元に戻せます）',
    mapPenDone: 'ペンを終える（Esc）',
    mapSquadPen: '分隊ペン（分隊の全員に見える線を、自分の分隊カラーで描く）',
    mapSquadPenJoin: '分隊ペン：分隊に入ると使えます',
    mapSquadPenRelay: '分隊ペン：中継サーバーが対応していません（押すと確かめ直します）',
    mapSquadPenHint:
      '左ドラッグで描く（描いている途中から分隊の全員に見えます）・右ドラッグかスペース + ドラッグで地図を動かす・Esc で終わる',
    mapSquadPenColor: 'あなたの分隊カラー（分隊ページで変えられます）',
    mapPenClearAll: 'このマップの分隊の線を全員分消す（数秒だけ元に戻せます）',
    mapPenClearAllShort: '全員分消す',
    mapClearedBy: '{name} がこのマップの分隊の線を消しました',
    mapClearedMine: 'このマップの分隊の線を消しました',
    mapClearedUndo: '元に戻す',
    mapPick: '表示するマップ',
    mapFloor: '階',
    mapAuto: '自動',
    mapGround: '地上',
    'floorBase_the-lab': 'First Level',
    floorBase_factory: '1st Floor',
    floorBase_interchange: '1st Floor',
    mapNone: '表示するマップがありません',
    mapStyle: '表示',
    mapMode: 'ゲームモード',
    gameModeNow: 'プレイ中のゲームモード',
    gameMode_regular: 'PvP',
    gameMode_pve: 'PvE',
    'gameMode_pvp-season': 'Season',
    mapStyleSvg: 'Abstract',
    mapStyleTile: 'Satellite',
    mapLoading: '地図を読み込み中…',
    mapDataFailed: '地図データを取得できませんでした',
    mapFloorHelp: '階（Ctrl + ホイールでも切り替え）',
    mapFilters: 'フィルター',
    mapSettings: '設定',
    mapSnap: 'スナップノートにする',
    squadFocus: 'マップでこの人を表示',
    squadRecent: '最近の分隊',
    squadRecentHint: '誰もいなくなった分隊はサーバーに残りません。同じコードでまた集まれます。',
    mapSnapFailed: 'マップを撮影できませんでした: ',
    mapSearch: '検索',
    mapSearchPlaceholder: 'タスク・アイテム・コンテナ…',
    mapSearchHint: 'カンマで区切ると複数を探せます（例: labs, ledx, bitcoin）',
    group_extracts: '脱出',
    group_hazards: '危険',
    group_landmarks: '目印',
    group_loose: '床置きの物資',
    group_containers: 'コンテナ',
    group_spawns: 'スポーン',
    group_tasks: 'タスク',
    group_usable: '設備',
    layer_extract_pmc: 'PMC',
    layer_extract_scav: 'Scav',
    layer_extract_shared: '共用',
    layer_extract_transit: 'トランジット',
    layer_hazard_minefield: '地雷原',
    layer_hazard_sniper: '狙撃 Scav',
    layer_hazard_mortar: '迫撃砲',
    layer_labels: '地名',
    layer_btr_stop: 'BTR の停留所',
    layer_spawn_pmc: 'PMC',
    layer_spawn_scav: 'Scav',
    layer_spawn_sniper_scav: '狙撃 Scav',
    layer_spawn_boss: 'ボス',
    layer_quest_item: 'アイテム',
    layer_quest_objective: '目的',
    layer_switch: 'スイッチ',
    layer_stationarygun: '固定機関銃',
    layer_lock: '鍵',
    settingSnipers: '狙撃 Scav のスポーンを常に表示',
    settingSnipersHint: '別の階を見ているときも薄くしません。フィルターで隠したときは表示しません',
    settingExtracts: '脱出地点を常に表示',
    settingExtractsHint: '別の階を見ているときも薄くしません。フィルターで隠したときは表示しません',
    settingActiveTasks: '進行中のタスクの印だけ表示',
    settingActiveTasksHint: 'TarkovTracker に接続しているときに使えます',
    settingSubtleLabels: '地名を目立たなくする',
    settingFade: '別の階の濃さ',
    settingExtractText: '脱出地点の名前の大きさ',
    settingLabelText: '地名の大きさ',
    popupTask: 'タスク',
    popupActivatedBy: '起動するスイッチ',
    popupActivates: '動かすもの',
    popupRequiredItem: '必要なアイテム',
    lockType_door: '扉',
    lockType_container: 'コンテナ',
    lockType_trunk: '車のドア・トランク',
    lockPower: '要電源',
    raidDuration: 'レイド時間',
    raidPlayers: '人数',
    minutes: '分',
    mapDataCredit: '地図と地点のデータ: tarkov.dev',
    mapBy: 'By:',
    squadUnavailable: 'マップはこのバージョンでは使えません（nightly 版で試験中）',
    squadIntro: '分隊コードを仲間と共有すると、レイド中にスクリーンショットを撮った位置が、全員の地図に表示されます。',
    squadName: '表示名',
    squadNamePlaceholder: '仲間に表示される名前',
    squadCode: '分隊コード',
    squadOpen: '分隊のページを開く',
    squadStart: '分隊を作る・参加する',
    squadMembers: 'メンバー',
    squadProfile: 'あなたのプロフィール',
    squadProfileHelp: '分隊の仲間に見える名前と色です。分隊を変えても同じものを使います。',
    squadJoinTitle: '分隊に入る',
    squadCreateHow:
      '自分で作るとき：押すと新しい分隊コードが発行され、そのまま分隊に入ります。このページに出るコードを仲間に伝えてください（コピーのボタンもあります）。',
    squadJoinHow:
      '仲間の分隊に入るとき：仲間から聞いた 8 文字の分隊コードを下に入れます（ハイフンは不要）。8 文字目でそのまま参加します。',
    squadJoined: '参加中の分隊',
    squadShares: '共有されたもの',
    squadSharesAll: 'すべて',
    squadSharesTabs: 'ページ',
    squadSharesDraw: '分隊ペン',
    squadSharesHint:
      'ページは、あとから入った人にも届きます。スナップノートは、送ったときにいた人だけに届きます。押すと開きます（スナップノートは自分のノートとして保存されます）。',
    squadSharesEmpty:
      'まだ何も共有されていません。ページはツールバーの分隊のボタン、スナップノートは共有のメニューから送れます。',
    squadDrew: '{map} に描きました',
    squadShareTab: 'このページを分隊に共有',
    squadShareDone: '分隊に共有しました',
    squadShareSnap: '分隊に共有',
    squadShareSnapHint: '書き込みごとの画像を、今いる分隊の仲間に送ります',
    squadShareSending: '分隊に送っています… {n}%',
    squadMemberUnread: 'この人から届いた、まだ見ていない共有',
    squadLookHere: '{map} にピン',
    squadSharesEveryone: '全員',
    squadSharesPeople: '共有した人で絞る',
    squadColorCustom: '好きな色を選ぶ',
    trackerCompletableCount: 'ゲームでは完了、TarkovTracker では未完了のタスクが {n} 件あります（押すと一覧）',
    trackerCompletableTitle: 'ゲームでは完了、TarkovTracker では未完了（押すと Completed にする）',
    trackerCompletableMore: 'ほか {n} 件',
    trackerCompletableAll: 'すべて Completed にする（{n} 件）',
    trackerCompletableClear: '一覧から外す（反映しない）',
    trackerCompletableSettings: 'TarkovTracker の設定を開く',
    snapFrom: '{name} から',
    snapEdit: '編集',
    snapEditDone: '完了',
    snapEditDoneHint: '編集を終えて、見るだけに戻す',
    squadCardLevel: 'レベル',
    squadCardRaids: 'レイド',
    squadCardKills: 'キル',
    squadCardSurvival: '生還率',
    squadCardKD: 'K/D',
    squadCardHours: 'プレイ時間',
    squadCardNone: 'まだ情報がありません（キャラクター画面の「全般」のスクリーンショットを撮ると出ます）',
    squadCardShares: 'この人が共有したものを見る',
    squadPictureShare: 'キャラクターの画像を分隊に見せる',
    squadPictureHint: 'キャラクター画面の「全般」のスクリーンショットを撮ると、左側の欄を分隊の仲間のカードに出します',
    squadCardMode: 'モード',
    squadCardTasks: '完了したタスク',
    squadCardProfile: 'TarkovTracker で見る',
    squadCardProfileHint: '本人が TarkovTracker でプロフィールの共有をオンにしていると見られます',
    squadMemberMore: 'この人が共有したこの種類のものをすべて見る',
    mapSquadFit: '分隊を自動で表示',
    mapSquadFitOn:
      '分隊を自動で表示する（誰かの位置が更新されたとき、自分の出撃マップなら、そこにいる分隊全員が入るように地図を合わせる）',
    mapSquadFitOff: '分隊の自動表示をやめる',
    settingShape: '矢印の形',
    settingShape_arrow: '矢じり',
    settingShape_tarkov: 'tarkov.dev',
    settingShape_dot: '丸と向き',
    settingMarker: '矢印のエフェクト',
    settingMarker_none: 'なし',
    settingMarker_outline: '縁取り',
    settingMarker_glow: '光彩',
    settingMarker_pulse: 'パルス',
    settingMarker_beacon: 'ビーコン',
    settingMarkerColor: 'エフェクトの色',
    settingMarkerAuto: 'それぞれの分隊カラー',
    squadSharesView: 'ピン',
    mapPin: 'ピンを刺す（地図を押した場所を分隊に見せる。やめるまで何度でも刺し直せます）',
    mapPinCancel: 'ピンを刺すのをやめる（Esc）',
    mapPinRemove: '自分のピンを抜く',
    mapPinDrag: 'ドラッグで動かせます',
    mapFresh: '分隊の仲間が新しく描きました',
    squadColor: '分隊カラー',
    squadColorAuto: '自動',
    squadColorTaken: '{name} が使っています',
    squadColorHelp:
      '地図の自分の印の色です。ほかの人が使っている色は選べません。自動にすると、空いている色になります。',
    squadColorBusy: '選んだ色はほかの人が使っているので、今は自動の色です。',
    squadCreate: '分隊を作る',
    squadJoin: '参加',
    squadLeave: '分隊を抜ける',
    squadLeaveQuick: '分隊から切断（2 回押す）',
    squadLeaveConfirm: 'もう一度押すと切断',
    squadShot: 'スクリーンショット',
    squadShotOn: '{map} のスクショ',
    squadSharesShots: 'スクショ',
    settingShotBubble: '位置にスクショを付ける',
    settingShotBubbleHint:
      '位置のスクショを、マップの自分の矢印の横に吹き出しで出します（押すと大きく）。分隊にいるときは仲間にも小さくして送ります（20 秒に 1 枚まで。同じスクショは二度送りません）',
    settingOpenOnRaid: 'レイド開始でマップを表示',
    settingOpenOnPosition: '位置スクショでマップを表示',
    squadShotSize: '大きい画像のサイズ',
    squadShotSizeHint: '手で共有したスクショと、仲間に頼まれた大きい画像をこの大きさで送ります',
    squadShotSizeFull: '元のまま',
    squadShotSize1080: '1080p',
    squadShotSize720: '720p',
    mapShotClose: '閉じる（枠の外を押しても閉じます）',
    squadShotLarge: '大きい画像を見る',
    squadShotLargeHint: '送った人に大きい画像を頼みます（その人がつながっているときだけ）',
    squadShotAsking: '頼んでいます…',
    squadShareShotHint: 'このスクショを大きい画像で分隊に送ります',
    squadShotSentAlready: 'このスクショはもう送っています',
    squadCopy: 'コードをコピー',
    squadCopied: 'コピーしました',
    squadPhase_connecting: '接続しています…',
    squadPhase_connected: '接続済み',
    squadPhase_offline: '中継に接続できません（自動で再試行します）',
    squadPhase_full: '分隊が満員です（10 人まで）',
    squadYou: 'あなた',
    squadOutOfRaid: 'レイド外',
    squadViewer:
      'この PC は Client なので、見るだけの参加です（位置は Host から送ります）。分隊の作成・参加・退出は Host と同期します。',
    squadPrivacy:
      '共有するのは表示名と分隊カラー、レイド中にスクリーンショットを撮った位置、分隊ペンの線とペンの位置だけです。内容は分隊コードで暗号化され、中継サーバーには読めません。',
    squadInvalidCode: '分隊コードは 8 文字です（例: ABCD-1234）',
    squadNeedName: '表示名を入力してください',
    // Toolbar, sidebar, welcome page, settings
    home: 'ホーム',
    settings: '設定',
    menu: 'メニュー',
    off: '受信OFF',
    back: '戻る',
    forward: '進む',
    reload: '再読み込み',
    address: 'URL または検索語を入力',
    open: '開く',
    close: '閉じる',
    pin: '固定',
    unpin: '固定解除',
    newTab: '新しいタブ',
    welcome: 'レイドの準備を、ここから。',
    intro: 'マップ、タスク、調べものを一つのウインドウに。',
    maps: 'マップ',
    tasks: 'タスク攻略',
    items: 'アイテム',
    progress: '進捗管理',
    other: 'その他',
    addBookmark: 'ブックマークを追加',
    edit: '編集',
    delete: '削除',
    name: '名前',
    url: 'URL',
    group: '分類',
    done: '確定',
    cancel: 'キャンセル',
    empty: 'ブックマークを追加して、よく使うサイトをまとめましょう。',
    client: 'ブラウザ設定',
    host: 'Host設定・ログ',
    appearance: '表示',
    language: '表示言語',
    layout: 'タブの配置',
    vertical: '左サイドバー',
    horizontal: '上部の横並び',
    recognition: 'タスクの自動表示',
    taskMode: '検出したタスクを開く方法',
    reuse: '同じタブを更新',
    new: '新しいタブを追加',
    questSite: '表示するサイト',
    hostChoice: 'Hostの設定に従う',
    official: '公式Wiki',
    japanese: '日本語Wiki',
    taskHelp:
      '表示中のタスクは、上のサイト選択で英語Wiki・日本語Wikiを切り替えられます。固定したタブは自動更新の対象外です。',
    connection: 'Host接続',
    mode: '接続方法',
    local: 'Host：このPCでタルコフを起動する',
    localHelp:
      'Escape from Tarkov を遊ぶPCで選びます。スクショやログから検出したタスク・マップ・アイテムをこのPCのタブに出し、つないだ別のPCにも送ります。',
    clientHelp:
      'Escape from Tarkov は別のPC（Host）で遊び、そのPCの MAYAK が検出したものをこのPCに出します。下で Host とつないでください。',
    bookmarkHelp: 'カードをクリックして開く。名前と分類は編集できます。',
    tabHelp: 'ドラッグで順序変更',
    dismiss: '閉じる',
    searchWiki: 'Wiki内で検索',
    pinHelp: '固定中',
    // Bosses, Goons reports, clock, screenshots
    bossMapBosses: 'マップのボス',
    goonReport: 'Goons を報告',
    goonReportOnly:
      '実際に Goons に遭遇したレイドだけ報告してください。報告は tarkov.dev に表示される目撃情報に加わります。',
    goonAccount: '報告するアカウント（EFT のログから）',
    goonNoAccount: 'EFT のログにアカウントが見つかりません。一度ゲームを起動してください。',
    goonWhen: 'いつ見たか',
    goonRaidNow: '今のレイド',
    goonRaidLast: '直前のレイド',
    goonStarted: '開始',
    goonAlready: '報告済み',
    goonWhenNow: '今の時刻で報告',
    goonConsent:
      'tarkov.dev は、報告と一緒にあなたの IP アドレスと選んだ EFT アカウント ID を保存します（不正な報告を追跡するため）。',
    goonSend: '報告する',
    goonSending: '送信中…',
    goonReported: '報告しました。tarkov.dev の目撃情報に反映されるまで最大10分ほどかかります。',
    goonCurrent: 'プレイ中',
    goonLastSeen: '最終',
    bossAuto: '自動',
    bossModeLabel: 'ゲームモード',
    bossPickHint: 'マップを選ぶか、レイドに入るとボスを表示します',
    clockFormat: '時刻の表示',
    clock24: '24時間表示（13:05）',
    clock12: '12時間表示（1:05 PM）',
    shotKind_tasks: 'タスク',
    shotKind_item: 'アイテム',
    shotKind_offer: '出品',
    shotKind_position: '位置',
    shotKind_unknown: '判定なし',
    shotInfo: '判定の詳細',
    shotInfoKind: '種類',
    shotInfoMatch: '一致',
    shotInfoConfidence: '一致度',
    shotInfoCandidates: '候補',
    shotInfoLayout: '画面の形',
    shotInfoScore: '検出スコア',
    shotInfoMap: 'マップ',
    shotInfoRaid: 'レイド中',
    shotInfoPosition: '座標',
    shotInfoStage: '状態',
    shotInfoError: 'エラー',
    yes: 'はい',
    no: 'いいえ',
    bosses: 'ボス',
    allBosses: 'ボスの詳細',
    bossesLoading: 'ボス情報を読み込み中…',
    noGoons: '最近の報告なし',
    noBosses: 'ボスは出ません',
    escorts: '取り巻き',
    goonHint:
      'Goons の位置はプレイヤーの報告（tarkov.dev）です。報告が新しいほど、今もそのマップにいる可能性が高くなります。',
    goonMaps: 'Goons が出るマップ',
    bossMaps: 'マップ',
    zoomIn: '拡大',
    zoomOut: '縮小',
    zoomFit: '全体を表示（リセット）',
    screenshots: 'スクリーンショット',
    allScreenshots: 'すべてのスクリーンショット',
    noScreenshots: 'スクリーンショットはまだありません',
    screenshotsHostOnly: 'スクリーンショットはHostのPCで見られます',
    openScreenshotFolder: 'フォルダを開く',
    newerScreenshot: '新しい方へ',
    olderScreenshot: '古い方へ',
    clientConnection: 'Client：タルコフは別のPC（Host）で起動する',
    p2pTitle: '別の PC へ送る',
    p2pReceive: 'Host とつなぐ',
    p2pHelp:
      'Host と相手の PC で MAYAK を開き、Host に出る 8 桁の接続コードを相手の PC で入力します。Host には何台でもつなげます（1 台ずつコードを発行）。一度つないだ PC はペアを覚えていて、次からは起動するだけで自動でつながります。やりとりはペアの PC だけが持つ鍵で暗号化して中継サーバー（mayak-relay.ich.sh）を通すので、中継サーバーには中身が読めません。',
    pairCodeHelp:
      '相手の PC の MAYAK で 設定 → 接続 を開き、Client にしてこの番号を入力してください。10 分で失効します。',
    enterPairCode: 'Host に表示された 8 桁の接続コード',
    joinPair: '接続する',
    manualExchange: 'コードを手で渡す（mayak.ich.sh を使わない）',
    manualExchangeHelp: 'mayak.ich.sh を経由したくないときは、この長いコードを相手の PC にコピーして渡します。',
    relayFailed: '接続コードのサーバー（mayak.ich.sh）に届きませんでした。下の長いコードを手で渡してください。',
    p2pLimit:
      '送られるのは Host が検出したタスク・マップ・位置・アイテムと、参加中の分隊だけです。Host で解除するとつないだ PC すべてがペアを忘れ、Client で解除するとその PC だけが外れます。',
    createInvite: '接続コードを発行',
    inviteCode: '招待コード',
    copyCode: 'コードをコピー',
    peerHostName: 'Host の PC',
    peerClientNames: 'つながっている PC',
    peerSelfName: 'この PC',
    copied: 'コピーしました',
    showCode: 'コードを表示',
    hideCode: 'コードを隠す',
    enterOffer: 'Host の長い招待コードを貼り付け',
    acceptInvite: '接続する',
    unpairPeer: 'この PC のペアリングを解除',
    cancelPairing: 'キャンセル',
    linkIdle: 'ペアリングしていません',
    linkConnecting: '中継サーバーに接続しています…',
    linkWaitingHost: 'Host を待っています（Host の MAYAK が起動していないか、つながっていません）',
    linkWaitingClient: '相手の PC を待っています',
    linkConnected: '接続中',
    linkConnectedCount: '{n} 台の PC と接続中',
    addPeer: '別の PC を追加（接続コードを発行）',
    unpairAll: 'すべての PC とのペアリングを解除',
    linkReceive: 'この PC に出すもの',
    linkReceive_task: 'タスク',
    linkReceive_map: 'マップと位置',
    linkReceive_item: 'アイテム',
    linkReceiveHelp:
      'Host が検出したもののうち、この PC で開くものを選びます（1 台はマップ、もう 1 台はタスク、のように分けられます）。',
    linkOffline: '中継サーバーに届きません。自動でつなぎ直します…',
    linkFailed: '接続できませんでした。',
    p2pExpired: '接続コードの有効期限が切れました。',
    // Tutorial
    tutorialShow: 'チュートリアルを表示',
    tutorialShowHelp: '初回起動時の案内（フォルダ、スクリーンショットキー、マップ、TarkovTracker）をもう一度見ます。',
    tutStep: 'ステップ',
    tutStart: 'はじめる',
    tutLater: 'あとで',
    tutNext: '次へ',
    tutBack: '戻る',
    tutSkip: 'スキップ',
    tutFinish: '完了',
    tutWelcomeTitle: 'MAYAK へようこそ',
    tutWelcome:
      'ゲーム内で撮影したスクリーンショットとログを読むだけで、マップ・タスク・アイテム情報をこのウインドウに映します。ゲーム本体には触れません。この案内に沿って進めれば、準備は数分で終わります。',
    tutFoldersTitle: 'EFT のフォルダ',
    tutFolders: 'スクリーンショットとログのフォルダを自動で探しました。違っていれば設定で選び直せます。',
    tutFoldersScreens: 'スクリーンショット',
    tutFoldersLogs: 'ログ',
    tutNotFound: '未検出。設定で選んでください',
    tutOpenFolders: 'フォルダの設定を開く',
    tutKeyTitle: 'スクリーンショットキーを押しやすい場所に',
    tutKey:
      'EFT の Settings → Controls → Screenshot。既定は PrintScreen ですが戦闘中に届きにくいので、マウスのサイドボタンや左手で届く空きキーへの割り当てをおすすめします。',
    tutKeyNote:
      '座標が入るのは EFT 自身のスクリーンショット機能で保存したファイルだけです。Steam や Windows のスクリーンショットは対象外です。',
    tutMapTitle: 'レイド中はそのキーを押すだけ',
    tutMap:
      'このウインドウのマップタブは、設定なしで現在地に追従します。タスク一覧で該当のタスクを開いた状態か、アイテム詳細を撮れば、それぞれの情報も表示されます（一覧だけの画面ではどのタスクか分かりません）。1 台の PC でマルチモニタなら、これで完結です。',
    tutOpenMap: 'マップを開く',
    tutRemoteTitle: '別の PC や普段のブラウザで見るなら（任意）',
    tutRemote:
      'そのブラウザで tarkov.dev のマップを開き、左下の接続ボタンを押します。同じ PC の Chrome / Edge / Brave なら Remote ID は自動検出、別の PC やタブレットなら ID を入力します。別の PC で MAYAK 自体を動かすなら、設定 → 他のPCとの接続 の 8 桁の接続コードで繋がります。',
    tutOpenRemote: 'tarkov.dev 連携の設定を開く',
    tutTrackerTitle: 'TarkovTracker で進捗を自動記録（任意）',
    tutTracker:
      'TarkovTracker はタスクの進捗を管理できる無料のサイトです。Settings → API Tokens で GP と WP を付けたトークンを作って取り込むと、受注・完了・失敗が自動で反映されます。',
    tutOpenTracker: 'TarkovTracker の設定を開く',
    tutDoneTitle: '準備完了',
    tutDone: 'この案内は 設定 → 表示 からいつでも見直せます。良いレイドを。',
    tutSupport:
      'MAYAK は無料です。気に入ったら、Buy Me a Coffee で開発を応援してもらえるとうれしいです（設定 → MAYAK について からも開けます）。',
    // Tab list and updates
    allTabs: 'すべてのタブ',
    searchTabs: 'タブを検索',
    tabsHint: '開いているタブを名前とアドレスで探せます。クリックで切り替え、× で閉じます。',
    noTabResults: '一致するタブはありません。',
    tabsClose: 'タブを閉じる',
    snapNotes: 'スナップノート',
    snapFromShot: 'スナップノートにする',
    snapFromShotHelp: 'このスクリーンショットを単独のスナップノートにして、書き込みを始めます',
    snapNotesAll: 'すべてのスナップノート',
    snapTake: 'スナップノート（このページを撮って書き込む）',
    snapVisible: '見えている範囲を撮る',
    snapVisibleHint: '今ウインドウに見えている部分',
    snapFull: 'ページ全体を撮る',
    snapFullHint: '下までスクロールする長いページも 1 枚に（高さ 15000px まで）',
    snapThisPage: 'このページのノート',
    snapShowAll: 'すべてのスナップノートを開く',
    snapCapturing: '撮影しています…',
    snapCaptureFailed: 'ページを撮影できませんでした: ',
    snapEmpty:
      'スナップノートはまだありません。ページを開いてツールバーのペンのボタンから撮るか、白紙や画像から作れます。',
    snapNewBlank: '白紙から作る',
    snapNewImage: '画像ファイルから作る',
    snapPasteHint: 'Ctrl+V で、クリップボードの画像からも作れます。',
    snapFilterAll: 'すべて',
    snapFilterLinked: 'ページのノート',
    snapFilterSingle: '単独のノート',
    snapFilterFavorite: 'お気に入り',
    snapFavorite: 'お気に入りにする',
    snapUnfavorite: 'お気に入りから外す',
    snapTitlePlaceholder: 'ノートの名前',
    snapRename: '名前を変更',
    snapNoMatch: 'この条件のノートはありません。',
    snapSingle: '単独',
    snapBack: '一覧に戻る',
    snapTitle: 'タイトル',
    snapPen: 'ペン',
    snapEraser: '消しゴム（線ごと消す）',
    snapText: '文字（クリックで入力、文字をクリックで編集、ドラッグで移動）',
    snapTextHint: '枠の外をクリックで確定。Enter で改行',
    snapTexts: '文字 {n}',
    snapTextSize: '文字の大きさ',
    snapFont: 'フォント',
    snapSpot: '撮った場所',
    snapFacing: '向き',
    snapShowSpot: 'tarkov.dev で位置を表示',
    snapShowSpotHint: '地図タブ（とリモート接続した地図）に、撮った位置と向きを表示します',
    snapPickMap: 'マップを選ぶ',
    snapPickMapHint: 'このスクショのマップが分かりませんでした。選ぶと地図に表示できます',
    snapSpotShown: '地図に位置を表示しました',
    snapFontDefault: '標準',
    snapOutline: '縁',
    snapOutlineAuto: '自動',
    snapOutlineAutoHint: '文字の色に合わせて白か黒',
    snapOutlineColor: '縁の色',
    snapOutlineWidth: '縁の太さ',
    snapMoreColors: 'その他の色',
    snapTextMove: 'ドラッグで移動',
    snapShare: '共有',
    snapCopyImage: '画像をコピー',
    snapCopyImageHint: '描き込みごとクリップボードへ',
    snapSaveAs: '名前を付けて保存',
    snapSaveAsHint: 'PNG 画像として保存',
    snapPostX: 'X に投稿',
    snapPostXHint: '画像をコピーして、X の投稿画面をブラウザで開きます',
    snapCopied: 'コピーしました',
    snapExported: '保存しました',
    snapPostXReady: '画像をコピーしました',
    snapPostXPaste: 'ブラウザで開く X の投稿欄で Ctrl+V を押すと、画像を貼り付けられます。',
    snapPostXOpening: 'まもなく X を開きます…',
    snapShareFailed: 'できませんでした',
    snapUndo: '元に戻す（Ctrl+Z）',
    snapRedo: 'やり直す（Ctrl+Y）',
    snapClear: 'このレイヤーの線をすべて消す',
    snapLayers: 'レイヤー',
    snapLayer: 'レイヤー {n}',
    snapLines: '{n} 本',
    snapLayerClear: 'このレイヤーの線を消す',
    snapOriginal: '元の画像',
    snapAdjust: '見やすさの調整',
    snapAdjustReset: '元に戻す',
    snapBrightness: '明るさ',
    snapContrast: 'コントラスト',
    snapShadows: '暗部を明るく',
    snapAdjustHint: '表示だけを変えます。元の画像は変わりません。',
    snapOriginalHint: '編集はされません',
    snapHide: '非表示にする',
    snapShow: '表示する',
    snapSizeS: '細い線',
    snapSizeM: '普通の線',
    snapSizeL: '太い線',
    snapFit: '幅に合わせる（Ctrl+0）',
    snapActual: '100% で表示',
    snapZoomIn: '拡大（Ctrl+ホイール、Ctrl++）',
    snapZoomOut: '縮小（Ctrl+ホイール、Ctrl+-）',
    snapOpenPage: '元のページを開く',
    snapUnlink: 'ページとの紐付けを外す',
    snapRelink: '元のページに紐付け直す',
    snapDelete: '削除',
    snapDeleteConfirm: 'もう一度押すと削除',
    snapSaved: '保存済み',
    snapSaveFailed: '保存できませんでした',
    snapSaving: '保存中…',
    snapLinked: 'このページのノート',
    snapUnlinked: '紐付けを外したノート',
    snapNoPage: '単独のノート',
    snapColor: '色',
    updateSection: 'アップデート',
    updateChannel: '使用するバージョン（更新チャンネル）',
    updateChannelStable: '安定版',
    updateChannelStableHelp: '正式リリースのバージョンだけに更新します。通常はこちら。',
    updateChannelNightly: 'nightly',
    updateChannelNightlyHelp:
      '開発中の変更を毎日ビルドしたバージョンにも更新します。新機能を早く試せますが、不具合が残っていることがあります。',
    updateChannelHelp:
      'nightly を選んでいても、安定版の方が新しければ安定版に更新します。安定版に戻すと、ダウンロード済みの nightly は破棄し、次の安定版が出たときに更新します（今のバージョンから戻すことはしません）。',
    updateCurrent: '現在の版',
    updateLatest: '最新の版',
    updateCheck: '更新を確認',
    updateChecking: '確認しています…',
    updateCheckedAt: '最終確認',
    updateUpToDate: '最新の版です',
    updateNever: 'まだ確認していません',
    updateUnsupported: 'このプラットフォーム向けのビルドがありません',
    updateError: '確認できませんでした',
    updateAutoNote: '自動更新は 設定 → 起動とウィンドウ で切り替えられます。',
    updateDownloading: 'MAYAK {v} をダウンロード中',
    updateReady: 'MAYAK {v} の準備ができました',
    updateRestart: '再起動して適用',
    updateDownload: 'ダウンロード',
    updateLater: 'あとで',
    updateNotes: '変更点',
    updateReadyHint: 'いま適用しなくても、次に MAYAK を終了したときに入れ替わります。',
    // Translate, sidebar, theme, ad blocking
    translatePage: 'このページを翻訳（Google 翻訳）',
    translateOff: '翻訳をやめて元のページに戻る',
    translateWiki: '公式 Wiki（英語）を翻訳して開く',
    translateWikiHelp:
      'タスクの検出で開く公式 Wiki のページを、Google 翻訳（translate.goog）経由で表示します。Chrome の「ページを翻訳」は WebView2 に無いため、その代わりです。ツールバーの翻訳ボタンでどのページでも同じことができます。',
    homeHelp: '最初のページに戻る',
    fixedAddress: '固定表示のためアドレスは変更できません',
    openExternal: '既定のブラウザで開く',
    closeSettings: '設定を閉じる',
    devInstance: '開発版（task dev）。データは Mayak-dev に分かれていて、入れてある MAYAK と同時に動かせます',
    collapseSection: '折りたたむ',
    expandSection: '展開する',
    groupHint: '選ぶか入力',
    resizeSidebar: 'ドラッグで幅を変更（ダブルクリックで元に戻す）',
    allBookmarks: 'すべてのブックマーク',
    searchBookmarks: 'ブックマークを検索',
    gridView: 'タイル表示',
    listView: 'リスト表示',
    pinToSidebar: 'サイドバーにピン留め',
    unpinFromSidebar: 'サイドバーから外す',
    bookmarkDropHint: 'ブックマークをここへドラッグしてピン留め',
    bookmarkDragHint: 'サイドバーの「ブックマーク」へドラッグすると、サイドバーにピン留めできます。',
    noBookmarkResults: '一致するブックマークはありません。',
    collapseSidebar: 'サイドバーを閉じる',
    expandSidebar: 'サイドバーを開く',
    minimise: '最小化',
    maximise: '最大化',
    restore: '元に戻す',
    theme: 'テーマ',
    themeSystem: 'システムに合わせる',
    adblock: '広告ブロック',
    adblockEnable: '広告とトラッカーをブロックする',
    adblockHelp:
      'EasyList・EasyPrivacy・AdGuard日本語フィルタで広告を止め、広告があった場所の空欄も詰めます。フィルタは EasyList（easylist.to）と AdGuard が公開しているリストで、自動で更新されます。tarkov.dev は広告で運営されているため対象外です。切り替えると表示中のページを再読み込みします。',
    mapTab: 'TARKOV.DEV',
    mapTabHelp: 'tarkov.dev のマップ。Remote Control で接続済みのまま、検出したマップと位置を表示します。',
    tabs: 'タブ',
    bookmarks: 'ブックマーク',
    hostMode: 'Hostモード',
    clientMode: 'Clientモード',
    menuHint: 'MAYAK メニュー',
    noTabs: 'ロゴのメニューからサイトや設定を開けます。',
    // Status bar, settings sections, about
    tracker_connected: '同期中',
    tracker_connecting: '接続中',
    'tracker_waiting-profile': 'プロフィール待ち',
    'tracker_missing-token': 'APIキー未設定',
    tracker_error: 'エラー',
    tracker_disabled: 'オフ',
    monitorOn: '監視中',
    monitorOff: '監視停止中',
    monitorStart: 'クリックで監視を開始',
    monitorStop: 'クリックで監視を停止',
    inRaid: 'レイド中',
    outRaid: 'レイド外',
    trackerLabel: 'TarkovTracker',
    taskSiteHelp:
      'タスクを認識したときと、アイテム情報からタスクを開くときのサイトです。tarkov.dev の Remote Control へ送るかどうかは「tarkov.dev 連携」の接続先ごとに選べます。',
    taskSiteClientHelp: '「Hostの設定に従う」にすると、Host側で選んだサイトで開きます。',
    settingsBack: '設定を閉じる',
    grpGeneral: '一般',
    grpGame: 'ゲーム',
    grpLinks: '連携',
    grpBrowser: 'ブラウザ',
    grpDiagnostics: '状態と診断',
    sec_appearance: '表示',
    sec_tasks: 'タスクの開き方',
    sec_adblock: '広告ブロック',
    sec_connection: '他のPCとの接続',
    sec_status: 'ステータス',
    sec_logs: 'ログ',
    sec_folders: 'フォルダと保存',
    sec_recognition: 'ゲームと認識',
    sec_remote: 'tarkov.dev 連携',
    sec_tracker: 'TarkovTracker',
    sec_sounds: '通知',
    sec_startup: '起動とウィンドウ',
    sec_debug: 'デバッグ',
    grpAbout: '情報',
    sec_about: 'MAYAK について',
    sec_licenses: 'ライセンスとクレジット',
    licLicense: 'ライセンス全文',
    licNotices: 'サードパーティのライセンス',
    licNoticesHelp:
      '同梱しているライブラリや OCR データのライセンスは、MAYAK と同じフォルダの THIRD_PARTY_NOTICES.txt にあります。',
    licData: 'データ',
    licVoices: '組み込み音声',
    licVoicesNote:
      '通知の声は、日本語を VOICEVOX、英語を Kokoro-82M（Apache-2.0）で作りました。MAYAK の GPL-3.0 の対象外で、それぞれの利用規約に従います。音声ファイルを取り出して再配布しないでください。',
    licTerms: '利用規約',
    licChecked: '規約の確認日',
    licVoicevoxTerms: 'VOICEVOX 利用規約',
    aboutVersion: 'バージョン',
    aboutDev: '開発ビルド',
    aboutTagline: 'Escape from Tarkov のスクリーンショットとログから、マップ・タスク・アイテム情報を映すコンパニオン。',
    aboutSite: '公式サイト',
    aboutSource: 'GitHub',
    aboutReleases: '変更履歴',
    aboutSupport: 'Buy Me a Coffee で応援',
    aboutSupportTitle: 'MAYAK の開発を応援する',
    aboutSupportHint:
      'MAYAK は無料で、個人で開発しています。役に立ったら、コーヒー 1 杯分の応援をもらえると開発の励みになります。',
    aboutLicense: 'GPL-3.0 で公開しています。',
    aboutCredits:
      'マップは tarkov.dev、タスクの進捗は TarkovTracker のデータと API を使っています。Escape from Tarkov は Battlestate Games の商標で、MAYAK は非公式のツールです。',
    // Layout and item panel
    placement: '配置を変更',
    navPosition: 'タブの位置',
    itemDock: 'アイテム情報の位置',
    placeLeft: '左',
    placeRight: '右',
    placeTop: '上',
    placeBottom: '下',
    openItemPage: 'アイテムのページを開く',
    itemSearch: 'アイテムを検索',
    itemSearchHint:
      '上のルーペからアイテム名で検索できます。ゲームでアイテムを調べてスクショを撮っても、ここに情報が出ます。',
    itemNoResults: '見つかりませんでした',
    openTask: 'タスクを開く',
    itemPanel: 'アイテム情報',
    itemShow: 'アイテム情報を表示',
    itemHide: 'アイテム情報を閉じる',
    itemRefresh: '最新の価格を取得',
    itemLive: 'LIVE',
    itemCatalog: 'カタログ',
    itemPriced: '価格更新',
    bestSale: '一番高く売れるのは',
    perSlot: '1マス',
    flea: 'フリーマーケット',
    fleaLow: '最安値',
    fleaAvg: '24時間平均',
    fleaRange: '24時間の幅',
    fleaChange: '48時間の変動',
    fleaOffers: '出品数',
    fleaLevel: '利用可能レベル',
    noFlea: 'フリーマーケットでは売れません',
    traders: 'トレーダー買取',
    itemTasks: '必要なタスク',
    itemHideout: '必要なハイドアウト',
    itemLocks: '使う場所',
    itemLockCount: '%d か所',
    itemLockSpot: '場所 %d',
    itemLockShowAll: 'このマップの場所をすべて表示',
    itemLockShow: 'マップで場所を表示',
    noNeeds: 'なし',
    fir: 'FIR',
    needDone: '完了',
    progressUnknown: 'TarkovTrackerと同期すると完了済みがわかります',
    // Price chart
    priceHistory: '価格の推移',
    range7d: '7日',
    range30d: '30日',
    rangeAll: '全期間',
    avgLine: '平均',
    minLine: '最安値',
    chartHigh: '最高',
    chartLow: '最安',
    chartLoading: '価格の履歴を読み込み中…',
    chartFailed: '価格の履歴を取得できませんでした',
    chartEmpty: 'この期間の履歴はありません',
    chartNow: '現在',
    // Popup window and api.js messages
    popupPin: 'ピン留め (ほかをクリックしても閉じない)',
    popupUnpin: 'ピン留めを外す',
    openInTab: 'タブで開く',
    openExternalBrowser: '外部ブラウザで開く',
    actionFailed: '操作を完了できませんでした: ',
    enterWebURL: 'http / https のURLを入力してください',
  },
  en: {
    // The map view and its squad (view-map.js)
    liveMap: 'Map',
    liveMapHelp: 'A map with extracts, spawns and more, and where your squadmates are',
    squad: 'Squad',
    mapPen: 'Your pen (lines for you only, kept by map and floor)',
    mapPenHint: 'Drag to draw; right-drag or Space + drag moves the map; Esc puts the pen down',
    mapPenHide: 'Hide your lines',
    mapPenShow: 'Show your lines',
    mapPenClear: 'Remove all your lines on this floor (can be undone)',
    mapPenDone: 'Put the pen down (Esc)',
    mapSquadPen: 'Squad pen (lines the whole squad sees, in your squad colour)',
    mapSquadPenJoin: 'Squad pen: join a squad to use it',
    mapSquadPenRelay: 'Squad pen: the relay does not take it (press to ask again)',
    mapSquadPenHint:
      'Drag to draw (the squad sees it as you draw); right-drag or Space + drag moves the map; Esc puts the pen down',
    mapSquadPenColor: 'Your squad colour (changed on the squad page)',
    mapPenClearAll: "Remove everyone's squad lines on this map (can be undone for a few seconds)",
    mapPenClearAllShort: 'Clear all',
    mapClearedBy: "{name} removed the squad's lines on this map",
    mapClearedMine: "You removed the squad's lines on this map",
    mapClearedUndo: 'Undo',
    mapPick: 'Map shown',
    mapFloor: 'Floor',
    mapAuto: 'Auto',
    mapGround: 'Ground',
    'floorBase_the-lab': 'First Level',
    floorBase_factory: '1st Floor',
    floorBase_interchange: '1st Floor',
    mapNone: 'No map to show',
    mapStyle: 'Style',
    mapMode: 'Game mode',
    gameModeNow: 'Game mode being played',
    gameMode_regular: 'PvP',
    gameMode_pve: 'PvE',
    'gameMode_pvp-season': 'Season',
    mapStyleSvg: 'Abstract',
    mapStyleTile: 'Satellite',
    mapLoading: 'Loading the maps…',
    mapDataFailed: 'Could not get the map data',
    mapFloorHelp: 'Floor (Ctrl + wheel changes it too)',
    mapFilters: 'Filters',
    mapSettings: 'Settings',
    mapSnap: 'Make a snap note',
    squadFocus: 'Show them on the map',
    squadRecent: 'Recent squads',
    squadRecentHint: 'A squad no one is in is not kept on the server; the same code brings everyone together again.',
    mapSnapFailed: 'Could not capture the map: ',
    mapSearch: 'Search',
    mapSearchPlaceholder: 'Task, item or container…',
    mapSearchHint: "Commas search for several (e.g. 'labs, ledx, bitcoin')",
    group_extracts: 'Extracts',
    group_hazards: 'Hazards',
    group_landmarks: 'Landmarks',
    group_loose: 'Loose loot',
    group_containers: 'Lootable items',
    group_spawns: 'Spawns',
    group_tasks: 'Tasks',
    group_usable: 'Usable',
    layer_extract_pmc: 'PMC',
    layer_extract_scav: 'Scav',
    layer_extract_shared: 'Shared',
    layer_extract_transit: 'Transit',
    layer_hazard_minefield: 'Minefield',
    layer_hazard_sniper: 'Sniper',
    layer_hazard_mortar: 'Mortar',
    layer_labels: 'Place names',
    layer_btr_stop: 'BTR stop',
    layer_spawn_pmc: 'PMC',
    layer_spawn_scav: 'Scav',
    layer_spawn_sniper_scav: 'Sniper Scav',
    layer_spawn_boss: 'Boss',
    layer_quest_item: 'Item',
    layer_quest_objective: 'Objective',
    layer_switch: 'Switch',
    layer_stationarygun: 'Stationary gun',
    layer_lock: 'Locks',
    settingSnipers: 'Always show sniper spawns',
    settingSnipersHint: 'Not faded while another floor shows; hidden when the filters hide them',
    settingExtracts: 'Always show extracts',
    settingExtractsHint: 'Not faded while another floor shows; hidden when the filters hide them',
    settingActiveTasks: 'Only show markers for active tasks',
    settingActiveTasksHint: 'With TarkovTracker connected',
    settingSubtleLabels: 'Make place names faint',
    settingFade: 'Strength of other floors',
    settingExtractText: 'Size of extract names',
    settingLabelText: 'Size of place names',
    popupTask: 'Task',
    popupActivatedBy: 'Activated by',
    popupActivates: 'Activates',
    popupRequiredItem: 'Required item',
    lockType_door: 'Door',
    lockType_container: 'Container',
    lockType_trunk: 'Car door or trunk',
    lockPower: 'needs power',
    raidDuration: 'Duration',
    raidPlayers: 'Players',
    minutes: 'min',
    mapDataCredit: 'Map and marker data: tarkov.dev',
    mapBy: 'By:',
    squadUnavailable: 'The map is not available in this version (being tried in the nightly build)',
    squadIntro:
      'Share a squad code with your squadmates: where each of you takes a screenshot in a raid shows on everyone’s map.',
    squadName: 'Display name',
    squadNamePlaceholder: 'The name your squad sees',
    squadCode: 'Squad code',
    squadOpen: 'Open the squad page',
    squadStart: 'Create or join a squad',
    squadMembers: 'Members',
    squadProfile: 'Your profile',
    squadProfileHelp: 'The name and colour your squad sees; they stay the same from squad to squad.',
    squadJoinTitle: 'Join a squad',
    squadCreateHow:
      'To make one: press it for a new squad code, and you are in the squad. Tell your squadmates the code this page shows (it has a copy button).',
    squadJoinHow:
      'To join a squadmate’s: type the 8-character squad code they gave you below (no hyphen needed); the 8th character joins.',
    squadJoined: 'Your squad',
    squadShares: 'Shared',
    squadSharesAll: 'All',
    squadSharesTabs: 'Pages',
    squadSharesDraw: 'Squad pen',
    squadSharesHint:
      'A page also reaches those who join later; a snap note only those there when it was sent. Press one to open it (a snap note is kept as a note of your own).',
    squadSharesEmpty:
      'Nothing shared yet. Share a page with the squad button in the toolbar, a snap note from its share menu.',
    squadDrew: 'drew on {map}',
    squadShareTab: 'Share this page with the squad',
    squadShareDone: 'Shared with the squad',
    squadShareSnap: 'Share with the squad',
    squadShareSnapHint: 'Sends the picture as drawn to the squad there now',
    squadShareSending: 'Sending to the squad… {n}%',
    squadMemberUnread: 'Shared by them and not seen yet',
    squadLookHere: 'A pin on {map}',
    squadSharesEveryone: 'Everyone',
    squadSharesPeople: 'Filter by who shared',
    squadColorCustom: 'Pick any colour',
    trackerCompletableCount: '{n} task(s) done in the game are not completed on TarkovTracker (press to list them)',
    trackerCompletableTitle: 'Done in the game, not on TarkovTracker (choose one to complete it)',
    trackerCompletableMore: '{n} more',
    trackerCompletableAll: 'Complete them all ({n})',
    trackerCompletableClear: 'Clear the list (without applying)',
    trackerCompletableSettings: 'Open the TarkovTracker settings',
    snapFrom: 'From {name}',
    snapEdit: 'Edit',
    snapEditDone: 'Done',
    snapEditDoneHint: 'Stop editing and go back to viewing',
    squadCardLevel: 'Level',
    squadCardRaids: 'Raids',
    squadCardKills: 'Kills',
    squadCardSurvival: 'Survival rate',
    squadCardKD: 'K/D',
    squadCardHours: 'Time played',
    squadCardNone: 'Nothing yet (a screenshot of the character screen’s Overall tab brings it)',
    squadCardShares: 'See what they shared',
    squadPictureShare: 'Show my character’s picture to the squad',
    squadPictureHint:
      'A screenshot of the character screen’s Overall tab puts its left panel on your card for the squad',
    squadCardMode: 'Mode',
    squadCardTasks: 'Tasks completed',
    squadCardProfile: 'View on TarkovTracker',
    squadCardProfileHint: 'Shows when they share their profile on TarkovTracker',
    squadMemberMore: 'See all of this kind they shared',
    mapSquadFit: 'Follow the squad',
    mapSquadFitOn:
      'Follow the squad (when someone’s position updates on your raid’s map, the map takes in everyone there)',
    mapSquadFitOff: 'Stop following the squad',
    settingShape: 'Arrow shape',
    settingShape_arrow: 'Arrowhead',
    settingShape_tarkov: 'tarkov.dev',
    settingShape_dot: 'Dot and cone',
    settingMarker: 'Effect on the arrows',
    settingMarker_none: 'None',
    settingMarker_outline: 'Outline',
    settingMarker_glow: 'Glow',
    settingMarker_pulse: 'Pulse',
    settingMarker_beacon: 'Beacon',
    settingMarkerColor: 'Effect colour',
    settingMarkerAuto: 'Each one’s squad colour',
    squadSharesView: 'Pins',
    mapPin: 'Drop a pin (show the squad the place you press; press again to move it until you stop)',
    mapPinCancel: 'Stop dropping a pin (Esc)',
    mapPinRemove: 'Take out your pin',
    mapPinDrag: 'Drag to move it',
    mapFresh: 'A squadmate drew something new',
    squadColor: 'Squad colour',
    squadColorAuto: 'Automatic',
    squadColorTaken: '{name} has it',
    squadColorHelp:
      'The colour of your marker on the map. A colour someone else has cannot be chosen; Automatic takes a free one.',
    squadColorBusy: 'Someone else has the colour chosen, so you have an automatic one for now.',
    squadCreate: 'Create a squad',
    squadJoin: 'Join',
    squadLeave: 'Leave the squad',
    squadLeaveQuick: 'Leave the squad (press twice)',
    squadLeaveConfirm: 'Press again to leave',
    squadShot: 'Screenshot',
    squadShotOn: 'Screenshot on {map}',
    squadSharesShots: 'Screenshots',
    settingShotBubble: 'Screenshots with the position',
    settingShotBubbleHint:
      'A screenshot of the position shows in a bubble by your arrow on the map (pressed, large). In a squad it goes to the squad too, small (one every 20 seconds at most; the same screenshot never twice)',
    settingOpenOnRaid: 'Show the map when a raid starts',
    settingOpenOnPosition: 'Show the map on a position screenshot',
    squadShotSize: 'Size of large pictures',
    squadShotSizeHint: 'Screenshots shared by hand, and large pictures a squadmate asks for, go at this size',
    squadShotSizeFull: 'As taken',
    squadShotSize1080: '1080p',
    squadShotSize720: '720p',
    mapShotClose: 'Close (pressing outside closes it too)',
    squadShotLarge: 'See it large',
    squadShotLargeHint: 'Asks whoever sent it for the large picture (while they are connected)',
    squadShotAsking: 'Asking…',
    squadShareShotHint: 'Sends this screenshot to the squad, large',
    squadShotSentAlready: 'This screenshot went already',
    squadCopy: 'Copy the code',
    squadCopied: 'Copied',
    squadPhase_connecting: 'Connecting…',
    squadPhase_connected: 'Connected',
    squadPhase_offline: 'Cannot reach the relay (retrying)',
    squadPhase_full: 'The squad is full (10 at most)',
    squadYou: 'you',
    squadOutOfRaid: 'Not in a raid',
    squadViewer:
      'This PC is a client, so it only watches (the Host sends the position). Creating, joining and leaving a squad follow the Host.',
    squadPrivacy:
      'Only your display name, your squad colour, where you take screenshots in a raid and the squad pen’s lines and position are shared. They are encrypted with the squad code; the relay cannot read them.',
    squadInvalidCode: 'A squad code has 8 characters (e.g. ABCD-1234)',
    squadNeedName: 'Enter a display name',
    // Toolbar, sidebar, welcome page, settings
    home: 'Home',
    settings: 'Settings',
    menu: 'Menu',
    off: 'Receiving off',
    back: 'Back',
    forward: 'Forward',
    reload: 'Reload',
    address: 'Search Google or type a URL',
    open: 'Open',
    close: 'Close',
    pin: 'Pin',
    unpin: 'Unpin',
    newTab: 'New tab',
    welcome: 'Get ready for your next raid.',
    intro: 'Maps, tasks and research, together in one window.',
    maps: 'Maps',
    tasks: 'Task guides',
    items: 'Items',
    progress: 'Progress',
    other: 'Other',
    addBookmark: 'Add bookmark',
    edit: 'Edit',
    delete: 'Delete',
    name: 'Name',
    url: 'URL',
    group: 'Category',
    done: 'Done',
    cancel: 'Cancel',
    empty: 'Add bookmarks to keep your useful sites together.',
    client: 'Browser settings',
    host: 'Host settings & logs',
    appearance: 'Appearance',
    language: 'Language',
    layout: 'Tab placement',
    vertical: 'Left sidebar',
    horizontal: 'Across the top',
    recognition: 'Automatic task navigation',
    taskMode: 'Open recognized tasks',
    reuse: 'Reuse the task tab',
    new: 'Add a new tab',
    questSite: 'Website',
    hostChoice: 'Follow Host setting',
    official: 'Official Wiki',
    japanese: 'Japanese Wiki',
    taskHelp:
      'Switch the current task between English and Japanese wikis using the website selector above. Pinned tabs are never replaced automatically.',
    connection: 'Host connection',
    mode: 'Connection mode',
    local: 'Host: Escape from Tarkov runs on this PC',
    localHelp:
      'Choose this on the PC you play on: tasks, maps and items found in screenshots and logs open in tabs here and go to the PCs paired with it.',
    clientHelp:
      'Escape from Tarkov runs on another PC (the Host); what its MAYAK finds shows here. Pair with the Host below.',
    bookmarkHelp: 'Click a card to open it. Names and categories are editable.',
    tabHelp: 'Drag to reorder',
    dismiss: 'Dismiss',
    searchWiki: 'Search this Wiki',
    pinHelp: 'Pinned',
    // Bosses, Goons reports, clock, screenshots
    bossMapBosses: "Map's bosses",
    goonReport: 'Report the Goons',
    goonReportOnly:
      'Only report a raid where you actually ran into the Goons. The report is added to the sightings shown on tarkov.dev.',
    goonAccount: 'Account to report with (from the EFT logs)',
    goonNoAccount: 'No account in the EFT logs yet. Start the game once.',
    goonWhen: 'When you saw them',
    goonRaidNow: 'This raid',
    goonRaidLast: 'The last raid',
    goonStarted: 'start',
    goonAlready: 'reported',
    goonWhenNow: 'Report at the current time',
    goonConsent:
      'tarkov.dev stores the report together with your IP address and the EFT account ID you chose, so that misuse can be traced.',
    goonSend: 'Report',
    goonSending: 'Sending…',
    goonReported: 'Reported. It shows in the tarkov.dev sightings within about ten minutes.',
    goonCurrent: 'playing',
    goonLastSeen: 'last seen',
    bossAuto: 'Auto',
    bossModeLabel: 'Game mode',
    bossPickHint: 'Choose a map, or enter a raid, to see its bosses',
    clockFormat: 'Time format',
    clock24: '24-hour (13:05)',
    clock12: '12-hour (1:05 PM)',
    shotKind_tasks: 'Task',
    shotKind_item: 'Item',
    shotKind_offer: 'Offer',
    shotKind_position: 'Position',
    shotKind_unknown: 'Not recognized',
    shotInfo: 'Recognition details',
    shotInfoKind: 'Kind',
    shotInfoMatch: 'Match',
    shotInfoConfidence: 'Match confidence',
    shotInfoCandidates: 'Candidates',
    shotInfoLayout: 'Layout',
    shotInfoScore: 'Detection score',
    shotInfoMap: 'Map',
    shotInfoRaid: 'In raid',
    shotInfoPosition: 'Position',
    shotInfoStage: 'Stage',
    shotInfoError: 'Error',
    yes: 'Yes',
    no: 'No',
    bosses: 'Bosses',
    allBosses: 'Boss details',
    bossesLoading: 'Loading bosses…',
    noGoons: 'no recent reports',
    noBosses: 'No bosses',
    escorts: 'Escorts',
    goonHint:
      'Goons locations are player reports (tarkov.dev). The newer a report, the likelier they are still on that map.',
    goonMaps: 'Maps the Goons spawn on',
    bossMaps: 'Maps',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    zoomFit: 'Fit to page (reset)',
    screenshots: 'Screenshots',
    allScreenshots: 'All screenshots',
    noScreenshots: 'No screenshots yet',
    screenshotsHostOnly: 'Screenshots are shown on the Host computer',
    openScreenshotFolder: 'Open folder',
    newerScreenshot: 'Newer',
    olderScreenshot: 'Older',
    clientConnection: 'Client: Escape from Tarkov runs on another PC (the Host)',
    p2pTitle: 'Send to another PC',
    p2pReceive: 'Connect to a Host',
    p2pHelp:
      'Open MAYAK on the Host and the other PC and enter the 8-digit code shown on the Host into the other one. A Host takes any number of PCs (a code for each). Paired PCs remember each other and connect again on their own at every start. What they say goes through a relay (mayak-relay.ich.sh), encrypted with a key only the paired PCs have, so the relay cannot read it.',
    pairCodeHelp:
      'On the other PC, open MAYAK → Settings → Connection, choose the Client mode and enter this number. It expires in 10 minutes.',
    enterPairCode: 'The 8-digit code shown on the Host',
    joinPair: 'Connect',
    manualExchange: 'Hand the code over yourself (no mayak.ich.sh)',
    manualExchangeHelp: 'To keep mayak.ich.sh out of it, copy this long code to the other PC yourself.',
    relayFailed: 'The pairing server (mayak.ich.sh) could not be reached; hand the long code below over yourself.',
    p2pLimit:
      'Only what the Host recognizes (tasks, maps, positions, items) and the squad joined are sent. Unpairing on the Host makes every paired PC forget it; unpairing on a Client takes only that PC out.',
    createInvite: 'Get a code',
    inviteCode: 'Invitation code',
    copyCode: 'Copy code',
    peerHostName: 'The Host',
    peerClientNames: 'PCs connected',
    peerSelfName: 'This PC',
    copied: 'Copied',
    showCode: 'Show the code',
    hideCode: 'Hide the code',
    enterOffer: 'Paste the long invitation from the Host',
    acceptInvite: 'Connect',
    unpairPeer: 'Unpair this PC',
    cancelPairing: 'Cancel',
    linkIdle: 'Not paired',
    linkConnecting: 'Connecting to the relay…',
    linkWaitingHost: 'Waiting for the Host (its MAYAK is not running or not connected)',
    linkWaitingClient: 'Waiting for the other PC',
    linkConnected: 'Connected',
    linkConnectedCount: 'Connected to {n} PCs',
    addPeer: 'Add another PC (get a code)',
    unpairAll: 'Unpair every PC',
    linkReceive: 'Show on this PC',
    linkReceive_task: 'Tasks',
    linkReceive_map: 'Maps and positions',
    linkReceive_item: 'Items',
    linkReceiveHelp: 'Which of the Host’s detections open on this PC (one PC the map, another the tasks, for example).',
    linkOffline: 'The relay cannot be reached; trying again…',
    linkFailed: 'Could not connect.',
    p2pExpired: 'The pairing code has expired.',
    // Tutorial
    tutorialShow: 'Show the tutorial',
    tutorialShowHelp: 'See the first-run guide again: folders, the screenshot key, the map and TarkovTracker.',
    tutStep: 'Step',
    tutStart: 'Get started',
    tutLater: 'Later',
    tutNext: 'Next',
    tutBack: 'Back',
    tutSkip: 'Skip',
    tutFinish: 'Done',
    tutWelcomeTitle: 'Welcome to MAYAK',
    tutWelcome:
      'MAYAK reads only the screenshots you take in the game and the logs it writes, and shows maps, tasks and item info in this window. It never touches the game itself. Follow this guide and setup takes a few minutes.',
    tutFoldersTitle: 'EFT folders',
    tutFolders:
      'The Screenshots and Logs folders were looked up automatically. If they are wrong, pick them in the settings.',
    tutFoldersScreens: 'Screenshots',
    tutFoldersLogs: 'Logs',
    tutNotFound: 'Not found; pick it in the settings',
    tutOpenFolders: 'Open the folder settings',
    tutKeyTitle: 'Put the screenshot key within reach',
    tutKey:
      'In EFT: Settings → Controls → Screenshot. The default is PrintScreen, which is hard to reach mid-fight, so bind it to a mouse side button or a free key near your left hand.',
    tutKeyNote:
      'Only screenshots taken with EFT’s own function carry coordinates; Steam or Windows screenshots do not.',
    tutMapTitle: 'In a raid, just press that key',
    tutMap:
      'The map tab in this window follows your position with no setup. Screenshot a task opened in the Tasks screen, or an item window, and that info appears too (the list alone does not show which task). On one PC with several monitors, that is all you need.',
    tutOpenMap: 'Open the map',
    tutRemoteTitle: 'Another PC or your usual browser (optional)',
    tutRemote:
      'Open the tarkov.dev map there and click the connect button at the bottom left. Chrome, Edge and Brave on this PC are detected automatically; from another PC or a tablet, type the Remote ID in. To run MAYAK itself on another PC, pair it with the 8-digit code under Settings → Other computers.',
    tutOpenRemote: 'Open the tarkov.dev settings',
    tutTrackerTitle: 'Let TarkovTracker record your progress (optional)',
    tutTracker:
      'TarkovTracker is a free site that tracks task progress. Create a token with GP and WP under Settings → API Tokens, add it here, and accepted, completed and failed tasks are recorded automatically.',
    tutOpenTracker: 'Open the TarkovTracker settings',
    tutDoneTitle: 'All set',
    tutDone: 'You can see this guide again under Settings → Appearance. Good raids.',
    tutSupport:
      'MAYAK is free. If you like it, you can support its development on Buy Me a Coffee (also under Settings → About MAYAK).',
    // Tab list and updates
    allTabs: 'All tabs',
    searchTabs: 'Search tabs',
    tabsHint: 'Every open tab, by name and address. Click one to switch to it, × to close it.',
    noTabResults: 'No tabs match.',
    tabsClose: 'Close tab',
    snapNotes: 'Snap notes',
    snapFromShot: 'Make a snap note',
    snapFromShotHelp: 'Turn this screenshot into a standalone snap note to draw on',
    snapNotesAll: 'All snap notes',
    snapTake: 'Snap note (capture this page and draw on it)',
    snapVisible: 'Capture what is on screen',
    snapVisibleHint: 'The part of the page in the window',
    snapFull: 'Capture the whole page',
    snapFullHint: 'A long page in one image, down to its end (up to 15000 px)',
    snapThisPage: 'Notes of this page',
    snapShowAll: 'Open all snap notes',
    snapCapturing: 'Capturing…',
    snapCaptureFailed: 'Could not capture the page: ',
    snapEmpty:
      'No snap notes yet. Open a page and capture it with the pen button in the toolbar, or start from a blank sheet or an image.',
    snapNewBlank: 'Start from a blank sheet',
    snapNewImage: 'Start from an image file',
    snapPasteHint: 'Ctrl+V starts one from an image on the clipboard too.',
    snapFilterAll: 'All',
    snapFilterLinked: 'Page notes',
    snapFilterSingle: 'Standalone notes',
    snapFilterFavorite: 'Favorites',
    snapFavorite: 'Add to favorites',
    snapUnfavorite: 'Remove from favorites',
    snapTitlePlaceholder: 'Note name',
    snapRename: 'Rename',
    snapNoMatch: 'No notes match.',
    snapSingle: 'Standalone',
    snapBack: 'Back to the list',
    snapTitle: 'Title',
    snapPen: 'Pen',
    snapEraser: 'Eraser (removes whole lines)',
    snapText: 'Text (click to type, click a text to edit it, drag to move it)',
    snapTextHint: 'Click outside the box to finish; Enter starts a new line',
    snapTexts: '{n} texts',
    snapTextSize: 'Text size',
    snapFont: 'Font',
    snapSpot: 'Taken at',
    snapFacing: 'facing',
    snapShowSpot: 'Show on tarkov.dev',
    snapShowSpotHint:
      'Shows where it was taken, and the direction, on the map tab (and the maps connected by Remote Control)',
    snapPickMap: 'Choose the map',
    snapPickMapHint: 'The map of this screenshot is not known; choose it to show the position',
    snapSpotShown: 'Shown on the map',
    snapFontDefault: 'Default',
    snapOutline: 'Outline',
    snapOutlineAuto: 'Auto',
    snapOutlineAutoHint: 'White or black, against the text colour',
    snapOutlineColor: 'Outline colour',
    snapOutlineWidth: 'Outline width',
    snapMoreColors: 'More colours',
    snapTextMove: 'Drag to move',
    snapShare: 'Share',
    snapCopyImage: 'Copy image',
    snapCopyImageHint: 'With the drawing, to the clipboard',
    snapSaveAs: 'Save as…',
    snapSaveAsHint: 'Save as a PNG image',
    snapPostX: 'Post to X',
    snapPostXHint: 'Copies the image and opens a new X post in your browser',
    snapCopied: 'Copied',
    snapExported: 'Saved',
    snapPostXReady: 'Image copied',
    snapPostXPaste: 'Press Ctrl+V in the X post that opens in your browser to paste the image.',
    snapPostXOpening: 'Opening X…',
    snapShareFailed: 'Could not do that',
    snapUndo: 'Undo (Ctrl+Z)',
    snapRedo: 'Redo (Ctrl+Y)',
    snapClear: 'Remove all lines of this layer',
    snapLayers: 'Layers',
    snapLayer: 'Layer {n}',
    snapLines: '{n} lines',
    snapLayerClear: 'Remove the lines of this layer',
    snapOriginal: 'Original image',
    snapAdjust: 'Viewing adjustments',
    snapAdjustReset: 'Reset',
    snapBrightness: 'Brightness',
    snapContrast: 'Contrast',
    snapShadows: 'Lift shadows',
    snapAdjustHint: 'Only the view changes; the original image stays as it is.',
    snapOriginalHint: 'Never edited',
    snapHide: 'Hide',
    snapShow: 'Show',
    snapSizeS: 'Thin line',
    snapSizeM: 'Medium line',
    snapSizeL: 'Thick line',
    snapFit: 'Fit to width (Ctrl+0)',
    snapActual: 'Show at 100%',
    snapZoomIn: 'Zoom in (Ctrl+wheel, Ctrl++)',
    snapZoomOut: 'Zoom out (Ctrl+wheel, Ctrl+-)',
    snapOpenPage: 'Open the page',
    snapUnlink: 'Unlink from the page',
    snapRelink: 'Link to its page again',
    snapDelete: 'Delete',
    snapDeleteConfirm: 'Press again to delete',
    snapSaved: 'Saved',
    snapSaveFailed: 'Could not save',
    snapSaving: 'Saving…',
    snapLinked: 'Note of this page',
    snapUnlinked: 'Unlinked from its page',
    snapNoPage: 'Standalone note',
    snapColor: 'Colour',
    updateSection: 'Updates',
    updateChannel: 'Version to use (update channel)',
    updateChannelStable: 'Stable',
    updateChannelStableHelp: 'Updates to released versions only. The usual choice.',
    updateChannelNightly: 'Nightly',
    updateChannelNightlyHelp:
      'Also updates to the version in development, built every day. New features arrive early, but bugs may remain.',
    updateChannelHelp:
      'On nightly, a newer stable release is installed instead. Back on stable, a downloaded nightly is dropped and the next stable release is installed when it comes out (the version you have is not rolled back).',
    updateCurrent: 'This version',
    updateLatest: 'Latest version',
    updateCheck: 'Check for updates',
    updateChecking: 'Checking…',
    updateCheckedAt: 'Last checked',
    updateUpToDate: 'Up to date',
    updateNever: 'Not checked yet',
    updateUnsupported: 'No build for this platform',
    updateError: 'Could not check',
    updateAutoNote: 'Automatic updates are switched under Settings → Startup & window.',
    updateDownloading: 'Downloading MAYAK {v}',
    updateReady: 'MAYAK {v} is ready',
    updateRestart: 'Restart to apply',
    updateDownload: 'Download',
    updateLater: 'Later',
    updateNotes: 'What changed',
    updateReadyHint: 'If you do not apply it now, it is installed when MAYAK next quits.',
    // Translate, sidebar, theme, ad blocking
    translatePage: 'Translate this page (Google Translate)',
    translateOff: 'Stop translating, back to the page itself',
    translateWiki: 'Open the official wiki (English) translated',
    translateWikiHelp:
      'Task pages on the official wiki open through Google Translate (translate.goog). WebView2 has no page translation of its own, so this stands in for it. The translate button in the toolbar does the same for any page.',
    homeHelp: 'Back to the start page',
    fixedAddress: 'This view is fixed; its address cannot be edited',
    openExternal: 'Open in default browser',
    closeSettings: 'Close settings',
    devInstance: 'Development build (task dev): its data is kept in Mayak-dev, so it runs beside the installed MAYAK',
    collapseSection: 'Collapse',
    expandSection: 'Expand',
    groupHint: 'Choose or type',
    resizeSidebar: 'Drag to resize (double-click to reset)',
    allBookmarks: 'All bookmarks',
    searchBookmarks: 'Search bookmarks',
    gridView: 'Tiles',
    listView: 'List',
    pinToSidebar: 'Pin to sidebar',
    unpinFromSidebar: 'Remove from sidebar',
    bookmarkDropHint: 'Drag bookmarks here to pin them',
    bookmarkDragHint: 'Drag a bookmark onto “Bookmarks” in the sidebar to pin it there.',
    noBookmarkResults: 'No bookmarks match.',
    collapseSidebar: 'Close sidebar',
    expandSidebar: 'Open sidebar',
    minimise: 'Minimize',
    maximise: 'Maximize',
    restore: 'Restore',
    theme: 'Theme',
    themeSystem: 'Match system',
    adblock: 'Ad blocking',
    adblockEnable: 'Block ads and trackers',
    adblockHelp:
      'Blocks ads with EasyList, EasyPrivacy and the AdGuard Japanese filter, and closes the gaps they leave. The filter lists are published by EasyList (easylist.to) and AdGuard and update automatically. tarkov.dev is excluded because ads fund it. Changing this reloads the current page.',
    mapTab: 'TARKOV.DEV',
    mapTabHelp: 'tarkov.dev map, kept connected via Remote Control. Detected maps and positions appear here.',
    tabs: 'Tabs',
    bookmarks: 'Bookmarks',
    hostMode: 'Host mode',
    clientMode: 'Client mode',
    menuHint: 'MAYAK menu',
    noTabs: 'Open a website or settings from the logo menu.',
    // Status bar, settings sections, about
    tracker_connected: 'synced',
    tracker_connecting: 'connecting',
    'tracker_waiting-profile': 'waiting for profile',
    'tracker_missing-token': 'no API key',
    tracker_error: 'error',
    tracker_disabled: 'off',
    monitorOn: 'Monitoring',
    monitorOff: 'Not monitoring',
    monitorStart: 'Click to start monitoring',
    monitorStop: 'Click to stop monitoring',
    inRaid: 'In raid',
    outRaid: 'Out of raid',
    trackerLabel: 'TarkovTracker',
    taskSiteHelp:
      'Where recognized tasks and tasks opened from the item sidebar open. Whether tasks go to tarkov.dev Remote Control is set per target under tarkov.dev link.',
    taskSiteClientHelp: '"Follow Host setting" opens the site chosen on the Host.',
    settingsBack: 'Close settings',
    grpGeneral: 'General',
    grpGame: 'Game',
    grpLinks: 'Connections',
    grpBrowser: 'Browser',
    grpDiagnostics: 'Status & diagnostics',
    sec_appearance: 'Appearance',
    sec_tasks: 'Opening tasks',
    sec_adblock: 'Ad blocking',
    sec_connection: 'Other computers',
    sec_status: 'Status',
    sec_logs: 'Logs',
    sec_folders: 'Folders & storage',
    sec_recognition: 'Game & recognition',
    sec_remote: 'tarkov.dev link',
    sec_tracker: 'TarkovTracker',
    sec_sounds: 'Notifications',
    sec_startup: 'Startup & window',
    sec_debug: 'Debug',
    grpAbout: 'About',
    sec_about: 'About MAYAK',
    sec_licenses: 'Licenses & credits',
    licLicense: 'License text',
    licNotices: 'Third-party licenses',
    licNoticesHelp:
      'The licenses of the bundled libraries and OCR data are in THIRD_PARTY_NOTICES.txt, in the folder MAYAK is in.',
    licData: 'Data',
    licVoices: 'Built-in voices',
    licVoicesNote:
      'The notification voices were made with VOICEVOX (Japanese) and Kokoro-82M (English, Apache-2.0). They are not under the GPL-3.0 of MAYAK but their own terms. Do not extract the audio files to redistribute them.',
    licTerms: 'Terms of use',
    licChecked: 'Terms checked',
    licVoicevoxTerms: 'VOICEVOX terms of use',
    aboutVersion: 'Version',
    aboutDev: 'development build',
    aboutTagline: 'A companion that turns Escape from Tarkov screenshots and logs into map, task and item information.',
    aboutSite: 'Website',
    aboutSource: 'GitHub',
    aboutReleases: 'Changelog',
    aboutSupport: 'Support on Buy Me a Coffee',
    aboutSupportTitle: 'Support MAYAK',
    aboutSupportHint:
      'MAYAK is free and made by one person. If it helps you, the price of a coffee keeps its development going.',
    aboutLicense: 'Released under the GPL-3.0.',
    aboutCredits:
      'Maps come from tarkov.dev and task progress from TarkovTracker, through their data and APIs. Escape from Tarkov is a trademark of Battlestate Games; MAYAK is an unofficial tool.',
    // Layout and item panel
    placement: 'Change the layout',
    navPosition: 'Tabs position',
    itemDock: 'Item details position',
    placeLeft: 'Left',
    placeRight: 'Right',
    placeTop: 'Top',
    placeBottom: 'Bottom',
    openItemPage: 'Open the item page',
    itemSearch: 'Search items',
    itemSearchHint:
      'Search by item name with the magnifier above, or inspect an item in the game and take a screenshot to see it here.',
    itemNoResults: 'No items found',
    openTask: 'Open task',
    itemPanel: 'Item',
    itemShow: 'Show item details',
    itemHide: 'Close item details',
    itemRefresh: 'Get the latest prices',
    itemLive: 'LIVE',
    itemCatalog: 'Catalog',
    itemPriced: 'Prices updated',
    bestSale: 'Sells best to',
    perSlot: 'per slot',
    flea: 'Flea market',
    fleaLow: 'Lowest offer',
    fleaAvg: '24h average',
    fleaRange: '24h range',
    fleaChange: '48h change',
    fleaOffers: 'Offers',
    fleaLevel: 'Unlocks at level',
    noFlea: 'Cannot be sold on the flea market',
    traders: 'Trader buy prices',
    itemTasks: 'Needed for tasks',
    itemHideout: 'Needed for hideout',
    itemLocks: 'Used at',
    itemLockCount: '%d places',
    itemLockSpot: 'Place %d',
    itemLockShowAll: 'Show all of them on the map',
    itemLockShow: 'Show it on the map',
    noNeeds: 'None',
    fir: 'FIR',
    needDone: 'Done',
    progressUnknown: 'Sync TarkovTracker to see what is done',
    // Price chart
    priceHistory: 'Price history',
    range7d: '7D',
    range30d: '30D',
    rangeAll: 'All',
    avgLine: 'Average',
    minLine: 'Lowest',
    chartHigh: 'High',
    chartLow: 'Low',
    chartLoading: 'Loading price history…',
    chartFailed: 'Could not load the price history',
    chartEmpty: 'No history for this period',
    chartNow: 'Now',
    // Popup window and api.js messages
    popupPin: 'Pin (stays open when you click elsewhere)',
    popupUnpin: 'Unpin',
    openInTab: 'Open in a tab',
    openExternalBrowser: 'Open in external browser',
    actionFailed: 'Could not complete the action: ',
    enterWebURL: 'Enter an http or https URL',
  },
}

// t returns key's text in language, falling back to Japanese, then the key.
export const t = (language, key) => (words[language] || words.ja)[key] ?? key
