// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Flea {
    "lastLow": number;
    "avg24h": number;
    "low24h": number;
    "high24h": number;
    "changePercent": number;
    "offers": number;
    "minLevel": number;

    /** Creates a new Flea instance. */
    constructor($$source: Partial<Flea> = {}) {
        if (!("lastLow" in $$source)) {
            this["lastLow"] = 0;
        }
        if (!("avg24h" in $$source)) {
            this["avg24h"] = 0;
        }
        if (!("low24h" in $$source)) {
            this["low24h"] = 0;
        }
        if (!("high24h" in $$source)) {
            this["high24h"] = 0;
        }
        if (!("changePercent" in $$source)) {
            this["changePercent"] = 0;
        }
        if (!("offers" in $$source)) {
            this["offers"] = 0;
        }
        if (!("minLevel" in $$source)) {
            this["minLevel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Flea instance from a string or object.
     */
    static createFrom($$source: any = {}): Flea {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Flea($$parsedSource as Partial<Flea>);
    }
}

export class HideoutNeed {
    "levelId": string;
    "station": string;
    "level": number;
    "count": number;
    "foundInRaid": boolean;

    /**
     * Complete is nil when hideout progress is unknown.
     */
    "complete": boolean | null;

    /** Creates a new HideoutNeed instance. */
    constructor($$source: Partial<HideoutNeed> = {}) {
        if (!("levelId" in $$source)) {
            this["levelId"] = "";
        }
        if (!("station" in $$source)) {
            this["station"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("foundInRaid" in $$source)) {
            this["foundInRaid"] = false;
        }
        if (!("complete" in $$source)) {
            this["complete"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HideoutNeed instance from a string or object.
     */
    static createFrom($$source: any = {}): HideoutNeed {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HideoutNeed($$parsedSource as Partial<HideoutNeed>);
    }
}

export class Info {
    "id": string;
    "mode": string;
    "name": string;
    "shortName": string;

    /**
     * Names and ShortNames are the names in other languages (see
     * internal/locale), when they differ; the sidebar shows the one in its
     * language.
     */
    "names"?: { [_ in string]?: string };
    "shortNames"?: { [_ in string]?: string };
    "iconUrl": string;
    "link": string;
    "wikiLink": string;
    "width": number;
    "height": number;
    "basePrice": number;

    /**
     * Flea is nil when the item cannot be sold on the flea market.
     */
    "flea": Flea | null;
    "traders": TraderPrice[];
    "tasks": TaskNeed[];
    "hideout": HideoutNeed[];

    /**
     * Live is true when the prices came from the GraphQL API just now; the
     * catalog snapshot is at most catalog.RefreshInterval old otherwise.
     */
    "live": boolean;

    /**
     * QuestSite is the Host's preferred site for opening tasks.
     */
    "questSite"?: string;
    "pricedAt": string;
    "fetchedAt": string;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("iconUrl" in $$source)) {
            this["iconUrl"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }
        if (!("wikiLink" in $$source)) {
            this["wikiLink"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("basePrice" in $$source)) {
            this["basePrice"] = 0;
        }
        if (!("flea" in $$source)) {
            this["flea"] = null;
        }
        if (!("traders" in $$source)) {
            this["traders"] = [];
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }
        if (!("hideout" in $$source)) {
            this["hideout"] = [];
        }
        if (!("live" in $$source)) {
            this["live"] = false;
        }
        if (!("pricedAt" in $$source)) {
            this["pricedAt"] = "";
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType4;
        const $$createField14_0 = $$createType6;
        const $$createField15_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField4_0($$parsedSource["names"]);
        }
        if ("shortNames" in $$parsedSource) {
            $$parsedSource["shortNames"] = $$createField5_0($$parsedSource["shortNames"]);
        }
        if ("flea" in $$parsedSource) {
            $$parsedSource["flea"] = $$createField12_0($$parsedSource["flea"]);
        }
        if ("traders" in $$parsedSource) {
            $$parsedSource["traders"] = $$createField13_0($$parsedSource["traders"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField14_0($$parsedSource["tasks"]);
        }
        if ("hideout" in $$parsedSource) {
            $$parsedSource["hideout"] = $$createField15_0($$parsedSource["hideout"]);
        }
        return new Info($$parsedSource as Partial<Info>);
    }
}

/**
 * PricePoint is one flea market sample: the average and lowest offer at Time
 * (Unix milliseconds). Older samples are daily, recent ones a few per day.
 */
export class PricePoint {
    "t": number;
    "price": number;
    "min": number;
    "offers"?: number;

    /** Creates a new PricePoint instance. */
    constructor($$source: Partial<PricePoint> = {}) {
        if (!("t" in $$source)) {
            this["t"] = 0;
        }
        if (!("price" in $$source)) {
            this["price"] = 0;
        }
        if (!("min" in $$source)) {
            this["min"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PricePoint instance from a string or object.
     */
    static createFrom($$source: any = {}): PricePoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PricePoint($$parsedSource as Partial<PricePoint>);
    }
}

export class TaskNeed {
    "id": string;
    "name": string;

    /**
     * Names are the task's names in other languages, when they differ.
     */
    "names"?: { [_ in string]?: string };
    "trader": string;
    "count": number;
    "foundInRaid": boolean;

    /**
     * State is the TarkovTracker state ("completed", "failed",
     * "uncompleted") or empty when progress is unknown.
     */
    "state": string;

    /**
     * URLs is the task's page per quest site (tarkov-dev, official-wiki,
     * japanese-wiki), for opening it from the item sidebar.
     */
    "urls"?: { [_ in string]?: string };

    /** Creates a new TaskNeed instance. */
    constructor($$source: Partial<TaskNeed> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("trader" in $$source)) {
            this["trader"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("foundInRaid" in $$source)) {
            this["foundInRaid"] = false;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskNeed instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskNeed {
        const $$createField2_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField2_0($$parsedSource["names"]);
        }
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField7_0($$parsedSource["urls"]);
        }
        return new TaskNeed($$parsedSource as Partial<TaskNeed>);
    }
}

export class TraderPrice {
    "trader": string;
    "price": number;
    "currency": string;
    "priceRub": number;

    /** Creates a new TraderPrice instance. */
    constructor($$source: Partial<TraderPrice> = {}) {
        if (!("trader" in $$source)) {
            this["trader"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = 0;
        }
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("priceRub" in $$source)) {
            this["priceRub"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraderPrice instance from a string or object.
     */
    static createFrom($$source: any = {}): TraderPrice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TraderPrice($$parsedSource as Partial<TraderPrice>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Flea.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = TraderPrice.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = TaskNeed.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = HideoutNeed.createFrom;
const $$createType8 = $Create.Array($$createType7);
